### ISSUE TITLE
About HTTP parameter Settings

### ISSUE THREAD

**Issue by ghost** [shadowsocks/v2ray-plugin#100]
I look at the command line with the method，Then I tried to config. Join in json：

"plugin":"/usr/bin/v2ray-plugin",
"plugin_opts":"server"

I want to know how to set up the specified confusion，Such as this"plugin_opts":"server;http;host=xxx.com"

I want to know whether this is feasible, and how should the client configuration？

**Comment by lcdtyph** [comment]
The plugin_opts has format "opt=val" where opt is same as the command line. Here is an example:

```json
    "plugin_opts": "server;mode=http;host=xxx.com;path=/abcdefg;cert=xxx.cer;key=xxx.key;fast-open"
```

**Comment by goovich** [comment]
I'm getting "Permission denied" note. Could you please help me debug the issue?

```
ss-server -c config.json
 2019-07-23 16:45:32 INFO: using tcp fast open
 2019-07-23 16:45:32 INFO: plugin "v2ray-plugin" enabled
 2019-07-23 16:45:32 INFO: initializing ciphers... aes-256-cfb
 2019-07-23 16:45:32 INFO: tcp server listening at 127.0.0.1:61319
 2019-07-23 16:45:32 INFO: running from root user
Permission denied
 2019-07-23 16:45:32 ERROR: plugin service exit unexpectedly
```

**Comment by lcdtyph** [comment]
Please post your config.json and omit your personal fields.

Is this result of directly executing from shell or systemd?

**Comment by goovich** [comment]
> Please post your config.json and omit your personal fields.
> 
> Is this result of directly executing from shell or systemd?
Hi there, v2ray-plugin was in root folder, moved it to /etc/ and solved the problem. At least the "permission denied" one.
