### ISSUE TITLE
Any plans to support mKCP/QUIC with obfuscation transport?

### ISSUE THREAD

**Issue by maddie** [shadowsocks/v2ray-plugin#101]
I'm wondering if you guys have any plans on this, or did you deliberately not implement them?

I have a local fork with these implemented, and I would love to submit a PR if it's OK.

And a side question for V2Ray mKCP/QUIC obfuscation transport:

I've got mKCP with obfuscation working already, but with QUIC with obfuscation, in spite of it runs fine, it doesn't seem to work as expected, as in:

mKCP with obfuscation:

server `srtp` + local `wechat-video` = not working (which should be expected, since they're using different obfuscation settings)
server `srtp` + local `wireguard` = works (i'm not sure if it's right? or maybe they obfuscate the same way?)

QUIC with obfuscation:

Any combination (`srtp`, `wechat-video`, `wireguard`, `utp`, `dtls`) seems to work somehow, so I wonder maybe it's not really working..

Thanks!

EDIT: Formatting

**Comment by Mygod** [comment]
For now I don't see why it's necessary to use obfuscation and I prefer QUIC to mKCP. Feel free to keep using your fork though.
