### ISSUE TITLE
UDP Forwarding

### ISSUE THREAD

**Issue by mriksman** [shadowsocks/v2ray-plugin#104]
I'm not sure UDP forwarding is working. My Google search led me to;
#70 @Mygod 

I have Shadowsocks-libev and v2ray-plugin. Config is;
```
"server":"0.0.0.0",
"server_port":1080,
"password":"xxxxxxxx",
"timeout":600,
"plugin": "v2ray-plugin",
"method":"aes-256-cfb",
"plugin_opts": "server;tls;host=example.com",
"mode":"tcp_and_udp"
```

When I start the program, I see the following;
```
Started Shadowsocks-libev Server Service.
 2019-07-19 15:00:58 INFO: plugin "v2ray-plugin" enabled
 2019-07-19 15:00:58 INFO: UDP relay enabled
 2019-07-19 15:00:58 INFO: initializing ciphers... aes-256-cfb
 2019-07-19 15:00:58 INFO: tcp server listening at 127.0.0.1:35741
 2019-07-19 15:00:58 INFO: udp server listening at 0.0.0.0:1080
2019/07/19 15:00:58 V2Ray 4.16 (Po) Custom
```
I'm not sure the 'udp server listening' is correct? 

I connected via Shadowsocks Windows (with the v2ray-plugin exe), and it connects/works fine. 

On the remote end, I loaded `ncat -l 2399` on a Windows PC (192.168.0.40) connected to the same network as the Shadowsocks Server (192.168.0.5). 
On the client end, I loaded `ncat --proxy localhost:1080 192.168.0.40 2399`. The logs on the Shadowsocks Server looks good;
```
2019/07/19 15:34:33 tcp:82.129.207.50:42526 accepted tcp:127.0.0.1:0
 2019-07-19 15:34:33 INFO: accept a connection
 2019-07-19 15:34:33 INFO: [1080] connect to 192.168.0.40:2399
```
What ever I typed in the client console window, appeared on the remote PC. Great.

When I change `ncat `to use UDP `-u`, it says it connects, but then the connection is immediately dropped;
```
2019/07/19 15:38:17 tcp:196.219.32.146:46166 accepted tcp:127.0.0.1:0
 2019-07-19 15:38:17 INFO: accept a connection
 2019-07-19 15:38:17 INFO: [1080] connect to 192.168.0.40:2399
 2019-07-19 15:38:20 INFO: server_recv close the connection
 2019-07-19 15:38:20 INFO: current remote connection: 19
 2019-07-19 15:38:20 INFO: current server connection: 19
```

@Mygod - you've previously replied 'Use UDP Fallback'. What is this? Is it available on any other client other than Android? 
I only have one port forward into my server - TCP port 443. And v2ray and the TLS certificate is used to secure the connection to Cloudflare. 

Any help would be appreciated.

**Comment by Sraw** [comment]
Don't know what you are testing. But 

> I'm not sure the 'udp server listening' is correct?

It is correct. Which means you need to send UDP to port 1080.

**Comment by tty7tyil** [comment]
I’m testing udp forwarding under the exact same environment too, everything seems to work, but I do not know any direct way to test udp forwarding.

**Comment by debiansid** [comment]
try dig @8.8.8.8

**Comment by tty7tyil** [comment]
> 
> 
> try dig @8.8.8.8

How do I config `dig` to send the request through local socks5 proxy?  Did not find the option, and env variable does not seems to have effect.

**Comment by debiansid** [comment]
I setup ss-redir on my router/Linux client, not sure about your setup.

**Comment by tty7tyil** [comment]
> 
> 
> I setup ss-redir on my router/Linux client, not sure about your setup.

Well, I found an indirect way to test udp forwarding using the android client.
Thx anyway.
