### ISSUE TITLE
Connecting to Caddy reverse proxy Failed

### ISSUE THREAD

**Issue by tefiszx** [shadowsocks/v2ray-plugin#105]
Hello everyone, I have a question to ask for v2ray-plugin connecting to Caddy reverse Proxy
same issue as [this](https://github.com/shadowsocks/v2ray-plugin/issues/30) 
@bigbighill  @VictoriaRaymond @madeye 
I have been confirmed normal connecting is all OK with v2ray-plugin.But If I use the caddy reverse proxy,the errors are happend .

The following is my configuration file for caddy and shadowsocks server

caddy config
#cat /etc/caddy/Caddyfile
```
http://www.mydomain,http://mydomain{
redir https://mydomain{url}
}
https://mydomain {
root /var/www/html
gzip
index index.html
tls mymail@gmail.com
proxy /ss localhost:1443 {
without /ss
websocket
header_upstream -Origin
  }
}
```

shadowsocks config
#cat /etc/shadowsocks-libev/config.json
```
{
    "server":"0.0.0.0",
    "server_port":1443,
    "password":"password",
    "timeout":300,
    "method":"aes-128-gcm",
    "fast_open":true,
    "plugin":"v2ray-plugin",
    "plugin_opts":"server;tls;cert=/.caddy/acme/acme-v02.api.letsencrypt.org/sites/mydomain/mydomain.crt;key=/.caddy/acme/acme-v02.api.letsencrypt.org/sites/mydomain/mydomain.key;host=mydomain;loglevel=none"

```
Below is the log
caddy LOG

> Jul 22 02:21:39 Proxyer caddy[13943]: 22/Jul/2019:02:21:39 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x
> Jul 22 02:21:39 Proxyer caddy[13943]: 22/Jul/2019:02:21:39 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x
> Jul 22 02:21:39 Proxyer caddy[13943]: 22/Jul/2019:02:21:39 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x
> Jul 22 02:21:40 Proxyer caddy[13943]: 22/Jul/2019:02:21:40 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x
> Jul 22 02:21:40 Proxyer caddy[13943]: 22/Jul/2019:02:21:40 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x
> Jul 22 02:21:40 Proxyer caddy[13943]: 22/Jul/2019:02:21:40 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x
> Jul 22 02:21:40 Proxyer caddy[13943]: 22/Jul/2019:02:21:40 +0000 [ERROR 502 /ss] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x

shadowsocks LOG

v# ss-server -c config.json
 

> 2019-07-22 01:52:27 INFO: using tcp fast open
>  2019-07-22 01:52:27 INFO: plugin "v2ray-plugin" enabled
>  2019-07-22 01:52:27 INFO: initializing ciphers... aes-128-gcm
>  2019-07-22 01:52:27 INFO: tcp server listening at 127.0.0.1:33423
>  2019-07-22 01:52:27 INFO: running from root user
> 2019/07/22 01:52:27 V2Ray 4.16 (Po) Custom
> 2019/07/22 01:52:27 A unified platform for anti-censorship.
> 2019/07/22 01:52:31 http: TLS handshake error from [::1]:33578: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:31 http: TLS handshake error from [::1]:33580: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:31 http: TLS handshake error from [::1]:33582: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:32 http: TLS handshake error from [::1]:33584: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:32 http: TLS handshake error from [::1]:33586: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:32 http: TLS handshake error from [::1]:33588: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:32 http: TLS handshake error from [::1]:33590: tls: first record does not look like a TLS handshake
> 2019/07/22 01:52:32 http: TLS handshake error from [::1]:33592: tls: first record does not look like a TLS handshake

**Comment by tefiszx** [comment]
Hi all,I just made some changes for my caddy config file,and the errors show diffrent
`http://www.mydomain,http://mydomain{
redir https://mydomain{url}
}
https://mydomain {
root /var/www/html
gzip
index index.html
tls mymail@gmail.com
**proxy /ss https://localhost:1443** {
without /ss
websocket
header_upstream -Origin
  }
}`

shadowsocks log

> 2019/07/22 06:03:37 http: TLS handshake error from [::1]:48240: remote error: tl s: bad certificate
2019/07/22 06:03:38 http: TLS handshake error from [::1]:48242: remote error: tl s: bad certificate
2019/07/22 06:03:38 http: TLS handshake error from [::1]:48244: remote error: tl s: bad certificate
2019/07/22 06:03:38 http: TLS handshake error from [::1]:48246: remote error: tl s: bad certificate
2019/07/22 06:03:38 http: TLS handshake error from [::1]:48248: remote error: tl s: bad certificate
2019/07/22 06:03:38 http: TLS handshake error from [::1]:48250: remote error: tl s: bad certificate
2019/07/22 06:03:38 http: TLS handshake error from [::1]:48252: remote error: tl s: bad certificate
2019/07/22 06:03:39 http: TLS handshake error from [::1]:48254: remote error: tl s: bad certificate
2019/07/22 06:03:39 http: TLS handshake error from [::1]:48256: remote error: tl s: bad certificate

**Comment by Acris** [comment]
Remove tls option in your v2ray-plugin configuration.

**Comment by tefiszx** [comment]
> Remove `tls` option in your v2ray-plugin configuration and use `http://localhost:1443` in your Caddyfile.

thanks a lot！It works after modified the Caddyfile according to your comments
