### ISSUE TITLE
cer证书申请失败

### ISSUE THREAD

**Issue by xzOxn** [shadowsocks/v2ray-plugin#107]
[Wed Jul 31 22:30:03 CST 2019] You didn't specify a Cloudflare api key and email yet.
[Wed Jul 31 22:30:03 CST 2019] You can get yours from here https://dash.cloudflare.com/profile.
[Wed Jul 31 22:30:03 CST 2019] Error add txt for domain:_acme-challenge.lt.hn.189.cn

楼主这个怎么解决

**Comment by Acris** [comment]
**You didn't specify a Cloudflare api key and email yet.**

https://github.com/Neilpang/acme.sh/wiki/dnsapi#1-use-cloudflare-domain-api-to-automatically-issue-cert
