### ISSUE TITLE
Not working behind CDN

### ISSUE THREAD

**Issue by busywandering** [shadowsocks/v2ray-plugin#112]
I’m using CloudFlare as the CDN. On the Windows client, in the Server Address field, if I input IP address of the original server, the configuration would work. If I input domain name, the connection would fail. Any idea what may have gone wrong?

**Comment by busywandering** [comment]
I’m using CloudFlare as the CDN. On the Windows client, in the Server Address field, if I input IP address of the original server, the configuration would work. If I input domain name, the connection would fail. Any idea what may have gone wrong?

**Comment by ikidou** [comment]
I use cloudflare too and it's works,did you set **host=youDomain**  options? or cloudflare provides tls support,so you should add **tls** flag in you options

**Comment by busywandering** [comment]
I found the cause of the issue. The SSL section under the Crypto tab was chosen as "Flexible". I changed it to "Full", and then it works.
