### ISSUE TITLE
可否添加 tls allowInsecure 选项，允许使用自签名证书？

### ISSUE THREAD

**Issue by lucaskeen** [shadowsocks/v2ray-plugin#114]
@madeye 请问大神可否添加 tls allowInsecure 选项，允许使用自签名证书？免去注册真实域名的步骤，反正只是开个代理服务器，也用不着域名。多谢！

**Comment by Mygod** [comment]
Use certificate option in client.

**Comment by better0332** [comment]
what ‘s mean certificate option?
