### ISSUE TITLE
exec: v2ray-plugin: Permission denied

### ISSUE THREAD

**Issue by 1ehsn** [shadowsocks/v2ray-plugin#116]
Hey. I've installed v2ray-plugin by just building it (`go build`) as the official repo suggests.
When I run Shadowsocks by `ss-server -c config.json` , I get this error:

> 2019-08-23 11:08:46 INFO: using tcp fast open
>  2019-08-23 11:08:46 INFO: plugin "v2ray-plugin" enabled
>  2019-08-23 11:08:46 INFO: enable TCP no-delay
>  2019-08-23 11:08:46 INFO: initializing ciphers... chacha20-ietf
>  2019-08-23 11:08:46 INFO: tcp server listening at 127.0.0.1:50469
>  2019-08-23 11:08:46 INFO: running from root user
> sh: 1: exec: v2ray-plugin: Permission denied
> 2019-08-23 11:16:31 ERROR: plugin service exit unexpectedly

This is my config file:

> {
>     "server":"0.0.0.0",
>     "server_port":80,
>     "password":"*******************",
>     "method":"chacha20-ietf",
>     "fast_open": true,
>     "no_delay": true,
>     "plugin":"v2ray-plugin",
>     "plugin_opts":"server"
> }

Any idea what the problem maybe?
Thanks

**Comment by whao** [comment]
同样的问题。 @ghost 解决了吗

**Comment by moghadas76** [comment]
I have same

**Comment by Gamoncol** [comment]
I've found the mistake that you do.
Here`s the link of the guide https://github.com/Knotoni/v2ray-install
you must follow all the steps, but don`t copy your files though an application. The OC doesn`t want to see copied files in itself. You need to create all files yourself, download the plugin and then write in the settings into the files. Then it will work.
I repeat - do not copy files, create them. The only file you can copy is the plugin. Others - creat and write the settings in. Then commads will work and you will spend only 5 min on it.
