### ISSUE TITLE
openwrt + ss-local + v2ray-plugin  not working

### ISSUE THREAD

**Issue by xcjiang** [shadowsocks/v2ray-plugin#118]
所用的版本如下：
openwrt 18.06
shadowsocks-libev  3.3.1
v2ray-plugin-linux-mips 1.1.0

v2ray的log里有如下的报错：

`[Info] failed to handler mux client connection > v2ray.com/core/proxy/freedom: failed to open connection to tcp:***:443 > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://***/):  > x509: certificate signed by unknown authority] > v2ray.com/core/common/retry: all retry attempts failed`

但证书应该是没有问题的，同一个的服务器用android可以顺利的连接。

**Comment by bingxuecandong** [comment]
一样的问题
我是小米路由3g，没刷机
v2ray-plugin-linux-mipsle 1.1.0
在ios和mac上使用v2ray-plugin是OK的

**Comment by lcdtyph** [comment]
服务器需要使用 fullchain 证书，不能只包含最后一级证书

**Comment by xcjiang** [comment]
应该是要安装ca-bundle这个包。
