### ISSUE TITLE
v2ray-plugin listens on TCP6 only

### ISSUE THREAD

**Issue by changyp6** [shadowsocks/v2ray-plugin#12]
Both version 20190114 and latest git version have this issue.
Run command:
`./v2ray-plugin_linux_amd64 -server -host itunes.apple.com -loglevel debug -localAddr 0.0.0.0 -localPort 12345 &`

Then run command:
```
sudo netstat -ltunp | grep v2ray
tcp6       0      0 :::12345                :::*                    LISTEN      15269/./v2ray-plugi
```

Enabling v2ray-plugin in shadowsocks has the same result, only listens on TCP6 port

If changing `-localAddr 0.0.0.0` to an actual IP address, v2ray-plugin listens on the correct IP protocol.

**Comment by linusyang** [comment]
This is golang's default mechanism, which binds to "::" even when specifying "0.0.0.0". Similar behavior can be seen in other golang-based apps, such as kcptun.

Essentially, listening on IPv6's address "::" is equivalent to "0.0.0.0" on POSIX-based systems (linux/macOS). It is backward compatible on such systems.

But I previously met weird issues with Windows 7 servers that only listens on IPv6 and ignores all connections from IPv4 addresses (correct me if wrong).

**Comment by changyp6** [comment]
> This is golang's default mechanism, which binds to "::" even when specifying "0.0.0.0". Similar behavior can be seen in other golang-based apps, such as kcptun.
> 
> Essentially, listening on IPv6's address "::" is equivalent to "0.0.0.0" on POSIX-based systems (linux/macOS). It is backward compatible on such systems.
> 
> But I previously met weird issues with Windows 7 servers that only listens on IPv6 and ignores all connections from IPv4 addresses (correct me if wrong).

I tested v2ray-plugin on CentOS 7 and Fedora 29, both system have this same behavior. It just ignores IPv4, only listens on IPv6.

I don't know if it is a bug of golang 1.11.4

**Comment by LiveChief** [comment]
Tested on UBUNTU and it's the same damn thing

**Comment by changyp6** [comment]
> If I remember correctly `sysctl.conf` should have an entry called `net.ipv6.conf.all.disable_ipv6`. I’m not sure if it’s relatable.
> 
> Anyway for broadcast IP addresses `0.0.0.0` is okay; otherwise you need to specify the IP address of the default interface returned by executing the following command
> 
> ```
> ifconfig | awk '/inet / { if ($2 != "127.0.0.1") print $2}'
> ```

I have set net.ipv6.conf.all.disable_ipv6 = 1
however, only IPv6 Address is listened to.

**Comment by PantherJohn** [comment]
@changyp6 I mean `net.ipv6.conf.all.disable_ipv6 = 0`

**Comment by changyp6** [comment]
@PantherJohn My sever's default setting is `net.ipv6.conf.all.disable_ipv6 = 0`
If I set "localAddr = 0.0.0.0", only IPv6 address is listened to

I have tested this on multiple platforms, CentOS, Fedora 29, Fedora 28, all have the same behavior.

My golang version is 1.11.4

**Comment by linusyang** [comment]
To be clear, this is not the issue of v2ray-plugin, but the golang runtime.

Or to say, it is **supposed** to listen on the `::` IPv6 address even if explicitly specifying the IPv4 any address `0.0.0.0`.

One related issue is golang/go#17615. The explanation can be found in [this commit][commit]:

> Listening on network "tcp" with host "0.0.0.0" or "[::]" may listen on both
> IPv4 and IPv6. To only use IPv4, use network "tcp4". To explicitly use both,
> listen on ":port" without a host.

[commit]: https://github.com/golang/go/commit/071908f3d809245eda42bf6eab071c323c67b7d2#diff-af10cab567dbd44651926d200c231fceR552

**Comment by changyp6** [comment]
@linusyang I agree with you that this should be GoLang Runtime issue.
The comment says that 0.0.0.0 may listen on both IPv4 and IPv6, however, when specifying 0.0.0.0, only IPv6 address is listened on, IPv4 is not.

**Comment by Mygod** [comment]
Despite `netstat` showing listening only on IPv6, the connection seems to work also with IPv4.

See also: https://unix.stackexchange.com/a/152618/145080
