### ISSUE TITLE
可否增加heroku支持？

### ISSUE THREAD

**Issue by unl89** [shadowsocks/v2ray-plugin#126]

**Comment by lcdtyph** [comment]
I think you should ask [mrluanma/shadowsocks-heroku](https://github.com/mrluanma/shadowsocks-heroku) to add support for this plugin.

**Comment by xianren78** [comment]
当然是OK的，heroku后台绑定域名后还可以加上Cloudflare。

**Comment by ygcaicn** [comment]
https://github.com/ygcaicn/ss-heroku
