### ISSUE TITLE
[Feature Request] Packaging for Snap?

### ISSUE THREAD

**Issue by R8s6** [shadowsocks/v2ray-plugin#131]
Hi,

There was a request for packaging v2ray-plugin into the debian repo for months without being processed,.

So I'm wondering if the devs could package it for Snap, just like shadowsocks-libev?

Thank you very much!

**Comment by xianren78** [comment]
`Alternatively, you can grab the latest nightly from Circle CI by logging into Circle CI or adding #artifacts at the end of URL like such: https://circleci.com/gh/shadowsocks/v2ray-plugin/20#artifacts`
Pls download nightly build from circleci.com.

**Comment by R8s6** [comment]
Thanks for the suggestion; however, the usage of shadowsocks and v2ray-plugin is a sensitive issue, because how can we trust that a 3rd-party binary has no government backdoor?

The only safe way is either downloading binary from the developers or compiling by ourselves.

To be fair, even the dev's binary is not entirely trustworthy because it's a binary which is hard to audit, but that's about the maximum risk I'm willing to take.

In addition, compiling the binary is trivial, and the only advantage of having the binary in a repo or snap is so we can update it easily.

**Comment by R8s6** [comment]
As I see it has entered debian/ubuntu, probably it's of little use for now.

Case closed.
