### ISSUE TITLE
Nginx+v2ray+Shadowsocks-libev not working

### ISSUE THREAD

**Issue by Qionglu735** [shadowsocks/v2ray-plugin#132]
I got a 404 in nginx/access.log

    "GET /ray HTTP/1.1" 404 152 "-" "Go-http-client/1.1"

seems nginx does not pass the request to v2ray.
but i can't find what's going wrong

these are my config file:
/etc/nginx/conf.d/MY_SS.conf

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name  MY_DOMAIN;
        root /usr/share/nginx/html/;
        ssl_certificate "MY_DOMAIN.cer";
        ssl_certificate_key "MY_DOMAIN.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        location /ray {
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_pass http://localhost:1984;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

/etc/shadowsocks-libev/config.json

    {
        "server": "localhost",
        "server_port": 30001,
        "password": "PASSWORD",
        "method": "xchacha20-ietf-poly1305",
        "timeout": 60,
        "mode": "tcp_only",
        "plugin": "/root/v2ray-plugin/v2ray-plugin",
        "plugin_opts": "server;path=/ray;loglevel=debug"
    } 

v2gray option on client

    tls;path=/ray;host=MY_DOMAIN

Any help ?

**Comment by devarped** [comment]
Server port in nginx and shadowsocks configs do not match.

**Comment by Qionglu735** [comment]
server port in nginx is the defalut port of v2ray-plugin

**Comment by onlyJinx** [comment]
老哥，你客户端使用手机的吗？配置完tls后网站是正常https了但是ss连接不上

**Comment by Qionglu735** [comment]
不是，我用pc

**Comment by onlyJinx** [comment]
> 不是，我用pc

你证书是放在默认路径/root/.acme.sh/下的吗？要不要转换证书成cer格式？

**Comment by Qionglu735** [comment]
> 你证书是放在默认路径/root/.acme.sh/下的吗？要不要转换证书成cer格式？

用acme生成时，就有cer和key了，不需要转

**Comment by onlyJinx** [comment]
> > 你证书是放在默认路径/root/.acme.sh/下的吗？要不要转换证书成cer格式？
> 
> 用acme生成时，就有cer和key了，不需要转

我用腾讯申请的证书，没有cer格式，现在各种报错，好烦
Sep 24 11:06:24 instance-2 ss-server[8900]: 2019/09/24 11:06:24 http: TLS handshake error from 127.0.0.1:32994: tls: first record does not look like a TLS handshake
Sep 24 11:06:24 instance-2 ss-server[8900]: 2019/09/24 11:06:24 http: TLS handshake error from 127.0.0.1:32998: tls: first record does not look like a TLS handshake
Sep 24 11:06:24 instance-2 ss-server[8900]: 2019/09/24 11:06:24 http: TLS handshake error from [::1]:44642: tls: first record does not look like a TLS handshake
Sep 24 11:06:24 instance-2 ss-server[8900]: 2019/09/24 11:06:24 http: TLS handshake error from 127.0.0.1:33002: tls: first record does not look like a TLS handshake
Sep 24 11:06:25 instance-2 ss-server[8900]: 2019/09/24 11:06:25 http: TLS handshake error from [::1]:44646: tls: first record does not look like a TLS handshake
Sep 24 11:06:25 instance-2 ss-server[8900]: 2019/09/24 11:06:25 http: TLS handshake error from 127.0.0.1:33006: tls: first record does not look like a TLS handshake
Sep 24 11:06:25 instance-2 ss-server[8900]: 2019/09/24 11:06:25 http: TLS handshake error from [::1]:44650: tls: first record does not look like a TLS handshake
Sep 24 11:06:25 instance-2 ss-server[8900]: 2019/09/24 11:06:25 http: TLS handshake error from 127.0.0.1:33010: tls: first record does not look like a TLS handshake
Sep 24 11:06:25 instance-2 ss-server[8900]: 2019/09/24 11:06:25 http: TLS handshake error from [::1]:44654: tls: first record does not look like a TLS handshake
Sep 24 11:06:25 instance-2 ss-server[8900]: 2019/09/24 11:06:25 http: TLS handshake error from 127.0.0.1:33014: tls: first record does not look like a TLS handshake

**Comment by rampageX** [comment]
proxy_pass http://localhost:**1984**; 
vs
"server_port": **30001**,

**Comment by onlyJinx** [comment]
> nginx 连接到 1984,
> proxy_pass http://localhost:1984;
> 
> ss-server 监听 30001 ?
> "server_port": **30001**,

详细描述在这里#133

**Comment by Qionglu735** [comment]
> 
> 
> nginx 连接到 1984,
> proxy_pass http://localhost:1984;
> 
> ss-server 监听 30001 ?
> "server_port": **30001**,

proxy_pass 到30001也是同样的错误
1984是v2ray-plugin的默认端口

**Comment by rampageX** [comment]
![2019-09-25_021836](https://user-images.githubusercontent.com/994081/65538911-f3a0a700-df3a-11e9-9ce2-4439f766e5a9.jpg)

你这里又是 location / 而不是 location /ray ，所以你不要把自己搞乱了，一步步来。

先随便丢个 html 文件去 / 下，用浏览器看看 https 访问是否正常，确认证书没问题，再搞反代。

正常情况客户端不需要设置任何证书，系统自带根证书。

还有你反复说 v2ray-plugin 默认端口，它没有什么默认端口，你在配置文件设置啥端口它就监听啥端口。

**Comment by Qionglu735** [comment]
> 
> 
> ![2019-09-25_021836](https://user-images.githubusercontent.com/994081/65538911-f3a0a700-df3a-11e9-9ce2-4439f766e5a9.jpg)
> 
> 你这里又是 location / 而不是 location /ray ，所以你不要把自己搞乱了，一步步来。
> 
> 先随便丢个 html 文件去 / 下，用浏览器看看 https 访问是否正常，确认证书没问题，再搞反代。
> 
> 正常情况客户端不需要设置任何证书，系统自带根证书。
> 
> 还有你反复说 v2ray-plugin 默认端口，它没有什么默认端口，你在配置文件设置啥端口它就监听啥端口。

这个截图不是我的配置，我的详细配置请看1楼

nginx上配置的其他url可以访问，已经验证过了

原先也是设置ss-libev的端口，发现不行，才改成1984

v2ray-plugin -h的说明里，写明了默认端口是1984

    -localPort string
        local port to listen on. (default "1984")

**Comment by onlyJinx** [comment]
> ![2019-09-25_021836](https://user-images.githubusercontent.com/994081/65538911-f3a0a700-df3a-11e9-9ce2-4439f766e5a9.jpg)
> 
> 你这里又是 location / 而不是 location /ray ，所以你不要把自己搞乱了，一步步来。
> 
> 先随便丢个 html 文件去 / 下，用浏览器看看 https 访问是否正常，确认证书没问题，再搞反代。
> 
> 正常情况客户端不需要设置任何证书，系统自带根证书。
> 
> 还有你反复说 v2ray-plugin 默认端口，它没有什么默认端口，你在配置文件设置啥端口它就监听啥端口。

哈哈，好像把你绕晕了，#133 是我的issue，不是楼主的，有空的话你也过去#133 帮我看看，谢谢～～

**Comment by Qionglu735** [comment]
Finally solve this problem

The SSL/TLS encryption mode in cdn should be set to Full, defalut is Flexible.

    Flexible SSL: You cannot configure HTTPS support on your origin, even with a certificate that is not valid for your site. Visitors will be able to access your site over HTTPS, but connections to your origin will be made over HTTP.
    Full SSL: Your origin supports HTTPS, but the certificate installed does not match your domain or is self-signed. Cloudflare will connect to your origin over HTTPS, but will not validate the certificate.
