### ISSUE TITLE
websocket (HTTPS) can't connect

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/v2ray-plugin#133]
Hello All,

我申请了证书文件，现在能正常部署到网站上，但是不能用shadowsocks去连接，证书是在腾讯申请的，他没有给我cer文件，我使用openssl把crt转换成cer;
openssl x509 -in yourcrt.crt -out yourcer.cer -outform der
转换后文件在安卓客户端是乱码的，无法使用，请问要怎么配置这个证书？
![Screenshot_20190924-103527_Shadowsocks](https://user-images.githubusercontent.com/21324835/65476932-2d2fce80-deb7-11e9-823a-7e947623fe39.jpg)
![SmartSelect_20190924-101849_Chrome Dev](https://user-images.githubusercontent.com/21324835/65476954-42a4f880-deb7-11e9-9d3f-ecd720c4a341.jpg)
![Screenshot_20190924-101340_JuiceSSH](https://user-images.githubusercontent.com/21324835/65476958-49337000-deb7-11e9-8d47-90cfda20265c.jpg)
![SmartSelect_20190924-101057_JuiceSSH](https://user-images.githubusercontent.com/21324835/65476963-4e90ba80-deb7-11e9-81ad-0916ce2f883c.jpg)
![SmartSelect_20190924-100847_JuiceSSH](https://user-images.githubusercontent.com/21324835/65476967-54869b80-deb7-11e9-9007-9d54ee675a13.jpg)

**Comment by onlyJinx** [comment]
I have updated the cert&key path in config file but still can't connect to server

![Screenshot_20190924-191424_JuiceSSH](https://user-images.githubusercontent.com/21324835/65507141-d4d0ef00-deff-11e9-84c5-92b50d7e5eca.jpg)

**Comment by loyess** [comment]
[试试一键安装](https://github.com/loyess/Shell)

**Comment by onlyJinx** [comment]
> [试试一键安装](https://github.com/loyess/Shell)

我试试，谢谢，不过还是喜欢自己一步一步安装，哈哈

**Comment by Mygod** [comment]
Use cer file instead.
