### ISSUE TITLE
系统重启后必须要把服务重启下才行

### ISSUE THREAD

**Issue by killgcd4ever** [shadowsocks/v2ray-plugin#137]
ss v2ray插件配nginx和cloudflare cdn 发现每次重启了vps之后连接都有问题，服务端报ERROR: unable to resolve xxx.com  此时重启ss服务之后就好了，请问为啥

**Comment by kaslr** [comment]
Try add a dns server in your configuration file, e.g.
```
    "nameserver": "8.8.8.8"
```

**Comment by killgcd4ever** [comment]
> Try add a dns server in your configuration file, e.g.
> 
> ```
>     "nameserver": "8.8.8.8"
> ```

It worked.Thank you very much.
btw,can ss-libev config support multiple nameserver, like this
"nameserver":["8.8.8.8",'8.8.4.4"]  I tried but ss start failed. Whether the configuration file has a syntax problem？Thanks!

**Comment by kaslr** [comment]
This key does not accept an array yet. I'll try to send a PR to support it when I'm available.

**Comment by killgcd4ever** [comment]
> ~This key does not accept an array yet. I'll try to send a PR to support it when I'm available.~
> 
> @killgcd4ever
> Sorry, there's no need for a PR. You can set multi dns servers with a comma separated string:
> 
> ```
>     "nameserver": "8.8.8.8,8.8.4.4"
> ```

Great, thank you very much
