### ISSUE TITLE
Android and tls certificates

### ISSUE THREAD

**Issue by br0metheus** [shadowsocks/v2ray-plugin#138]
What is the correct way to import a certifcate to the android client?

I have tried directly importing crt, cert, and pem certificates with the browse option in the app, but they cannot be selected. I've also tried manually entering the certificate various ways and formats, in the app, in a text editor to profile.json, with/without line breaks, -----BEGIN/END CERTIFICATE----- , == padding etc. The app accepts it but I cannot connect, I always get bad certificate errors on the server. It is a self-signed certificate. The same certificate works when used with my linux clients. Tried tls and quic modes, same result. With 1.1.0 on the server, I get no certificate warning, but still cannot connect from android. 

server config:

    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":443,
    "local_port":1080,
    "password":"password",
    "nameserver":"my dns server",
    "fast_open":true,
    "no_delay":true,
    "reuse_port":true,
    "timeout":600,
    "plugin":"/etc/shadowsocks-libev/v2ray-plugin",
    "plugin_opts":"server;tls;host=myhost.com;key=/etc/shadowsocks-libev/shadowsocks.key;  cert=/etc/shadowsocks-libev/shadowsocks.cert",
    "method":"chacha20-ietf-poly1305"

linux client config (works)

    "server":"server ip",
    "server_port":443,
    "local_port":1080,
    "mode":"tcp_and_udp",
    "password":"password",
    "nameserver":"my dns server",
    "fast_open":true,
    "no_delay":true,
    "reuse_port":true,
    "plugin":"v2ray-plugin",
    "plugin_opts":"quic;host=myhost.com;cert=/etc/shadowsocks-libev/shadowsocks.cert",
    "timeout":600,
    "method":"chacha20-ietf-poly1305"

![Screenshot_20191008-180956_Shadowsocks](https://user-images.githubusercontent.com/55767285/66439010-a0485180-ea2e-11e9-878e-f8a290c3c200.png)

![Screenshot_20191008-182656_Shadowsocks](https://user-images.githubusercontent.com/55767285/66439022-a807f600-ea2e-11e9-89b6-1054db0e147e.png)

![Screenshot_20191008-180921_v2ray](https://user-images.githubusercontent.com/55767285/66439033-adfdd700-ea2e-11e9-970e-5058544be276.png)

**Comment by enihcam** [comment]
bad certificate errors only happen on v1.2.0.
v1.1.0 works good.

**Comment by br0metheus** [comment]
Thanks. I tried 1.1.0, still can't connect although I'm not seeing certificate errors in server logs with this version

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vanyaindigo** [comment]
> I have tried directly importing crt, cert, and pem certificates with the browse option in the app, but they cannot be selected

You just need to copy/paste Certificate data, it may be .crt or .pem whatever
![Android3](https://user-images.githubusercontent.com/34334385/69026061-6d548e80-09da-11ea-80f0-8bcd79f1c23e.png)

**Comment by vanyaindigo** [comment]
No need to import it to Android while you use Cloudflare CDN
