### ISSUE TITLE
v1.2.0 detected and quarantined as a virus by Windows Defender after a restart

### ISSUE THREAD

**Issue by Nukme** [shadowsocks/v2ray-plugin#139]
Product Name %%827 
  Product Version 4.18.1909.6 
  Detection ID {0BD686D5-6D19-4A8E-80F2-629C1C5F6AA6} 
  Detection Time 2019-10-09T21:23:40.303Z 
  Unused  
  Unused2  
  Threat ID 2147722906 
  Threat Name Trojan:Win32/Ludicrouz.Z 
  Severity ID 5 
  Severity Name Severe 
  Category ID 8 
  Category Name Trojan 
  FWLink https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Ludicrouz.Z&threatid=2147722906&enterprise=0 
  Status Code 1 
  Status Description  
  State 1 
  Source ID 3 
  Source Name %%818 
  Process Name C:\Tools\Shadowsocks\Shadowsocks.exe 
  Detection User  
  Unused3  
  Path file:_C:\Tools\Shadowsocks\v2ray-plugin_windows_amd64.exe 
  Origin ID 1 
  Origin Name %%845 
  Execution ID 1 
  Execution Name %%813 
  Type ID 8 
  Type Name %%862 
  Pre Execution Status 0 
  Action ID 9 
  Action Name %%887 
  Unused4  
  Error Code 0x00000000 
  Error Description The operation completed successfully.  
  Unused5  
  Post Clean Status 0 
  Additional Actions ID 0 
  Additional Actions String No additional actions required 
  Remediation User  
  Unused6  
  Security intelligence Version AV: 1.303.1200.0, AS: 1.303.1200.0, NIS: 1.303.1200.0 
  Engine Version AM: 1.1.16400.2, NIS: 1.1.16400.2

**Comment by jgh004** [comment]
同样被检测出木马
