### ISSUE TITLE
ss-local + v2ray-plugin errror: failed to start server: v2ray.com/core/app/proxyman/inbound

### ISSUE THREAD

**Issue by wrcno1** [shadowsocks/v2ray-plugin#140]
failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 8530 > v2ray.com/core/transport/internet: failed to listen on address: <ip>:<port> > v2ray.com/core/transport/internet/websocket: failed to listen TCP on <ip>:<port> > listen tcp  <ip>:<port>: bind: cannot assign requested address

**Comment by kaslr** [comment]
What's your plugin-opts ?

**Comment by wrcno1** [comment]
> What's your plugin-opts ?

Thanks for your hits. I've just checked my plugin-opts and found out that I misused service side config: "plugin-opts":"server; xxx". After I changed the plugin-opts, everything works fine.

**Comment by wrcno1** [comment]
Thanks a lot! @kaslr
