### ISSUE TITLE
使用 Nginx / Caddy 反代后，如何设置 UDP 转发？

### ISSUE THREAD

**Issue by nbieyn** [shadowsocks/v2ray-plugin#141]
正常配置 SS+WebSocket+TLS 可以打开并使用 UDP 转发。
而通过 Nginx / Caddy 反代后，UDP 转发不能用，有什么解决方法？
````
{
    "server":"127.0.0.1",
    "server_port":9999,
    ...
    "plugin":"v2ray-plugin",
    "plugin_opts":"server;path=/sspath"
}
````
````
#Caddy 设置
example.com {
    proxy /sspath localhost:9999 {
        websocket
        header_upstream -Origin
    }
}
````

Vmess 通过反代后，UDP 转发是能用的。
VMess 是基于 TCP 的协议，对于 UDP 包 V2Ray 会转成 TCP 再传输的。[[1]](https://guide.v2fly.org/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%EF%BC%9Aq-a)
但 SS 不是这样的。

**Comment by nbieyn** [comment]
发现 443/UDP 端口空着，复制了一份 SS 配置，改成
```
{
    "server":"0.0.0.0",
    "server_port":443,
    "mode":"udp_only",
    ...
}
```
与不用 Nginx/Caddy 效果一样。但是应该用不了 QUIC 了。

**Comment by tty7tyil** [comment]
我现在在尝试让 nginx 像反代 http 一样反代 udp 到 ss 的监听端口上，这样应该能正常使用 ss 的 udp 转发功能，但肯定也是不能套 cdn，毕竟人家不转发你的 udp。
但是现在卡在 nginx udp 转发上，stream 模块死活加载不上……

ps：搜了好久都没搜到你这个 issue，因为你只提了「转发」没提「forwarding」😂。

**Comment by odesky** [comment]
请问大神有解决方法吗?

**Comment by tty7tyil** [comment]
> 
> 
> 请问大神有解决方法吗?

请自行阅读本 issue，写得很清楚了。
