### ISSUE TITLE
很高的内存占用

### ISSUE THREAD

**Issue by shindo10** [shadowsocks/v2ray-plugin#143]
机器是网件4300
openwrt 18.06.04
ss 3.3.2
v2ray-plugin 1.2.0
启用插件后，负载一度超过3，VSZ 一直655m
正常使用但就是很慢，不超过5Mb/秒
![image](https://user-images.githubusercontent.com/6128526/67173798-6bef7080-f3f2-11e9-8846-3c8481f72897.png)

**Comment by Mygod** [comment]
Report to v2ray instead.
