### ISSUE TITLE
v2ray-plugin套clouflare的CDN正常，其他的不正常

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/v2ray-plugin#145]
v2ray-plugin的tls模式，套clouflare正常。但是其他的都不行。请问需要CDN支持什么才可以？难道支持https还不行吗？

**Comment by liujunhui74** [comment]
Websocket. Not all CDN support it.

**Comment by zhangjint5** [comment]
> v2ray-plugin的tls模式，套clouflare正常。但是其他的都不行。请问需要CDN支持什么才可以？难道支持https还不行吗？

不行！需要CDN支持 WebSocket ，目前知道的就 ClouFlare 支持 WebSocket 。
