### ISSUE TITLE
Raspberry Pi Model B Rev 2 下无法运行，求解？

### ISSUE THREAD

**Issue by hzqim** [shadowsocks/v2ray-plugin#146]
自编译的 OpenWRT 18.06.04 ，顺利编译出 v2ray-plugin
但运行v2ray-plugin的时候提示非法指令，这是CPU不支持吗？

> 
系统信息如下：
主机名	OpenWrt
主机型号	Raspberry Pi Model B Rev 2
架构	ARMv6-compatible processor rev 7 (v6l)
固件版本	OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc)
内核版本	4.9.184
本地时间	Thu Jun 27 20:44:58 2019
运行时间	0h 23m 37s
平均负载	1.46, 0.93, 0.41
>

**Comment by Biercenter** [comment]
你好，请问是怎么编译的？固件也是自编译的，但是是ARMv8 Processor rev 4 (v8l)
