### ISSUE TITLE
Update v2ray dependency to 4.21.3+

### ISSUE THREAD

**Issue by lixin9311** [shadowsocks/v2ray-plugin#148]
4.21.3 fixed self-signed cert issue on Windows.

https://github.com/v2ray/v2ray-core/releases/tag/v4.21.3

**Comment by enihcam** [comment]
the update would also resolve https://github.com/shadowsocks/v2ray-plugin/issues/125

**Comment by enihcam** [comment]
https://github.com/teddysun/v2ray-plugin
