### ISSUE TITLE
Use v2ray-plugin after Nginx have status 400

### ISSUE THREAD

**Issue by gu18168** [shadowsocks/v2ray-plugin#150]
Nginx log have the `"GET /ray HTTP/1.1" 400 59 "-" "Go-http-client/1.1"` , I have a cloudflare CDN, too

My Nginx https config is:
```
server {
    listen       443 ssl http2;
    listen [::]:443 ssl http2;
    server_name  mydomain;

    ssl_certificate      /root/.acme.sh/mydomain.cer;
    ssl_certificate_key  /root/.acme.sh/mydomain.key;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_protocols SSLv2 SSLv3 TLSv1;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location /ray {
        proxy_redirect off;
        proxy_pass   http://127.0.0.1:23333;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }
}
```

and my shadowsocks server config:
```
-s 0.0.0.0 -p 23333 -m chacha20-ietf-poly1305 -k password --plugin v2ray-plugin --plugin-opts=server;tls;host=mydomain;path=/ray;cert=/root/.acme.sh/mydomain.cer;key=/root/.acme.sh/mydomain.key
```

**Comment by liujunhui74** [comment]
Nginx has already terminated TLS. Traffic between nginx and ss is plain text. Disable TLS in your ss.
And you'd better listen 127.0.0.1 instead of 0.0.0.0.

**Comment by gu18168** [comment]
@liujunhui74 thank you for your response, when I disable TLS in my ss, now have a new problem, the status turned to be 502, and I saw the error log like below:
```
recv() failed (104: Connection reset by peer) while reading response header from upstream
```

**Comment by liujunhui74** [comment]
> @liujunhui74 thank you for your response, when I disable TLS in my ss, now have a new problem, the status turned to be 502, and I saw the error log like below:
> 
> ```
> recv() failed (104: Connection reset by peer) while reading response header from upstream
> ```

It seems your ss is not running or is not listening on the desired port. Try netstat -ltnp to find out.

**Comment by gu18168** [comment]
@liujunhui74 I use ss in docker, and I use the command, the result is below:
```
tcp6       0      0 :::23333                :::*                    LISTEN      23586/docker-proxy
```

**Comment by Relers** [comment]
> Nginx has already terminated TLS. Traffic between nginx and ss is plain text. Disable TLS in your ss. And you'd better listen on 127.0.0.1 instead of 0.0.0.0.
Wasted 3 hours to solve the problem. You are right. If you are using ss behind nginx, remove tls;cert;key options from plugin-opts.
