### ISSUE TITLE
TLS+WS速度瓶颈在openwrt上异常

### ISSUE THREAD

**Issue by moralrebuild** [shadowsocks/v2ray-plugin#152]
本人是在openwrt 18.06.4上通过 https://github.com/chenhw2/openwrt-v2ray-plugin 编译的：
```
v2ray-plugin 1.2.0-20191007
```
但使用时发现播放youtube视频时（VPS服务器在台湾）新3路由器(MIPS 800MHz)竟然和网件R7800 (Qualcomm ARM 1.7GHz)没有显著差距，这与大众对两种SoC巨大性能差距印象不符。请大家会会诊：

MT300N	ss w/ v2ray (ws+tls)(chacha20-ietf-poly1305) ： 5mbps
Newifi 3    ss w/ v2ray (ws+tls)(chacha20-ietf-poly1305)：  11mbps
R7800       ss w/ v2ray (ws+tls)(chacha20-ietf-poly1305) :   15mbps
NUC desktop ss w/ v2ray (ws+tls)(chacha20-ietf-poly1305) :    50mbps

**Comment by xqdoo00o** [comment]
ss-libev 加密库是mbedtls吧，这个库性能 不是很好。可以换成[go版本的ss](https://github.com/shadowsocks/go-shadowsocks2) 再试试

**Comment by rampageX** [comment]
ss 一层，tls 一层，路由器跑起来不会快到哪去，NUC 用的 intel 处理器把，带 aes 硬件加速自然轻松很多。

**Comment by rampageX** [comment]
@xqdoo00o BTW: 实际测试 go-shadowsocks2 比 shadowsocks-libev 慢：

ASUS RT-AC68P shadowsocks-libev:

> iperf_ss 500M chacha20-ietf-poly1305

> Server listening on TCP port 8388
> TCP window size: 85.3 KByte (default)

>  2019-12-02 11:59:51 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-12-02 11:59:51 INFO: listening at 127.0.0.1:8387
>  2019-12-02 11:59:51 INFO: running from root user
>  2019-12-02 11:59:51 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-12-02 11:59:51 INFO: tcp server listening at 127.0.0.1:8389
>  2019-12-02 11:59:51 INFO: running from root user

> Client connecting to 127.0.0.1, TCP port 8387
> TCP window size:  773 KByte (default)

> [  3] local 127.0.0.1 port 56130 connected with 127.0.0.1 port 8387
> [  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 41872
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-28.3 sec   500 MBytes   148 Mbits/sec
> [ ID] Interval       Transfer     Bandwidth
> [  4]  0.0-28.5 sec   500 MBytes   147 Mbits/sec
> Test Finished

ASUS RT-AC68P go-shadowsocks2:

> iperf_ssgo 500M AEAD_CHACHA20_POLY1305

> Server listening on TCP port 8388
> TCP window size: 85.3 KByte (default)

> Client connecting to 127.0.0.1, TCP port 8387
> TCP window size:  193 KByte (default)

> [  3] local 127.0.0.1 port 44229 connected with 127.0.0.1 port 8387
> [  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 22732
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-53.9 sec   500 MBytes  77.9 Mbits/sec
> [ ID] Interval       Transfer     Bandwidth
> [  4]  0.0-54.1 sec   500 MBytes  77.5 Mbits/sec
> Test Finished

PHICOMM-N1 shadowsocks-libev:

> iperf_ss 500M chacha20-ietf-poly1305

> Server listening on TCP port 8388
> TCP window size: 85.3 KByte (default)

>  2019-12-02 12:08:31 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-12-02 12:08:31 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-12-02 12:08:31 INFO: listening at 127.0.0.1:8387
>  2019-12-02 12:08:31 INFO: running from root user
>  2019-12-02 12:08:31 INFO: tcp server listening at 127.0.0.1:8389
>  2019-12-02 12:08:31 INFO: running from root user

> Client connecting to 127.0.0.1, TCP port 8387
> TCP window size: 3.76 MByte (default)

> [  3] local 127.0.0.1 port 15368 connected with 127.0.0.1 port 8387
> [  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 15444
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-11.9 sec   500 MBytes   353 Mbits/sec
> [ ID] Interval       Transfer     Bandwidth
> [  4]  0.0-12.4 sec   500 MBytes   339 Mbits/sec
> Test Finished

PHICOMM-N1 go-shadowsocks2:

iperf_ssgo 500M AEAD_CHACHA20_POLY1305

> Server listening on TCP port 8388
> TCP window size: 85.3 KByte (default)

> Client connecting to 127.0.0.1, TCP port 8387
> TCP window size: 3.76 MByte (default)

> [  3] local 127.0.0.1 port 14930 connected with 127.0.0.1 port 8387
> [  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 15006
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-15.3 sec   500 MBytes   274 Mbits/sec
> [ ID] Interval       Transfer     Bandwidth
> [  4]  0.0-15.6 sec   500 MBytes   270 Mbits/sec
> Test Finished

**Comment by xqdoo00o** [comment]
因为ARM v8之后的架构都有AES-NI了

**Comment by Mygod** [comment]
You can set up a separate ss-local on a faster CPU and route traffic through that.
