### ISSUE TITLE
非常奇怪的情形

### ISSUE THREAD

**Issue by fruitlee** [shadowsocks/v2ray-plugin#153]
突然发现不能用，经过多次测试，发现如下很奇怪的事情：
配置：
服务端用nginx，http和https都有配置，指向ss-server+v2ray-plugin [http on local addr]
情形：
1、客户端tls模式，直接使用VPS的IP，数据只有出站没有入站，工作不正常
2、客户端tls模式，使用域名+CDN，工作正常
3、客户端http模式，直接使用VPS的IP，工作正常
4、客户端http模式，使用域名+CDN，工作正常
5、浏览器http://ip/path访问得到预期响应
6、浏览器https://ip/path访问得到预期响应
7、浏览器http://domain(CDN)/path访问得到预期响应
8、浏览器https://domain(CDN)/path访问得到预期响应
综上，plugin只要是以tls模式直接连接IP，就不能工作。然而为何浏览器在所有情况下的响应却是正常的？1的情形正常使用了很长时间，突然就不能正常工作了

**Comment by fruitlee** [comment]
the reason I can think of is the feature...

**Comment by xqdoo00o** [comment]
因为免费的lets encrypt的证书只是针对域名的，ip ssl证书也有，但是要花钱的

**Comment by Mygod** [comment]
There's no support for HTTP nor nginx/any webserver.
