### ISSUE TITLE
v2ray-plugin always report a syntax error

### ISSUE THREAD

**Issue by sunduda** [shadowsocks/v2ray-plugin#154]
### Description

When I trying to start shadowsocks-libev server on a Debian Buster server,  a syntax error always occurs:
`/usr/bin/v2ray-plugin: 2: /usr/bin/v2ray-plugin: Syntax error: Unterminated quoted string`
### Steps to reproduce:
```
$ sudo apt install -y shadowsocks-libev socat netcat
$ mkdir -p ~/Downloads/v2ray-plugin
$ cd ~/Downloads/v2ray-plugin
$ curl -s https://api.github.com/repos/shadowsocks/v2ray-plugin/releases/latest \
$ | grep "browser_download_url.*tar.gz" \
$ | grep "linux-amd64" \
$ | cut -d '"' -f 4 \
$ | wget -qi - -O v2ray-plugin --show-progress
$ sudo cp ~/Downloads/v2ray-plugin/v2ray-plugin /usr/bin/v2ray-plugin
```
### Server-side configuration:
```
{
  "...": "...",
  "fast-open":true,
  "plugin": "v2ray-plugin",
  "plugin_opts": "server;tls;fast-open;host=mydomain.me;cert=/etc/shadowsocks-libev/mydomain.me/fullchain.cer;key=/etc/shadowsocks-libev/mydomain.me/mydomain.me.key;loglevel=none"
}
```
### ss-server log:
```
INFO: using tcp fast open
INFO: plugin "/usr/bin/v2ray-plugin" enabled
INFO: UDP relay enabled
INFO: enable TCP no-delay
INFO: initializing ciphers... aes-256-gcm
INFO: using nameserver: 8.8.8.8
INFO: tcp server listening at 127.0.0.1:43355
INFO: tcp port reuse enabled
INFO: udp server listening at x.x.x.x:443
INFO: udp port reuse enabled
/usr/bin/v2ray-plugin: 2: /usr/bin/v2ray-plugin: Syntax error: Unterminated quoted string
ERROR: plugin service exit unexpectedly
```
Please help me figure out this issue, thanks a lot.

**Comment by liujunhui74** [comment]
Is your v2ray-plugin executable? Didn't see chmod +x in your scripts.

**Comment by sunduda** [comment]
> 
> 
> Is your v2ray-plugin executable? Didn't see chmod +x in your scripts.

Thanks, but it's not the reason. I executed the script below, but the error still occurs.
`sudo chmod a+x /usr/bin/v2ray-plugin`

**Comment by kaslr** [comment]
It seems you didn't extract the tarball you've downloaded.

**Comment by sunduda** [comment]
> 
> 
> It seems you didn't extract the tarball you've downloaded.

OMG, I'm such an idiot. Thanks I'll try agian.

**Comment by sunduda** [comment]
> 
> 
> It seems you didn't extract the tarball you've downloaded.

Thank you so much. Problem solved.
