### ISSUE TITLE
Unable to start server with Quic

### ISSUE THREAD

**Issue by vanyaindigo** [shadowsocks/v2ray-plugin#156]
When using --plugin-opts "server;mode=quic;host=mydomain.me" server always fall back with 
`failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 443 > v2ray.com/core/transport/internet: failed to listen on address: server_ip:443 > listen udp server_ip:443: bind: address already in use`

**Comment by zhangjint5** [comment]
must be set   "mode": "tcp_only"
Cannot use    "mode": "tcp_and_udp"

Because QUIC listens to UDP port, if SS listens to UDP, it will cause port conflict!

**Comment by vanyaindigo** [comment]
Does it faster websocket-tls?

**Comment by zhangjint5** [comment]
> websocket-tls是否更快？

Look at the network, I open two servers, both at the same time!

a TCP, a UDP, may have different ISP optimizations / restrictions on it, and the differences are also different.
