### ISSUE TITLE
How can I know my CPU is arm64 or amd64 or mips

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/v2ray-plugin#158]
How can I know my CPU is arm64 or amd64 or mips

**Comment by lssmoon2019** [comment]
I want to download the releases

**Comment by vanyaindigo** [comment]
`lscpu`

**Comment by 369329303** [comment]
I searched it on google, and brought me to this stackoverflow page.
https://unix.stackexchange.com/questions/180726/easy-command-line-method-to-determine-specific-arm-architecture-string
```bash
$ dpkg --print-architecture
```

**Comment by waymao** [comment]
`uname -a`
See if you can find "amd64", "arm64" etc. For most personal computers, the arch will be "amd64".
