### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by LiveChief** [shadowsocks/v2ray-plugin#16]
```
root@perosnal-shadowsocks-compute:/etc/shadowsocks-libev/v2ray-plugin# ss-server -s 0.0.0.0 -p 443 -k password -m aes-256-gcm --plugin v2ray-plugin --plugin-opts "server;tls"
 2019-01-18 17:29:58 INFO: plugin "v2ray-plugin" enabled
 2019-01-18 17:29:58 INFO: initializing ciphers... aes-256-gcm
 2019-01-18 17:29:58 INFO: tcp server listening at 127.0.0.1:35769
 2019-01-18 17:29:58 INFO: running from root user
2019/01/18 17:29:58 V2Ray 4.13 (Po) Custom
2019/01/18 17:29:58 A unified platform for anti-censorship.
2019/01/18 17:29:58 No TLS cert specified, trying /root/.acme.sh/cloudfront.com/fullchain.cer
2019/01/18 17:29:58 main: failed to parse config > main: failed to read cert > open /root/.acme.sh/cloudfront.com/fullchain.cer: no such file or directory
 2019-01-18 17:29:58 ERROR: plugin service exit unexpectedly
root@perosnal-shadowsocks-compute:/etc/shadowsocks-libev/v2ray-plugin# 
```

can we add a option to specify the fullchain.pem somewhere...

```
root@perosnal-shadowsocks-compute:/etc/shadowsocks-libev/v2ray-plugin# ss-server -s 0.0.0.0 -p 443 -k password -m aes-256-gcm --plugin v2ray-plugin --plugin-opts:cert=/etc/letsencrypt/live/example.com/fullchain.pem
 2019-01-18 17:33:26 ERROR: Unrecognized option: (null)

shadowsocks-libev 3.1.3

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-server

       -s <server_host>           Host name or IP address of your remote server.
       -p <server_port>           Port number of your remote server.
       -l <local_port>            Port number of your local server.
       -k <password>              Password of your remote server.
       -m <encrypt_method>        Encrypt method: rc4-md5, 
                                  aes-128-gcm, aes-192-gcm, aes-256-gcm,
                                  aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                  aes-128-ctr, aes-192-ctr, aes-256-ctr,
                                  camellia-128-cfb, camellia-192-cfb,
                                  camellia-256-cfb, bf-cfb,
                                  chacha20-ietf-poly1305,
                                  xchacha20-ietf-poly1305,
                                  salsa20, chacha20 and chacha20-ietf.
                                  The default cipher is rc4-md5.

       [-a <user>]                Run as another user.
       [-f <pid_file>]            The file path to store pid.
       [-t <timeout>]             Socket timeout in seconds.
       [-c <config_file>]         The path to config file.
       [-n <number>]              Max number of open files.
       [-i <interface>]           Network interface to bind.
       [-b <local_address>]       Local address to bind.

       [-u]                       Enable UDP relay.
       [-U]                       Enable UDP relay and disable TCP relay.
       [-6]                       Resovle hostname to IPv6 address first.

       [-d <addr>]                Name servers for internal DNS resolver.
       [--reuse-port]             Enable port reuse.
       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--acl <acl_file>]         Path to ACL (Access Control List).
       [--manager-address <addr>] UNIX domain socket address.
       [--mtu <MTU>]              MTU of your network interface.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.
       [--no-delay]               Enable TCP_NODELAY.
       [--key <key_in_base64>]    Key of your remote server.
       [--plugin <name>]          Enable SIP003 plugin. (Experimental)
       [--plugin-opts <options>]  Set SIP003 plugin options. (Experimental)

       [-v]                       Verbose mode.
       [-h, --help]    
          Print this message.

root@perosnal-shadowsocks-compute:/etc/shadowsocks-libev/v2ray-plugin# 
```

**Comment by Love4Taylor** [comment]
```
➜  ~ v2ray-plugin --help
Usage of v2ray-plugin:
  -V    Run in VPN mode.
  -cert string
        Path to TLS certificate file. Overrides certRaw. Default: ~/.acme.sh/{host}/fullchain.cer
  -certRaw string
        Raw TLS certificate content. Intended only for Android.
  -fast-open
        Enable TCP fast open.
  -host string
        Hostname for server. (default "cloudfront.com")
  -key string
        (server) Path to TLS key file. Default: ~/.acme.sh/{host}/{host}.key
  -localAddr string
        local address to listen on. (default "127.0.0.1")
  -localPort string
        local port to listen on. (default "1984")
  -loglevel string
        loglevel for v2ray: debug, info, warning (default), error, none.
  -mode string
        Transport mode: websocket, quic (enforced tls). (default "websocket")
  -mux int
        Concurrent multiplexed connections (websocket client mode only). (default 1)
  -path string
        URL path for websocket. (default "/")
  -remoteAddr string
        remote address to forward. (default "127.0.0.1")
  -remotePort string
        remote port to forward. (default "1080")
  -server
        Run in server mode
  -tls
        Enable TLS.
```

```
➜  ~ ss-server -c demo.json -p 443 --plugin v2ray-plugin --plugin-opts "server;tls;host=your.domain;cert=/home/user/.acme.sh/your.domain_ecc/fullchain.cer;key=/home/user/.acme.sh/your.domain_ecc/your.domain.key"
 2019-01-19 15:08:28 INFO: plugin "v2ray-plugin" enabled
 2019-01-19 15:08:28 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-01-19 15:08:28 INFO: tcp server listening at 127.0.0.1:48559
2019/01/19 15:08:28 V2Ray 4.13 (Po) Custom
2019/01/19 15:08:28 A unified platform for anti-censorship.
2019/01/19 15:08:28 [Warning] v2ray.com/core: V2Ray 4.13 started
```

**Comment by timorpic** [comment]
```
{
    "server": "0.0.0.0",
    "server_port": 443, 
    "password": "Admin", 
    "method": "chacha20-ietf-poly1305", 
    "timeout": 3600, 
    "fast_open": true, 
    "reuse_port": true, 
    "no_delay": true, 
    "plugin": "/home/v2ray-plugin_linux_amd64", 
    "plugin_opts": "server;tls;host=***.***;cert=/home/V2ray.crt;key=/home/V2ray.key;fast-open;loglevel=info;certRaw", 
    "ipv6_first": true, 
    "mode": "tcp_and_udp"
}

```


### Android can't connect

> ```
> ➜  ~ v2ray-plugin --help
> Usage of v2ray-plugin:
>   -V    Run in VPN mode.
>   -cert string
>         Path to TLS certificate file. Overrides certRaw. Default: ~/.acme.sh/{host}/fullchain.cer
>   -certRaw string
>         Raw TLS certificate content. Intended only for Android.
>   -fast-open
>         Enable TCP fast open.
>   -host string
>         Hostname for server. (default "cloudfront.com")
>   -key string
>         (server) Path to TLS key file. Default: ~/.acme.sh/{host}/{host}.key
>   -localAddr string
>         local address to listen on. (default "127.0.0.1")
>   -localPort string
>         local port to listen on. (default "1984")
>   -loglevel string
>         loglevel for v2ray: debug, info, warning (default), error, none.
>   -mode string
>         Transport mode: websocket, quic (enforced tls). (default "websocket")
>   -mux int
>         Concurrent multiplexed connections (websocket client mode only). (default 1)
>   -path string
>         URL path for websocket. (default "/")
>   -remoteAddr string
>         remote address to forward. (default "127.0.0.1")
>   -remotePort string
>         remote port to forward. (default "1080")
>   -server
>         Run in server mode
>   -tls
>         Enable TLS.
> ```
> ```
> ➜  ~ ss-server -c demo.json -p 443 --plugin v2ray-plugin --plugin-opts "server;tls;host=your.domain;cert=/home/user/.acme.sh/your.domain_ecc/fullchain.cer;key=/home/user/.acme.sh/your.domain_ecc/your.domain.key"
>  2019-01-19 15:08:28 INFO: plugin "v2ray-plugin" enabled
>  2019-01-19 15:08:28 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-01-19 15:08:28 INFO: tcp server listening at 127.0.0.1:48559
> 2019/01/19 15:08:28 V2Ray 4.13 (Po) Custom
> 2019/01/19 15:08:28 A unified platform for anti-censorship.
> 2019/01/19 15:08:28 [Warning] v2ray.com/core: V2Ray 4.13 started
> ```

**Comment by Love4Taylor** [comment]
@timorpic Why do you use certRaw on the server side?

**Comment by timorpic** [comment]
> @timorpic Why do you use certRaw on the server side?

Do try
Remove certRaw and still can't connect

**Comment by JLbeard** [comment]
> > @timorpic Why do you use certRaw on the server side?
> 
> Do try
> Remove certRaw and still can't connect

安卓客户端host要相同

**Comment by timorpic** [comment]
> @timorpic 除非你是自签或者根证书不被系统信任 否则不需要填这项

申请的一年免费的证书
[FreeSSL.org](url)

**Comment by timorpic** [comment]
> > @timorpic 除非你是自签或者根证书不被系统信任 否则不需要填这项
> 
> 申请的一年免费的证书
> [FreeSSL.org](url)
> Windows10 没问题 一切正常 手机端就是连不上

问题找到了  就是这个[FreeSSL.org](url)证书不信任

**Comment by bigbighill** [comment]
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019-01-19 21:06:20 INFO: tcp server listening at 127.0.0.1:43517
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019-01-19 21:06:20 INFO: udp server listening at 0.0.0.0:443
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019/01/19 21:06:20 V2Ray 4.13 (Po) Custom
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019/01/19 21:06:20 A unified platform for anti-censorship.
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019/01/19 21:06:20 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 43517 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:43517 > listen tcp 127.0.0.1:43517: bind: address already in use
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019-01-19 21:06:20 ERROR: plugin service exit unexpectedly
1月 19 21:06:20 host.localdomain ss-server[4271]: 2019-01-19 21:06:20 INFO: closed gracefully
1月 19 21:06:20 host.localdomain systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=255/n/a1月 19 21:06:20 host.localdomain systemd[1]: Unit shadowsocks-libev.service entered failed state.
1月 19 21:06:20 host.localdomain systemd[1]: shadowsocks-libev.service failed.

**Comment by xqdoo00o** [comment]
我的证书 一般是用 https://github.com/Neilpang/acme.sh 生成的

**Comment by LiveChief** [comment]
Anyone with any updated configs or anything for the community??

**Comment by malikshi** [comment]
![screenshot_695](https://user-images.githubusercontent.com/9080737/52227182-6cd28780-28e1-11e9-8256-86fc40aa46d4.png)
did am i wrong? 
this is in client config
![screenshot_696](https://user-images.githubusercontent.com/9080737/52227254-94295480-28e1-11e9-9738-b6857e7d4d7e.png)
by using 
➜  ~ ss-server -c demo.json -p 443 --plugin v2ray-plugin --plugin-opts "server;tls;host=your.domain;cert=/home/user/.acme.sh/your.domain_ecc/fullchain.cer;key=/home/user/.acme.sh/your.domain_ecc/your.domain.key"

before i try Shadowsocks over websocket (HTTPS) am i already tried Shadowsocks over websocket (HTTP) and work but why use HTTPS not working? wrong config client?
