### ISSUE TITLE
eSNI

### ISSUE THREAD

**Issue by vanyaindigo** [shadowsocks/v2ray-plugin#161]
It would be nice to implement eSNI support with fake host.

**Comment by vanyaindigo** [comment]
You can use this

**Comment by dimqua** [comment]
@vanyaindigo to my knowledge, Cloudflare is no longer supports domain-fronting.

**Comment by vanyaindigo** [comment]
> 
> 
> @vanyaindigo to my knowledge, Cloudflare is no longer supports domain-fronting.

No it's not true

**Comment by Mygod** [comment]
Report to v2ray instead.
