### ISSUE TITLE
Can v2ray-plugin co-operates with simple-obfs?

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/v2ray-plugin#162]
client side: v2ray-plugin on arm64
server side: simple-obfs on linux amd64
both side in http mode.

can work normally? and vice versa.

because they were all written following sip 003 rules, same configuration, I think should work. although v2ray-plugin has some new features that simple-obfs will not understand.

if can co-opertate than it's good news. because v2ray-plugin is too big, some mips routers only 8MB rom.

thanks a lot!

**Comment by maddie** [comment]
They are different protocols. It will not work.

You will have to make two separate configurations with v2ray and obfs if you need to use both and configure your clients accordingly.

**Comment by debiansid** [comment]
@madeye 
Is it possible that you will make v2ray-plugin via C like your simple-obfs?
thanks

**Comment by maddie** [comment]
@debiansid 

I highly doubt that would be feasible. If you're looking for the 'performance' provided by C, one would have to:

1. rewrite V2Ray in C, which is quite tedious
2. compile V2Ray as Go shared library and call via C code, which defeats the purpose of getting more 'performance'

If you're looking for a smaller binary, you might want to try using tools like `upx`, but YMMV.
