### ISSUE TITLE
ss cannot start server with v2ray-plugin enabled due to 'bind: address already in use'

### ISSUE THREAD

**Issue by Shuanglu** [shadowsocks/v2ray-plugin#163]
Issue:
I was trying to use the ss with v2ray-plugin. below is the command.

ss-server -c /etc/shadowsocks-libev/config.json -p 443 --plugin v2ray-plugin plugin-opts "server;tls;host=<my domain>.com" -m chacha20-ietf-poly1305

The 1st time it started successfully. However after the restart of the machine, it failed to start due to below

 2019-11-22 17:23:10 INFO: plugin "v2ray-plugin" enabled
 2019-11-22 17:23:10 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-11-22 17:23:10 INFO: tcp server listening at **127.0.0.1:49355**
 2019-11-22 17:23:10 INFO: running from root user
2019/11/22 17:23:11 V2Ray 4.19.1 (Po) Custom
2019/11/22 17:23:11 A unified platform for anti-censorship.
2019/11/22 17:23:11 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 49355 > v2ray.com/core/transport/internet: **failed to listen on address: 127.0.0.1:49355 > listen tcp 127.0.0.1:49355: bind: address already in use**
 2019-11-22 17:23:11 ERROR: plugin service exit unexpectedly

The ss config file is the default one. The port "49355" seems to be the port used by the v2ray and it's a random value. Before the ss server start, the port was not used. Any idea why this error happened?

**Comment by vanyaindigo** [comment]
Maybe it would be better to write all config in to config.json?

**Comment by Shuanglu** [comment]
> Maybe it would be better to write all config in to config.json?

I found out the problem, there was '--' missing before 'plugin-opts'.
