### ISSUE TITLE
Is this an error? Is it serious？

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/v2ray-plugin#164]
logs like this: 
http: TLS handshake error from 27.211.184.102(an unknown ip):39103: tls: first record does not look like a TLS handshake

http: TLS handshake error from 118.119.177.137:34304: read tcp*.*.*.* (my VPS server ip):443->*.*.*.*(my IPS given ip):34304: read: connection reset by peer

http: TLS handshake error from *.*.*.*(my IPS given ip):34048: local error: tls: unexpected message

**Comment by ajimix** [comment]
I have the same problem. Why it was closed without a solution?
