### ISSUE TITLE
Redirect to local server

### ISSUE THREAD

**Issue by jeffshead** [shadowsocks/v2ray-plugin#165]
Can I specify a local web server for the redirect instead of a third-party public website? In other words, can I install Shadowsocks and v2ray-plugin on my server that also has Apache installed and have all non-Shadowsocks client traffic sent to Apache which is listening on port 123 (e.g., 127.0.0.1:123)? This way, normal HTTP/HTTPS traffic gets the website but people using a Shadowsocks client with v2ray-plugin get to use the proxy.

I was able to do this with Shadowsocks and an older version of the Cloak plugin but it no longer works after using a script that was supposed to update to the latest version.

**Comment by Mygod** [comment]
No. Report to v2ray instead.

**Comment by jeffshead** [comment]
Yes, you most certainly can!

I asked the question, here, because I wanted to know before I undertook the daunting task of reinstalling my entire setup. Since no one responded, I decided to try it and IT DOES WORK without issue.

**Comment by liveinaus** [comment]
@jeffshead do you mind sharing how you redirect the normal traffic by nginx (i.e. tell if the traffic is from SS client)

**Comment by jeffshead** [comment]
> @jeffshead do you mind sharing how you redirect the normal traffic by nginx (i.e. tell if the traffic is from SS client)

It's been a while since I did this so going from memory, you just set everything up with a reverse proxy (RP). The RP could be NGINX, Caddy, HA, Traefik, SWAG, etc,  I'm not using NGINX for this so I can't provide to you the actual setup. In essence, you allow public traffic on port 80/443 of the RP. For example, on the RP, you forward regular traffic to say port 8060 which could be an Apache server behind the RP. Then you forward v2ray traffic, on another port, to the specified path on the SS server.

Example code in the RP config file:
```
www.yoursite.com:443 {  
    reverse_proxy /path localhost:1986   #v2ray
    reverse_proxy 127.0.0.1:8060   #Apache
}
```

**Comment by liveinaus** [comment]
> > @jeffshead do you mind sharing how you redirect the normal traffic by nginx (i.e. tell if the traffic is from SS client)
> 
> It's been a while since I did this so going from memory, you just set everything up with a reverse proxy (RP). The RP could be NGINX, Caddy, HA, Traefik, SWAG, etc, I'm not using NGINX for this so I can't provide to you the actual setup. In essence, you allow public traffic on port 80/443 of the RP. For example, on the RP, you forward regular traffic to say port 8060 which could be an Apache server behind the RP. Then you forward v2ray traffic, on another port, to the specified path on the SS server.
> 
> Example code in the RP config file:
> 
> ```
> www.yoursite.com:443 {  
>     reverse_proxy /path localhost:1986   #v2ray
>     reverse_proxy 127.0.0.1:8060   #Apache
> }
> ```

I see, so basically you are using a different path for the services (SS or normal traffic). I was thinking if it is possible to use the same path or not.  For example proxy to different ports by distinguishing the protocols (or other means). But, all good, I think it is good enough for now.

Thanks for your quick reply!! 👍
