### ISSUE TITLE
Doesn't support v6?

### ISSUE THREAD

**Issue by timorpic** [shadowsocks/v2ray-plugin#17]
`{
    "server": [
        "::0", 
        "0.0.0.0"
    ], 
    "server_port":80,
    "password":"123456",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open": true
}`
`root@debian:/var/log/v2ray# ss-server -c /home/shadow-v2ray.json -p 80 --plugin /root/v2ray-plugin_linux_amd64 --plugin-opts "server"
 2019-01-19 14:30:25 INFO: using tcp fast open
 2019-01-19 14:30:25 INFO: plugin "/root/v2ray-plugin_linux_amd64" enabled
 2019-01-19 14:30:25 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-01-19 14:30:25 INFO: tcp server listening at 127.0.0.1:36019
 2019-01-19 14:30:25 INFO: running from root user
2019/01/19 14:30:25 V2Ray 4.13 (Po) Custom
2019/01/19 14:30:25 A unified platform for anti-censorship.
panic: Calling IP() on a DomainAddress.

goroutine 1 [running]:
v2ray.com/core/common/net.domainAddress.IP(0xc000020e50, 0xb, 0x986301, 0x7f6707c9ea48, 0xc000047b50)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/net/address.go:161 +0x39
v2ray.com/core/transport/internet/websocket.listenTCP(0x980720, 0xc000020078, 0x980e60, 0xc00004f520, 0xc0000f0050, 0x0, 0xc0000854f0, 0x41165c, 0x901824, 0xc000020f10, ...)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/transport/internet/websocket/hub.go:97 +0x49
v2ray.com/core/transport/internet/websocket.ListenWS(0x980720, 0xc000020078, 0x980e60, 0xc00004f520, 0xc000060050, 0xc000085bd0, 0xc00004f5b0, 0x891fc0, 0xc000047c50, 0xc000047c90, ...)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/transport/internet/websocket/hub.go:66 +0xd3
v2ray.com/core/transport/internet.ListenTCP(0x980720, 0xc000020078, 0x980e60, 0xc00004f520, 0xc000050050, 0xc000085bd0, 0xc00004f5b0, 0x0, 0xc000047e38, 0x5d2a3c, ...)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/transport/internet/tcp_hub.go:48 +0x13f
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).Start(0xc0000e62d0, 0x4296f2, 0xc000000008)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/app/proxyman/inbound/worker.go:109 +0xbb
v2ray.com/core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0xc000050a40, 0xc000061b00, 0xc000047df0)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/app/proxyman/inbound/always.go:131 +0x66
v2ray.com/core/app/proxyman/inbound.(*Manager).Start(0xc000050880, 0x0, 0x0)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/app/proxyman/inbound/inbound.go:103 +0x173
v2ray.com/core.(*Instance).Start(0xc0000507c0, 0x0, 0x0)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/v2ray.go:314 +0xac
main.main()
	/home/max/Workspace/v2ray-plugin/main.go:341 +0x6e
 2019-01-19 14:30:25 ERROR: plugin service exit unexpectedly
`

**Comment by Love4Taylor** [comment]
https://github.com/shadowsocks/v2ray-plugin/issues/12
