### ISSUE TITLE
tcp fast open未能如期运行

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/v2ray-plugin#173]
服务端：Debian 10 ，shadowsocks-libev 3.3.3（安装自backports），`echo "net.ipv4.tcp_fastopen = 3">> /etc/sysctl.conf && sysctl -p`

客户端：win10 1909 18363.535，shadowsocks-windows 4.1.9.2，`netsh int tcp set global fastopenfallback=disabled`并重启

服务端启动参数：`/ss-server -p 443 -k mypw --plugin /path2v2 --plugin-opts "fast-open;tls;host=my.dm;server"`

配置完成客户端并正常连接后，服务端使用命令 `grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92 | column -t` 检查tfo运行状态，发现未能如期运行，log如下：
`root@SAFEHOSTNAME:~# grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92 | column -t
TCPFastOpenPassiveFail  TCPFastOpenListenOverflow  TCPFastOpenCookieReqd  TCPFastOpenBlackhole  TCPSpuriousRtxHostQueues  BusyPollRxPackets
0                       0                          0                      0                     0                         0
`

1、服务端更换`websocket (HTTP)`&`Shadowsocks over quic`等混淆模式后再次进行测试，依旧未能如期运行，排除混淆方式的问题

2、服务端使用`obfs-server`插件进行测试，命令参数`ss-server -p 443 -k mypd --plugin /path2ob --plugin-opts "obfs=http;fast-open"`
此时tfo如期运行（丢失cookie），log如下
`root@SAFEHOSTNAME:~# grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92 | column -t
TCPFastOpenPassiveFail  TCPFastOpenListenOverflow  TCPFastOpenCookieReqd  TCPFastOpenBlackhole  TCPSpuriousRtxHostQueues  BusyPollRxPackets
0                       0                          7                      0                     0                         0
`

3、releases和circleci的版本都试了一遍，依旧未能如期运行，排除版本问题

**Comment by Aniark** [comment]
log排版似乎不太好，附图

未能如期运行log：
![未如期](https://user-images.githubusercontent.com/10991795/72000773-fbccea00-327e-11ea-9459-4583a723e692.jpg)
如期运行log：
![如期](https://user-images.githubusercontent.com/10991795/72000814-11421400-327f-11ea-9a14-5c3274cb2a5b.jpg)

**Comment by vanyaindigo** [comment]
With cercleci master#62:
[https://raw.githubusercontent.com/vanyaindigo/MyGitJava/master/fastopen.png](url)

**Comment by vanyaindigo** [comment]
![fastopen](https://user-images.githubusercontent.com/34334385/72133122-bb11c580-3391-11ea-8dca-54f355facecd.png)

**Comment by JoshDaone** [comment]
have same issue with 1.3.0 or circleci 66, tested same version from both server & client. Pls help.

Server-end config:

```
{
    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":443,
    "nameserver":"1.0.0.1",
    "local_port":8090,
    "password":"XXXXXXX",
    "timeout":300,
    "fast_open":true,
    "no_delay":true,
    "method":"xchacha20-ietf-poly1305",
    "plugin":"/usr/bin/v2ray-plugin_linux_amd64",
    "plugin_opts":"server;tls;fast-open;host=domain.com;cert=/path/cert.pem;key=/path/key.pem;loglevel=none"
}
```

Shadowsocks-Windows Client-side:

```
  "version": "4.1.9.2",
  "configs": [
    {
      "server": "domain.com",
      "server_port": 443,
      "password": "XXXXXXXXXX",
      "method": "xchacha20-ietf-poly1305",
      "plugin": "v2ray-plugin_windows_amd64",
      "plugin_opts": "tls;host=domain.com;fast-open",
      "plugin_args": "",
      "remarks": "server-a",
      "timeout": 20
    },
```
Either way cannot see any `TCPFastOpenCookieReqd` from /proc/net/netstat

**Comment by david9991** [comment]
sysctl.conf 加入
```
net.ipv4.tcp_fastopen_blackhole_timeout_sec=0
```
如果客户端是 macos，配置
```
net.inet.tcp.disable_tcp_heuristics=1
```
不然几次尝试后，服务端会禁止连入，macos 也会禁止继续尝试。
