### ISSUE TITLE
ci snapshot version cannot run on windows

### ISSUE THREAD

**Issue by eebssk1** [shadowsocks/v2ray-plugin#174]
The snapshot version does not have .exe suffix and windows repoerts the program is not compatible with your windows.

v2ray-plugin-windows-amd64-v1.2.0-7-g0754d6e.tar.gz

**Comment by vanyaindigo** [comment]
Well unpack the archive

**Comment by eebssk1** [comment]
> 
> 
> Well unpack the archive

you mean unpack "v2ray-plugin-windows-amd64-v1.2.0-7-g0754d6e" ？

**Comment by vanyaindigo** [comment]
Yes
