### ISSUE TITLE
CGO_ENABLED=0 while code import C

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/v2ray-plugin#18]
CGO_ENABLED is set to 0 in the build script
https://github.com/shadowsocks/v2ray-plugin/blob/cf83998cda60629ed078707815dd51eb6b65c586/build-release.sh#L34

but two android specific source code `import "C"`

**Comment by Mygod** [comment]
https://github.com/shadowsocks/v2ray-plugin/blob/cf83998cda60629ed078707815dd51eb6b65c586/build-release.sh#L22
