### ISSUE TITLE
debug error

### ISSUE THREAD

**Issue by timorpic** [shadowsocks/v2ray-plugin#19]
2019/01/22 13:31:24 [Info] [2224786249] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/22 13:31:24 [Info] [2224786249] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/01/22 13:31:24 [Info] [848192592] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/22 13:31:24 [Info] [848192592] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/01/22 13:31:35 [Info] [2224786249] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/22 13:31:35 [Info] [2224786249] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/22 13:31:35 [Info] [2224786249] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/01/22 13:31:35 [Info] [848192592] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/22 13:31:35 [Info] [848192592] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/22 13:31:35 [Info] [848192592] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/01/22 13:31:36 [Info] [2193116932] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process request > io: read/write on closed pipe
2019/01/22 13:31:36 [Info] [2193116932] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/01/22 13:31:45 [Info] [2193116932] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/22 13:31:45 [Info] [2193116932] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/22 13:31:45 [Info] [2193116932] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe

**Comment by LiveChief** [comment]
Post the entire log file please

**Comment by timorpic** [comment]
> Post the entire log file please
config.conf
{
    "server": "0.0.0.0",
    "server_port": 443,
    "password": "Admin",
    "method": "chacha20-ietf-poly1305",
    "timeout": 3600,
    "fast_open": true,
    "reuse_port": true,
    "no_delay": true,
    "plugin": "/home/v2ray-plugin_linux_amd64",
    "plugin_opts": "server;tls;host=kpo.betax.ml;cert=/etc/v2ray/v2ray.crt;key=/etc/v2ray/v2ray.key;fast-open;path=/api/;loglevel=debug",
    "ipv6_first": true,
    "mode": "tcp_and_udp"
}

log：
2019/01/28 10:37:21 [Info] [4215697493] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:60393
2019/01/28 10:37:21 [Info] [4215697493] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:60393
2019/01/28 10:37:23 [Debug] [1258254964] v2ray.com/core/proxy/dokodemo: processing connection from: 183.198.202.5:29921
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/01/28 10:37:23 tcp:183.198.202.5:29921 accepted tcp:127.0.0.1:0
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:60393
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:60393
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/01/28 10:37:23 tcp:183.198.202.5:29921 accepted tcp:127.0.0.1:0
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:60393
2019/01/28 10:37:23 [Info] [1258254964] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:60393
2019/01/28 10:37:25 [Info] [1258254964] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/28 10:37:25 [Info] [1258254964] v2ray.com/core/common/mux: session 2 ends. > io: read/write on closed pipe
2019/01/28 10:37:25 [Info] [1258254964] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/28 10:37:25 [Info] [1258254964] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/01/28 10:37:33 [Info] [1258254964] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/28 10:37:33 [Info] [1258254964] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/28 10:37:33 [Info] [1258254964] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/01/28 10:37:34 [Info] [1160320635] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/01/28 10:37:34 tcp:183.198.202.5:29903 accepted tcp:127.0.0.1:0
2019/01/28 10:37:34 [Info] [1160320635] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/01/28 10:37:34 [Info] [1160320635] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:60393
2019/01/28 10:37:34 [Info] [1160320635] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:60393
2019/01/28 10:37:37 [Info] [1160320635] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/01/28 10:37:37 [Info] [1160320635] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/01/28 10:37:37 [Info] [1160320635] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:60393
2019/01/28 10:37:37 [Info] [1160320635] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:60393
2019/01/28 10:37:37 tcp:183.198.202.5:29903 accepted tcp:127.0.0.1:0
2019/01/28 10:37:38 [Info] [3603108846] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/28 10:37:38 [Info] [3603108846] v2ray.com/core/common/mux: session 2 ends. > io: read/write on closed pipe
2019/01/28 10:37:42 [Info] [3603108846] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/01/28 10:37:42 tcp:183.198.202.5:29922 accepted tcp:127.0.0.1:0
2019/01/28 10:37:42 [Info] [3603108846] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/01/28 10:37:42 [Info] [3603108846] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:60393
2019/01/28 10:37:42 [Info] [3603108846] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:60393
2019/01/28 10:37:56 [Info] [1315325875] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/28 10:37:56 [Info] [1315325875] v2ray.com/core/common/mux: session 4 ends. > io: read/write on closed pipe
2019/01/28 10:37:56 [Info] [3557028915] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/01/28 10:37:56 [Info] [3557028915] v2ray.com/core/common/mux: session 2 ends. > io: read/write on closed pipe
2019/01/28 10:37:56 [Info] [1315325875] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/28 10:37:56 [Info] [1315325875] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/28 10:37:56 [Info] [1315325875] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/01/28 10:38:05 [Info] [3557028915] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/28 10:38:05 [Info] [3557028915] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/28 10:38:05 [Info] [3557028915] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/01/28 10:38:28 [Info] [2328850318] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1000 (normal)
2019/01/28 10:38:28 [Info] [2328850318] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/01/28 10:38:28 [Info] [2328850318] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe

**Comment by LiveChief** [comment]
https://gist.github.com/LiveChief/cffe5435e113274f73c9e8f9706b68b2

**Comment by chalist** [comment]
@Prajwal-Koirala your gist does not exist. please post again. I get this error too:

```
2020/01/23 03:53:11 [Info] [1669915622] v2ray.com/core/common/mux: dispatching request to tcp:127.0.0.1:0
2020/01/23 03:53:11 [Info] v2ray.com/core/proxy/freedom: opening connection to tcp:222.222.222.222:443
2020/01/23 03:53:11 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:11 [Info] v2ray.com/core/proxy/freedom: opening connection to tcp:222.222.222.222:443
2020/01/23 03:53:11 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:11 [Info] [2595068351] v2ray.com/core/common/mux: dispatching request to tcp:127.0.0.1:0
2020/01/23 03:53:11 [Info] v2ray.com/core/proxy/freedom: opening connection to tcp:222.222.222.222:443
2020/01/23 03:53:11 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:15 [Debug] [1004159257] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:55678
2020/01/23 03:53:15 [Info] [1004159257] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2020/01/23 03:53:15 [Info] [1004159257] v2ray.com/core/common/mux: dispatching request to tcp:127.0.0.1:0
2020/01/23 03:53:15 [Debug] [3051091140] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:55680
2020/01/23 03:53:15 [Info] [3051091140] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2020/01/23 03:53:15 [Info] [3051091140] v2ray.com/core/common/mux: dispatching request to tcp:127.0.0.1:0
2020/01/23 03:53:19 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:19 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:19 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:19 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:27 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/01/23 03:53:27 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/01/23 03:53:27 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/01/23 03:53:27 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/01/23 03:53:27 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:27 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:27 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443
2020/01/23 03:53:27 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:222.222.222.222:443

```
