### ISSUE TITLE
在终端中运行，客户端可连接上，如果做为服务启动，则无法启动.

### ISSUE THREAD

**Issue by bigbighill** [shadowsocks/v2ray-plugin#21]
[root@host xxxx]# ss-server -v -c /etc/shadowsocks-libev/config.json
 2019-01-22 17:58:35 INFO: using tcp fast open
 2019-01-22 17:58:35 INFO: plugin "v2ray-plugin" enabled
 2019-01-22 17:58:35 INFO: UDP relay enabled
 2019-01-22 17:58:35 INFO: initializing ciphers... aes-256-gcm
 2019-01-22 17:58:35 INFO: using nameserver: 8.8.8.8
 2019-01-22 17:58:35 INFO: tcp server listening at 127.0.0.1:34797
 2019-01-22 17:58:35 INFO: udp server listening at 0.0.0.0:443
2019/01/22 17:58:35 V2Ray 4.13 (Po) Custom
2019/01/22 17:58:35 A unified platform for anti-censorship.
2019/01/22 17:58:35 [Warning] v2ray.com/core: V2Ray 4.13 started
2019/01/22 17:58:43 tcp:49.90.184.119:31538 accepted tcp:127.0.0.1:0 
 2019-01-22 17:58:43 INFO: accept a connection
 2019-01-22 17:58:43 INFO: [443] connect to www.google.com:443
 2019-01-22 17:58:43 INFO: found address name v6 address www.google.com
 2019-01-22 17:58:43 INFO: found address name v4 address www.google.com
 2019-01-22 17:58:43 INFO: successfully resolved www.google.com
 2019-01-22 17:58:43 INFO: remote connected
 2019-01-22 17:58:43 INFO: remote_recv close the connection
 2019-01-22 17:58:43 INFO: current remote connection: 0
 2019-01-22 17:58:43 INFO: current server connection: 0

config.json
{   "server":"0.0.0.0",
    "server_port":443,
    "password":"1234",
    "timeout":300,
    "method":"aes-256-gcm",
    "fast_open":true,
    "user":"nobody",
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"v2ray-plugin",
    "plugin_opts":"server;tls;host=xxxx.com;cert=/root/.acme.sh/xxxx.com/fullchain.cer;key=/root/.acme.sh/xxxx.com/xxxx.com.key"
}
在终端中运行，客户端可连接上，如果做为服务启动，则无法启动
Jan 22 17:39:43 host shadowsocks-libev: Starting Shadowsocks-libev success
Jan 22 17:39:43 host systemd: Started LSB: Fast tunnel proxy that helps you bypass firewalls.
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: using tcp fast open
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: plugin "v2ray-plugin" enabled
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: UDP relay enabled
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: initializing ciphers... aes-256-gcm
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: using nameserver: 8.8.8.8
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: tcp server listening at 127.0.0.1:58155
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: udp server listening at 0.0.0.0:443
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: plugin service exit unexpectedly
Jan 22 17:39:43 host /usr/local/bin/ss-server[3928]: closed gracefully
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: using tcp fast open
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: plugin "v2ray-plugin" enabled
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: UDP relay enabled
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: initializing ciphers... aes-256-gcm
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: using nameserver: 8.8.8.8
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: tcp server listening at 127.0.0.1:47393
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: udp server listening at 0.0.0.0:443
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: plugin service exit unexpectedly
Jan 22 17:52:52 host /usr/local/bin/ss-server[3945]: closed gracefully
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: using tcp fast open
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: plugin "v2ray-plugin" enabled
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: UDP relay enabled
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: initializing ciphers... aes-256-gcm
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: using nameserver: 8.8.8.8
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: tcp server listening at 127.0.0.1:49533
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: udp server listening at 0.0.0.0:443
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: plugin service exit unexpectedly
Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: closed gracefully

**Comment by LiveChief** [comment]
```
{
    "server":["[::0]","0.0.0.0"],
    "server_port":443,
    "password":"PASSWORD",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "nameserver": "8.8.8.8",
    "fast_open":true,
    "reuse_port":true,
    "no_delay":true,
    "mode":"tcp_only"
    "plugin":"v2ray-plugin", 
    "plugin_opts":"server;tls;host=xxxx .com;cert=/root/.acme.sh/xxxx.com/fullchain.cer;key=/root/.acme.sh/xxxx.com/xxxx.com.key"
 }
```

Try this...

The issue should be UDP

**Comment by bigbighill** [comment]
还是不行，只要以service方式启动 shadowsocks-libev，还是启动失败

**Comment by bigbighill** [comment]
> 
> 
> ```
> {
>     "server":["[::0]","0.0.0.0"],
>     "server_port":443,
>     "password":"PASSWORD",
>     "timeout":300,
>     "user":"nobody",
>     "method":"aes-256-gcm",
>     "nameserver": "8.8.8.8",
>     "fast_open":true,
>     "reuse_port":true,
>     "no_delay":true,
>     "mode":"tcp_only"
>     "plugin":"v2ray-plugin", 
>     "plugin_opts":"server;tls;host=xxxx .com;cert=/root/.acme.sh/xxxx.com/fullchain.cer;key=/root/.acme.sh/xxxx.com/xxxx.com.key"
>  }
> ```
> 
> Try this...
> 
> The issue should be UDP
> `Jan 22 17:55:24 host /usr/local/bin/ss-server[3962]: udp server listening at 0.0.0.0:443`
还是不行，只要以service方式启动 shadowsocks-libev，还是启动失败

我的两种启动shadowsocks-libev方式：
第一种使用的是秋水逸冰的做的
https://github.com/teddysun/shadowsocks_install/raw/master/shadowsocks-libev
/etc/init.d/srtart restart stop status
第二种是 /etc/systemd/system/shadowsocks-libev.service
[Unit]
Description=Shadowsocks-Libev Server Service
After=network.target

[Service]
Type=simple
User=nobody
PIDFile=/var/run/shadowsocks-libev.pid
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config.json
[Install]
WantedBy=multi-user.target      

你是以何种方式启动shadowsocks-libev？方便贴出你用的shadowsocks-libev.service内容啊。

**Comment by LiveChief** [comment]
English?

**Comment by bigbighill** [comment]
> 
> 
> English?
google translate:
Still not, as long as you start shadowsocks-libev in service mode, the startup fails.
How do you start shadowsocks-libev? Conveniently post the shadowsocks-libev.service content you use.

**Comment by LiveChief** [comment]
Was able to replicate the same error on my own VPS, seems like your not the only one facing this issue

**Comment by bigbighill** [comment]
> 
> 
> Was able to replicate the same error on my own VPS, seems like your not the only one facing this issue

maybe ss-libev bug or v2ray-plugin bug

**Comment by madeye** [comment]
Change `"plugin":"v2ray-plugin",` to `"plugin":"/absolute/path/to/v2ray-plugin", `

**Comment by bigbighill** [comment]
> 
> 
> Change `"plugin":"v2ray-plugin",` to `"plugin":"/absolute/path/to/v2ray-plugin", `

Change `"plugin":"v2ray-plugin",` to `"plugin":"/usr/local/bin/v2ray-plugin"  
shadowsocks-libev.service can not boot

**Comment by madeye** [comment]
Try the command `setcap cap_net_bind_service=+ep /usr/local/bin/v2ray-plugin` first.

**Comment by bigbighill** [comment]
> 
> 
> Try the command `setcap cap_net_bind_service=+ep /usr/local/bin/v2ray-plugin` first.

done ,but shadowsocks-libev.service can not boot still.

` shadowsocks-libev.service - LSB: Fast tunnel proxy that helps you bypass firewalls
   Loaded: loaded (/etc/rc.d/init.d/shadowsocks-libev; bad; vendor preset: disabled)
   Active: active (exited) since 三 2019-01-23 15:35:25 CST; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3753 ExecStop=/etc/rc.d/init.d/shadowsocks-libev stop (code=exited, status=1/FAILURE)
  Process: 3756 ExecStart=/etc/rc.d/init.d/shadowsocks-libev start (code=exited, status=0/SUCCESS)

1月 23 15:35:25 host.localdomain systemd[1]: Starting LSB: Fast tunnel proxy that helps you bypass firewalls...
1月 23 15:35:25 host.localdomain shadowsocks-libev[3756]: Starting Shadowsocks-libev success
1月 23 15:35:25 host.localdomain systemd[1]: Started LSB: Fast tunnel proxy that helps you bypass firewalls.
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: using tcp fast open
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: plugin "/usr/local/bin/v2ray-plugin" enabled
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: UDP relay enabled
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: initializing ciphers... aes-256-gcm
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: using nameserver: 8.8.8.8
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: tcp server listening at 127.0.0.1:59337
1月 23 15:35:25 host.localdomain /usr/local/bin/ss-server[3759]: udp server listening at 0.0.0.0:443
`

**Comment by madeye** [comment]
According to your log, it boots successfully and works well.

**Comment by madeye** [comment]
I see the problem:

```
"plugin_opts":"server;tls;host=xxxx.com;cert=/root/.acme.sh/xxxx.com/fullchain.cer;key=/root/.acme.sh/xxxx.com/xxxx.com.key"
```

You're trying to read files in `/root` directory as `nobody`.

**Comment by bigbighill** [comment]
> 
> 
> According to your log, it boots successfully and works well.

**NOT WORKS WELL**

1、/etc/init.d/shadowsocks-libev（https://github.com/teddysun/shadowsocks_install/raw/master/shadowsocks-libev）

/etc/init.d/shadowsocks-libev
chkconfig add shadowsocks-libev
chkconfig shadowsocksocks-libev on
systemctl start shadowsocks-libev 

shadowsocks-libev.service can not boot.

2、2、run /usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config.json in terminal
boot sucess

**Comment by bigbighill** [comment]
> 
> 
> I see the problem:
> 
> ```
> "plugin_opts":"server;tls;host=xxxx.com;cert=/root/.acme.sh/xxxx.com/fullchain.cer;key=/root/.acme.sh/xxxx.com/xxxx.com.key"
> ```
> 
> You're trying to read files in `/root` directory as `nobody`.

> {   "server":"0.0.0.0",
>     "server_port":443,
>     "password":"password",
>     "timeout":300,
>     "method":"aes-256-gcm",
>     "fast_open":true,
>     "reuse":true,
>     "nameserver":"8.8.8.8",
>     "mode":"tcp_and_udp",
>     "plugin":"/usr/local/bin/v2ray-plugin",
>     "plugin_opts":"server;tls;host=www.marading.tk;cert=/root/.acme.sh/www.marading.tk/fullchain.cer;key=/root/.acme.sh/www.marading.tk/www.marading.tk.key"
> }
> 

shadowsocks-libev.service can not boot sucessfully

**Comment by Mygod** [comment]
@madeye Speaking of this, maybe we should [implement a permission too open error](https://stackoverflow.com/q/9270734/2245107) for private key files.

**Comment by madeye** [comment]
@Mygod You see, even without "too open error", our user is trying to read `/root` as `nobody` and got confused already.

**Comment by Mygod** [comment]
Well that's just because we didn't make a guide (and I'm definitely not going to. Somebody please do it for me thanks :rofl:).

**Comment by DearTanker** [comment]
想知道是如何解决的。。
