### ISSUE TITLE
http fake identify issue

### ISSUE THREAD

**Issue by PHCSJC** [shadowsocks/v2ray-plugin#215]
This issue is from v2ray:
https://github.com/v2ray/v2ray-core/issues/2537

Do this issue effect v2ray-plugin? or need update for fix?

**Comment by Mygod** [comment]
It is expected that HTTP only provides only weak traffic obfuscation. You can probably find a lot more similar ways to identify v2ray server fingerprint so I consider this as a wontfix.

We will however merge upstream releases periodically.

**Comment by PHCSJC** [comment]
v2ray have released new fix this issue.

**Comment by Mygod** [comment]
If you worry about the vulnerability, maybe you shouldn't use HTTP mode in the first place.
