### ISSUE TITLE
shadowsocks+v2ray-plugin+CDN on IPv6 problem (client IPv4 but the server IPv6)

### ISSUE THREAD

**Issue by sleeplife** [shadowsocks/v2ray-plugin#222]
guys please help me
I followed this link https://www.reddit.com/r/dumbclub/comments/f8xs24/howto_shadowsocks_server_with_v2ray_plugin/
I also checked and I saw nginx welcome page but....

1. Server is **NAT-IPv4** with **dedicated IPv6** which I used for cloudflare (**AAAA**)

nginx configure (`/etc/nginx/sites-available/default`)
```
server_name sire.com;

        location /test {
                proxy_redirect off;
                proxy_pass https://localhost:210;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;
        }
```
....
```
    listen [::]:443 ssl http2 ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/site.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/site.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    ssl_session_cache shared:SSL:1m;
```
and `/etc/nginx/sites-enabled/default` :
```
    listen [::]:443 ssl http2 ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/site.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/site.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    ssl_session_cache shared:SSL:1m;
```
Shadowsocks (`/etc/shadowsocks-libev/config.json`)
```
{
    "prefer_ipv6": true,
    "ipv6_first": true,
    "server": "localhost",
    "server_port": 210,
    "password":"apassword",
    "timeout":300,
    "method":"aes-256-gcm",
    "plugin":"v2ray-plugin",
    "plugin_opts":"server;path=/test;tls;host=site.com;loglevel=none",
    "fast_open": false
}
```

After running
```
root@host:~# ssserver -c /etc/shadowsocks-libev/config.json
INFO: loading config from /etc/shadowsocks-libev/config.json
2020-08-02 06:03:09 INFO     loading libcrypto from libcrypto.so.1.1
2020-08-02 06:03:09 INFO     loading libsodium from libsodium.so.23
2020-08-02 06:03:09 INFO     starting server at localhost:210
```
After trying to connect: (It didnt connect after I press the bottom gray part to ping, it is being shown on the server):
```
2020-08-02 06:03:15 ERROR    Finalize cipher failed
2020-08-02 06:03:15 ERROR    Finalize cipher failed
2020-08-02 06:03:16 ERROR    Finalize cipher failed
```
**need to turn on TAP/TUN or FUSE?**

**Comment by vanyaindigo** [comment]
You can check this [guide](https://overclockers.ru/blog/Indigo81/show/31739/shadowsocks-cherez-cloudflare-cdn-povyshaem-bezopasnost-v-seti) too

**Comment by andymc88** [comment]
This worked for me on IPv6 server with Ubuntu 20.04.

```
wget https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.1/v2ray-plugin-linux-amd64-v1.3.1.tar.gz

tar -xf v2ray-plugin-linux-amd64-v1.3.1.tar.gz

cp v2ray-plugin_linux_amd64 /usr/bin/v2ray-plugin
```

```
apt install shadowsocks-libev -y
```

Edit /etc/shadowsocks-libev/config.json

```
{
    "server":"::1",
    "server_port":10001,
    "password":"pass1234",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "ipv6_first":true,
    "plugin":"/usr/bin/v2ray-plugin",
    "plugin_opts":"server;path=/abc123"
}
```

`systemctl restart shadowsocks-libev`

Edit /etc/nginx/sites-available/default to add new Nginx location block within server block for port 443.

```
location /abc123 {
    proxy_redirect off;
    proxy_pass http://[::1]:10001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
}
```

```
systemctl restart nginx
```

Client settings for Android

- Profile Name = Example
- Server = www.example.com
- Remote Port = 443
- Password = pass1234
- Encrypt Method = chacha20-ietf-poly1305
- Route = All
- IPv6 Route = On
- Apps VPN Mode = Off
- Metered Hint = Off
- Remote DNS = 8.8.8.8
- Send DNS over UDP = Off
- Plugin = v2ray
- Transport mode = websocket-tls
- Hostname = www.example.com
- Path = /abc123
- Concurrent connections = 1
- Certificate for TLS verification = Not set
- Logcat level = warning
- Generated line = path=/abc123;host=www.example.com;tls
- UDP Fallback = Disabled

**Comment by liujunhui74** [comment]
> 
> ```
> {
>     "prefer_ipv6": true,
>     "ipv6_first": true,
>     "server": "localhost",
>     "server_port": 210,
>     "password":"apassword",
>     "timeout":300,
>     "method":"aes-256-gcm",
>     "plugin":"v2ray-plugin",
>     "plugin_opts":"server;path=/test;tls;host=site.com;loglevel=none",
>     "fast_open": false
> } ```

You should better not enable tls in your ss-server config.
Remove 'tls' in your plugin_opts, and replace https://localhost with http://localhost in your nginx conf file.

**Comment by vanyaindigo** [comment]
> You should better not enable tls in your ss-server config.
> Remove 'tls' in your plugin_opts, and replace https://localhost with http://localhost in your nginx conf file.

It seems that this will be better, but when terminating TLS in the plugin, the server speed is higher

**Comment by liujunhui74** [comment]
> > You should better not enable tls in your ss-server config.
> > Remove 'tls' in your plugin_opts, and replace https://localhost with http://localhost in your nginx conf file.
> 
> It seems that this will be better, but when terminating TLS in the plugin, the server speed is higher

Why does terminating TLS in the plugin result in higher speed?
By the way, if TLS is terminated in the plugin, nginx is no longer needed.

**Comment by vanyaindigo** [comment]
Nginx's goal is not to terminate TLS, but to cover the entry point

**Comment by andymc88** [comment]
Also, camouflage web pages are intended to survive even manual inspection of the server.

**Comment by vanyaindigo** [comment]
True, but the volume of traffic and frequency of requests will still give you away

**Comment by sleeplife** [comment]
> 
> This worked for me on IPv6 server with Ubuntu 20.04.
> 
This worked for me too

I used the `ubuntu-ss-install.sh` first time 

> https://www.reddit.com/r/dumbclub/comments/f8xs24/howto_shadowsocks_server_with_v2ray_plugin/

but this time I install shadowsocks-libv myself and v2ray by your link

thank you so much and everyone who replied

**Comment by aboka2k** [comment]
hi all, thanks for the posting as i hv learn a bit more than yesterday. but after reading more than 10 times and thinking the whole day, im so confuse..... cant understand how 'proxy_pass' works.

I mean shouldn't we be using https and tls on the ss-server config since all is https traffic - from cdn(strict ssl/https always on), nginx strict https(option #2) and client using 443/tls to connect

my understanding of proxy_pass mean it will divert all the traffic to the specify address:port, so if thats true and this 'proxy_pass http://localhost:210' means all http traffic should goto localhost:210, but what about https traffics?

thank you,

**Comment by liujunhui74** [comment]
> hi all, thanks for the posting as i hv learn a bit more than yesterday. but after reading more than 10 times and thinking the whole day, im so confuse..... cant understand how 'proxy_pass' works.
> 
> I mean shouldn't we be using 'https://localhost:210' and tls on the ss-server config since all is https traffic - from cdn(strict ssl/https always on), nginx strict https(option no.2 certbot) and client using 443/tls to connect
> 
> my understanding of proxy_pass mean it will divert all the traffic to the specify address:port, so if thats true and this 'proxy_pass http://localhost:210' means all http traffic should goto localhost:210, but what about https traffics?
> 
> thank you,

Direct connection
[you (e.g. Firefox)] ------------------------------------- [e.g. Google]

Plain ss
[you]--[ss client]======<ss protocol>======[ss server] ---- [Google]

SS + v2ray
[you]--[ss client]==[v2ray plugin]≡≡≡≡≡≡<https>≡≡≡≡≡≡[v2ray plugin]==[ss server] ---- [Google]

SS + v2ray + nginx
[you]--[ss client]==[v2ray plugin]≡≡≡≡≡≡<https>≡≡≡≡≡≡[nginx]-<http>-[v2ray plugin]==[ss server] ---- [Google]

SS + v2ray + nginx + CDN (+ IPv6)
[you]--[ss client]==[v2ray plugin]≡≡≡<https>≡≡≡[CDN]≡≡≡<https/IPv4|6>≡≡≡[nginx]-<http>-[v2ray plugin]==[ss server] ---- [ Google]

Your VPS = {[nginx]-<http>-[v2ray plugin]==[ss server]}. Nobody is able to intercept the traffic between nginx and v2ray plugin so there is no need to use https.

**Comment by aboka2k** [comment]
> SS + v2ray + nginx + CDN (+ IPv6)
[you]--[ss client]==[v2ray plugin]≡≡≡<https>≡≡≡[CDN]≡≡≡<https/IPv4|6>≡≡≡[nginx]-<http>-[v2ray plugin]==[ss server] ---- [ Google]

thanks a lot for the visualization, i think i got it this time - nginx is accepting and terminating the https and then proxying using http to v2ray. and since the traffic is passing internally, so no need https :)

cheers,

**Comment by aboka2k** [comment]
hi all, got another question after reviewing the setup here and searching online regarding websocket. In all the example here, the ss-server config does not use websocket in the plugin_opts - mode=websocket. may i ask why? is it bcoz it is enable by default or its not needed, etc?

thank you,
