### ISSUE TITLE
TLS vs HTTP 

### ISSUE THREAD

**Issue by LiveChief** [shadowsocks/v2ray-plugin#23]
Difference?

also which one is recommended ?

@MyGod

**Comment by e2ge** [comment]
ws和http是同一层的，http可以tls，ws也可以tls，没有ws+http。

**Comment by LiveChief** [comment]
English??

**Comment by Mygod** [comment]
Depends.

**Comment by LiveChief** [comment]
@Mygod 

I understand your quite busy but it would be amazing if u just took like 2 mins of your time to explain, plz
