### ISSUE TITLE
Go build failed: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

### ISSUE THREAD

**Issue by NullPointerDu** [shadowsocks/v2ray-plugin#246]
go build

go: downloading github.com/v2fly/v2ray-core/v4 v4.38.3
go: downloading github.com/golang/protobuf v1.5.2
go: extracting github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/protobuf v1.26.0
go: extracting github.com/v2fly/v2ray-core/v4 v4.38.3
go: extracting google.golang.org/protobuf v1.26.0
go: downloading golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
go: downloading github.com/pires/go-proxyproto v0.5.0
go: downloading github.com/gorilla/websocket v1.4.2
go: extracting golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
go: extracting github.com/gorilla/websocket v1.4.2
go: downloading github.com/lucas-clemente/quic-go v0.20.1
go: downloading golang.org/x/sys v0.0.0-20210415045647-66c3f260301c
go: extracting github.com/pires/go-proxyproto v0.5.0
go: extracting github.com/lucas-clemente/quic-go v0.20.1
go: downloading github.com/cheekybits/genny v1.0.0
go: extracting github.com/cheekybits/genny v1.0.0
go: extracting golang.org/x/sys v0.0.0-20210415045647-66c3f260301c
go: finding github.com/golang/protobuf v1.5.2
go: finding github.com/v2fly/v2ray-core/v4 v4.38.3
go: finding google.golang.org/protobuf v1.26.0
go: finding github.com/pires/go-proxyproto v0.5.0
go: finding golang.org/x/sys v0.0.0-20210415045647-66c3f260301c
go: finding github.com/gorilla/websocket v1.4.2
go: finding github.com/lucas-clemente/quic-go v0.20.1
go: finding github.com/cheekybits/genny v1.0.0
go: finding golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
build github.com/shadowsocks/v2ray-plugin: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

**Comment by NullPointerDu** [comment]
Issue solved after update GO version.

**Comment by hzjnet** [comment]
具体什么版本啊？ 我系统已经更新到最新了，还是上面问题
