### ISSUE TITLE
armv7 version appear Illegal instruction error on openwrt armv7 platform

### ISSUE THREAD

**Issue by xiedeacc** [shadowsocks/v2ray-plugin#258]
cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1000.00
Features        : half thumb fastmult edsp tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : BCM5301X
Revision        : 0000
Serial          : 0000000000000000

./v2ray-plugin_linux_arm7
Illegal instruction

device: netgear r8000

can U(maintainers) fix cross build problem?

**Comment by xiedeacc** [comment]
> check this https://github.com/teddysun/v2ray-plugin

thanks

**Comment by HiHat** [comment]
Please use arm5 plugin version with soft floating point (arm6 and arm7 versions for hard float ARM CPU).
