### ISSUE TITLE
ERROR when enable ipv6

### ISSUE THREAD

**Issue by Old-Pussy** [shadowsocks/v2ray-plugin#28]
When I write my config.json like`"server":["::0","0.0.0.0"],` ,it will says 

>panic: Calling IP() on a DomainAddress.
 goroutine 1 [running]:
v2ray.com/core/common/net.domainAddress.IP(0xc000026e50, 0xb, 0x98fa01, 0x7f26134baa48, 0xc0000c3b50)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/common/net/address.go:161 +0x39
v2ray.com/core/transport/internet/websocket.listenTCP(0x989e40, 0xc000026078, 0x98a580, 0xc000057520, 0xc000100050, 0x0, 0xc0000994f0, 0x41340c, 0x90a477, 0xc000026f10, ...)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/transport/internet/websocket/hub.go:97 +0x49
v2ray.com/core/transport/internet/websocket.ListenWS(0x989e40, 0xc000026078, 0x98a580, 0xc000057520, 0xc000070050, 0xc000099bd0, 0xc0000575b0, 0x89a520, 0xc0000c3c50, 0xc0000c3c90, ...)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/transport/internet/websocket/hub.go:66 +0xd3
v2ray.com/core/transport/internet.ListenTCP(0x989e40, 0xc000026078, 0x98a580, 0xc000057520, 0xc000060050, 0xc000099bd0, 0xc0000575b0, 0x0, 0xc0000c3e38, 0x5da1dc, ...)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/transport/internet/tcp_hub.go:48 +0x13f
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).Start(0xc0000f62d0, 0x42b4e2, 0xc000000008)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/app/proxyman/inbound/worker.go:109 +0xbb
v2ray.com/core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0xc000060a40, 0xc000077b00, 0xc0000c3df0)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/app/proxyman/inbound/always.go:131 +0x66
v2ray.com/core/app/proxyman/inbound.(*Manager).Start(0xc000060880, 0x0, 0x0)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/app/proxyman/inbound/inbound.go:103 +0x173
v2ray.com/core.(*Instance).Start(0xc0000607c0, 0x0, 0x0)
	/root/go/pkg/mod/v2ray.com/core@v4.13.0+incompatible/v2ray.go:314 +0xac
main.main()
	/root/v2ray-plugin/main.go:341 +0x6e
 2019-01-27 14:15:13 ERROR: plugin service exit unexpectedly

**Comment by LiveChief** [comment]
Hey dude just do 0.0.0.0 this will enable ipv4 / ipv6
