### ISSUE TITLE
v2ray-plugin support Caddy reverse proxy？

### ISSUE THREAD

**Issue by bigbighill** [shadowsocks/v2ray-plugin#30]
v2ray-plugin support Caddy reverse proxy？
Caddyfile

`domain.com {`
`       tls xxx@gmail.com`
`       gzip`
`       timeouts none`
`       proxy /xx 127.0.0.1:444 {`
`       without /xx`
`       websocket`
`    }`
`}`

android can not connect

@madeye

**Comment by VictoriaRaymond** [comment]
Technically yes. Please check logs from V2Ray and Caddy.

**Comment by bigbighill** [comment]
**shadowsocks-libev + v2ray-plugin log**
`2019/01/29 21:58:29 http: TLS handshake error from 127.0.0.1:47174: tls: first record does not look like a TLS handshake
2019/01/29 21:58:32 http: TLS handshake error from 127.0.0.1:47176: tls: first record does not look like a TLS handshake
2019/01/29 21:58:33 http: TLS handshake error from 127.0.0.1:47178: tls: first record does not look like a TLS handshake
2019/01/29 21:58:51 http: TLS handshake error from 127.0.0.1:47180: tls: first record does not look like a TLS handshake
2019/01/29 21:58:51 http: TLS handshake error from 127.0.0.1:47182: tls: first record does not look like a TLS handshake
2019/01/29 21:58:52 http: TLS handshake error from 127.0.0.1:47184: tls: first record does not look like a TLS handshake
2019/01/29 21:58:52 http: TLS handshake error from 127.0.0.1:47186: tls: first record does not look like a TLS handshake
2019/01/29 21:58:53 http: TLS handshake error from 127.0.0.1:47188: tls: first record does not look like a TLS handshake
2019/01/29 21:58:56 http: TLS handshake error from 127.0.0.1:47190: tls: first record does not look like a TLS handshake
2019/01/29 21:58:57 http: TLS handshake error from 127.0.0.1:47192: tls: first record does not look like a TLS handshake`
**caddy log**
`1月 29 21:58:29 host.localdomain caddy[4124]: 29/Jan/2019:21:58:29 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:32 host.localdomain caddy[4124]: 29/Jan/2019:21:58:32 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:33 host.localdomain caddy[4124]: 29/Jan/2019:21:58:33 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:51 host.localdomain caddy[4124]: 29/Jan/2019:21:58:51 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:51 host.localdomain caddy[4124]: 29/Jan/2019:21:58:51 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:52 host.localdomain caddy[4124]: 29/Jan/2019:21:58:52 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:52 host.localdomain caddy[4124]: 29/Jan/2019:21:58:52 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:53 host.localdomain caddy[4124]: 29/Jan/2019:21:58:53 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:56 host.localdomain caddy[4124]: 29/Jan/2019:21:58:56 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
1月 29 21:58:57 host.localdomain caddy[4124]: 29/Jan/2019:21:58:57 +0800 [ERROR 502 /xxx] net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
`

**Comment by VictoriaRaymond** [comment]
You have TLS enabled on your client, but not in Caddy

**Comment by bigbighill** [comment]
v2ray-plugin for android  tranport mode :websocet-tls,but can not connected

**Comment by USDao** [comment]
@bigbighill can give configfiles and caddyfile look？

**Comment by boris1993** [comment]
@USDao Maybe you can refer to [this article](https://github.com/boris1993/shadowsocks-v2ray-docker#case-example)

**Comment by tefiszx** [comment]
@bigbighill could you please show me Caddy config file.I have encountered the same error you mentioned above.
