### ISSUE TITLE
Shadowsocks, v2ray, and simple-obfs

### ISSUE THREAD

**Issue by altayhunter** [shadowsocks/v2ray-plugin#31]
I'm confused about the relationship between shadowsocks, v2ray, and simple-obfs. My understanding of simple-obfs was that it wrapped the messages with an HTTP header to make them appear more like web traffic, and allowed servers to failover to a webpage making them appear like actual webservers.
Simple-obfs is now deprecated and replaced with this v2ray-plugin which doesn't appear to have the failover option for servers. What does this plugin actually do and how is it related to v2ray? Does it use the VMess protocol?
Also, is there a difference between running shadowsocks-libev with the v2ray-plugin and running v2ray with a shadowsocks configuration? Should those be compatible with each other?

**Comment by LiveChief** [comment]
Simple osfb is complete garbage compared to this, that's all u need to know.

**Comment by hybtoy** [comment]
@LiveChief video is unavailable. Is there any configuration manual for CDN mode? 
Thanks.

**Comment by LiveChief** [comment]
Give me 24 hours I'll either create a step by step or just a video.

**Comment by malikshi** [comment]
> Setup v2ray normally , buy a free domains add it to cloudflare and add the IP for SS server to @ records set SSL to flexible
> 
> Find cloudflare IP range, connect to the Ip for cloudflare IP range , For SS and set the host to your domain
> 
> IP: Cloudflare IP
> Password: Normal Password
> Domain: example.com

is it legit, did you try using v2ray from shadowsocks or original v2ray?

**Comment by LiveChief** [comment]
V2ray plugin for shadowsocks

**Comment by malikshi** [comment]
> > Setup v2ray normally , buy a free domains add it to cloudflare and add the IP for SS server to @ records set SSL to flexible
> > Find cloudflare IP range, connect to the Ip for cloudflare IP range , For SS and set the host to your domain
> > IP: Cloudflare IP
> > Password: Normal Password
> > Domain: example.com
> 
> is it legit, did you try using v2ray from shadowsocks or original v2ray?

can i see the config in CF and SS client? i dont quite understand it, i tried add @ at CF to my IP public VPS with DNS & HTTP(CDN) ON, then im setting SS client with example.com to connect but no response at all.

**Comment by LiveChief** [comment]
Set SSL to flexible, and connect to cloudflare IP range and in host is example.com

**Comment by malikshi** [comment]
> Set SSL to flexible, and connect to cloudflare IP range and in host is example.com

sent me screenshot please

**Comment by malikshi** [comment]
[https://github.com/shadowsocks/v2ray-plugin/issues/31#issuecomment-460236841](url)
![screenshot_701](https://user-images.githubusercontent.com/9080737/52312536-73dec000-29dd-11e9-88ee-d6afb58f387b.png)

**Comment by LiveChief** [comment]
choose a ip from here for the IP u connect 
https://www.cloudflare.com/ips/

start server on port 80
and connect...

**Comment by malikshi** [comment]
Thanks alot I will try this one. So set ss-server port 80 not 443 ?

**Comment by LiveChief** [comment]
Yes

**Comment by malikshi** [comment]
> Yes, don't connect to server directly connect it via cloudflare so u connect to the cloudflare IP range

here my setting, no luck at all, what should i do?
![screenshot_703](https://user-images.githubusercontent.com/9080737/52330558-43704380-2a28-11e9-8181-571a1f2bef05.png)

**Comment by LiveChief** [comment]
```
nano /etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "server_port":80,
    "password":"<PASSWORD>",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "nameserver": "8.8.8.8",
    "fast_open":true,
    "reuse_port":true,
    "no_delay":true,
    "plugin":"/etc/shadowsocks-libev/<FILE_NAME>",
    "plugin_opts":"server"
}
```
Use this config
Change filename and password.

After this , add the domain to cloudflare and the @ paste your VPS IP there

Share the pic of cloudflare

**Comment by jibon57** [comment]
@LiveChief , thanks for your explanation. I have used `domain` name instated of IP as `Server` in client but both is working 👍

**Comment by LiveChief** [comment]
:)
Connect to cloudflare IP not your VPS IP.

**Comment by jibon57** [comment]
@LiveChief yes, I had setup my domain with my VPS IP in cloudflare. Later I had used that domain directly but using cloudflare IP worked too.

**Comment by LiveChief** [comment]
Perfect

**Comment by terrytw** [comment]
> Perfect

If I'm not mistaken, connection speed to cloudflare could be a bottleneck here, right?

**Comment by malikshi** [comment]
@terrytw my speed almost same as my ISP speed.

**Comment by terrytw** [comment]
@malikshi 

Thank you for the feedback. 

But cloudflare does not offer the best connection speed in my country. So I just want to be sure. From my understanding, you are actually connecting to a cloudflare server which then redirect you to the real server, right?

**Comment by malikshi** [comment]
Rights my ISP speed 14-25Mbps. I'm never try on home network isp

**Comment by LiveChief** [comment]
@terrytw its slower by like 5-10% max
https://www.cloudflare.com/ips/

just find a server closest to you.

**Comment by terrytw** [comment]
@LiveChief Cheers.

**Comment by denoza** [comment]
I followed your discussion here, however while using v2ray with cloudflare, I am facing following issue:

`failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 80 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:80 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:80 > listen tcp 0.0.0.0:80: bind: address already in use`

Is there any solution for this?

**Comment by LiveChief** [comment]
Other applications are using port 80, kill the other app that's using that port and restart the server and do it again and it should work.

**Comment by denoza** [comment]
@LiveChief Thanks, I figured it out.

**Comment by MeIsReallyBa** [comment]
> Simple osfb is complete garbage compared to this, that's all u need to know.
> 
> This will use web socket to hide your network traffic and you can use this behind a CDN, while on simple osfb just a header was added and using DPI we could find out the server and just ban the server ip but if we use this with cloudflare they will have to block almost 7m+ sites just to block your shadow socks proxy..
> 
> https://www.youtube.com/watch?v=5gjEUM-_E08

In fact,by using OSFB,we could still make our network traffic via cdn just like v2ray plugin do.

**Comment by dimqua** [comment]
@MeIsReallyBa could you provide more details?

**Comment by doublesixwings** [comment]
@LiveChief Is it necessary to build a real website?

**Comment by LiveChief** [comment]
@doublesixwings u dont need to build a website
you just need the domain and the access to dns records.

**Comment by doublesixwings** [comment]
@LiveChief What will happen if the DPI try to visit the domain?

**Comment by LiveChief** [comment]
DPI will see a error on the website and a 404 page

**Comment by doublesixwings** [comment]
@LiveChief So for better security, I think it's a good choice to build a real website that pointed by the domain name, am I right? As @MeIsReallyBa said before, the simple-obfs also can use cdn provided by cloudflare to hide the real IP, so I don't see the superiority of v2ray-plugin over simple-obfs.

**Comment by LiveChief** [comment]
U use websockets to transfer data instead of just adding a header.

**Comment by doublesixwings** [comment]
@LiveChief Maybe, but from my own experience, the free cdn service of cloudflare will slowdown the speed obviously, I have used simple-obfs for almost 2 years, for better network speed I don't use the cdn, although it was deprecated by author, I just don't have a driving force to change to v2ray-plugin.

**Comment by LiveChief** [comment]
@doublesixwings it will take less than 10 mins i can guarantee you that 
https://github.com/LiveChief/Fun-Linux-Scripts/blob/master/Shadowsocks_With_V2Ray.md

cloudflare didn't slow any speeds for me i was getting about 90 - 95% of the normal speeds.

**Comment by doublesixwings** [comment]
@LiveChief As I known, the free cdn nodes of cloudflare are all in US, I don't think it won't slow the network speed if your vps is in hongkong.

**Comment by LiveChief** [comment]
@doublesixwings why not give it a try and try digital ocean their speeds are pretty good for shit like this.

https://m.do.co/c/4fdeeb3264a8

**Comment by doublesixwings** [comment]
@LiveChief As I said before, I just don't have a driving fore to change frome simple-obfs to v2ray-plugin, the first reason is I have a good experience at using simple-obfs, the second reason is I just don't get the superiority of v2ray-plugin as you said. Sorry for disturbance!

**Comment by LiveChief** [comment]
@doublesixwings okay, well i am guessing you will change sooner or later.

**Comment by dimqua** [comment]
> So for better security, I think it's a good choice to build a real website that pointed by the domain name, am I right?

It's probably depends on where you live. Theoretically, the DPI is able to check if you connecting to a real website (web page) or not. IIRC, Russian censors used this technique in the past to detect Telegram proxy servers.

**Comment by batatablhm** [comment]
also for the plugin program, put the .exe name

**Comment by hiddify** [comment]
simple-obfs is very good to avoid detection 
Currently, many CDN providers are slow down in Iran and even the internal one can be easily detected because they decrypt the packet and can identify its usage for shadowsocks.

The best option is simple-obfs, which create a fakedns so we can easily mask google.com and no one can detect it
