### ISSUE TITLE
the configuration is right on windows？

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/v2ray-plugin#34]
Hello All,

The configuration is right？

![123](https://user-images.githubusercontent.com/21324835/52161931-7607fc80-2707-11e9-9c19-0fb0c304f16f.PNG)

**Comment by malikshi** [comment]
> Hello All,
> 
> The configuration is right？
> 
> ![123](https://user-images.githubusercontent.com/21324835/52161931-7607fc80-2707-11e9-9c19-0fb0c304f16f.PNG)

like this, I just find out then answer your question LUL
![screenshot_697](https://user-images.githubusercontent.com/9080737/52229308-326be900-28e7-11e9-87b7-04496494cf3b.png)

**Comment by Mygod** [comment]
Run latest version.
