### ISSUE TITLE
Any way for performance optimization ?

### ISSUE THREAD

**Issue by Old-Pussy** [shadowsocks/v2ray-plugin#36]
My router is WNDR4300.

![CPU usage is too high](https://i.loli.net/2019/02/05/5c597887b40d8.png)

**Comment by LiveChief** [comment]
Explain your connection setup

**Comment by Old-Pussy** [comment]
> Explain your connection setup

I build with `env GOOS=linux GOARCH=mips GOMIPS=softfloat`
My `pluin-opts` is `"tls;path=/wsray;host=mydomain.me"` .
When I input it into luci-app-shadowsocks , it will cost one CPU core of my router.But It doesn't work.
When I input it through SSH,it will cost all the 4 CPU cores.And it will have a 2~3Mbps connection speed.
I use the same opts on my Android phone and it works fine, nearly 20Mbps.

**Comment by madeye** [comment]
Remove tls option and try again.

**Comment by Old-Pussy** [comment]
> Remove tls option and try again.

After remove tls option, the CPU usage decreased to about 60% .But the speed is still slow.My server is at native now and the desirable speed should be 50Mbps.
![speedtest.jpg](https://i.loli.net/2019/02/06/5c5aaf712cc97.png)

**Comment by LiveChief** [comment]
Use it with CDN

**Comment by chenhw2** [comment]
Need to consider the CPU performance, with `tls`, speed on `x86` platform can be up to 30M/s(full vps network), but speed on `ar71xx` platform(QCA9558) can be only up to 21M/s.
