### ISSUE TITLE
Building error: `undefined: net.ListenConfig`

### ISSUE THREAD

**Issue by shenfei** [shadowsocks/v2ray-plugin#37]
Hi,

I got the following error in an `ubuntu:18.04` container.

```
root@fdfe47b68c1c:/v2ray-plugin# go get
go get: no install location for directory /v2ray-plugin outside GOPATH
        For more details see: 'go help gopath'
root@fdfe47b68c1c:/v2ray-plugin# go build
# v2ray.com/core/common/net
/root/go/src/v2ray.com/core/common/net/system.go:11:21: undefined: net.ListenConfig
```

Before that, I only run `apt-get install shadowsocks-libev golang-go git` and clone the `v2ray-plugin`.

Any ideas how to fix this? Thanks.

p.s. Maybe we need a more detailed install readme. It'll be very helpful for someone who have zero experience in golang (I refer to https://github.com/shadowsocks/v2ray-plugin/issues/4 to figure out I have to run `go get` first 🤦‍♂️ ).

**Comment by LiveChief** [comment]
$10 and I'll set it up for u, or

https://gist.github.com/LiveChief/cffe5435e113274f73c9e8f9706b68b2
