### ISSUE TITLE
ANDROID MODE VPN SERVICE ERROR

### ISSUE THREAD

**Issue by malikshi** [shadowsocks/v2ray-plugin#38]
I don't know should be I am posting there or in v2ray-android. But here the error 
Mode PROXY only
![screenshot_2019-02-06-18-17-41-985_com github shadowsocks](https://user-images.githubusercontent.com/9080737/52338140-25144300-2a3c-11e9-8ea0-6d14303f7b8e.png)
Work normally, but VPN MODE not working it's no internet access.
![screenshot_2019-02-06-18-18-16-796_com github shadowsocks](https://user-images.githubusercontent.com/9080737/52338226-6147a380-2a3c-11e9-8061-34f74b182c66.png)
Here my setting
![screenshot_2019-02-06-18-24-28-210_com github shadowsocks](https://user-images.githubusercontent.com/9080737/52338349-bd122c80-2a3c-11e9-828c-9cd2b0f1b391.png)

**Comment by LiveChief** [comment]
Your server config and cloudflare config aren't setup properly...

**Comment by malikshi** [comment]
@LiveChief sent me your screenshots please

**Comment by LiveChief** [comment]
dude your the one asking for help.


share yours and ill tell u what your doing wrong.

**Comment by malikshi** [comment]
> dude your the one asking for help.
> 
> share yours and ill tell u what your doing wrong.

sorry, this my setting can you check it?
![screenshot_704](https://user-images.githubusercontent.com/9080737/52353081-70404d00-2a60-11e9-897b-65f650513e89.png)

**Comment by LiveChief** [comment]
go to SSL and set it to flexible.

**Comment by malikshi** [comment]
still won't pass udp connection,
![screenshot_705](https://user-images.githubusercontent.com/9080737/52356655-33c41f80-2a67-11e9-8164-f3e9abd7bf3d.png)

**Comment by LiveChief** [comment]
Dude it's TCP only via cloudflare..

**Comment by LiveChief** [comment]
Install Google BBR so it's as fast as UDP

**Comment by LiveChief** [comment]
What error are u getting??

**Comment by malikshi** [comment]
> Dude it's TCP only via cloudflare..
> 
> Install Google BBR so it's as fast as UDP
> 
> What error are u getting??

i see, thank a lot sir,

**Comment by LiveChief** [comment]
@malikshi if u wanna close the issue feel free.
