### ISSUE TITLE
No debian prebuilt package

### ISSUE THREAD

**Issue by ghmia** [shadowsocks/v2ray-plugin#39]
As title

**Comment by malikshi** [comment]
Why not using Linux from released files

**Comment by ghmia** [comment]
How so?

**Comment by qhdityq** [comment]
Not sure below steps are correct or not, but I used in my setup, for your reference
1. Download the file which applicable with your platform from the release
2. Extract the file
3. Rename the file to v2ray-plugin, and move the file to the folder which is the same as your shadowsocks execute  file
4. follow the README to configure your server and client

**Comment by ghmia** [comment]
Someone made this request

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922360
