### ISSUE TITLE
please fix route in Android apps

### ISSUE THREAD

**Issue by malikshi** [shadowsocks/v2ray-plugin#42]
Shadowsocks v2ray plugin
Service MODE VPN can't access internet even testing connection.
Service MODE PROXY ONLY can test and access internet.
I'm using ips range from CF.

**Comment by LiveChief** [comment]
its working perfectly, something wrong with your device.

**Comment by denoza** [comment]
Same here, working fine for me

**Comment by malikshi** [comment]
Yea. I do need reconfigure I think. -_-
