### ISSUE TITLE
MT7621 (mipsel_24kc) run error

### ISSUE THREAD

**Issue by TienYow** [shadowsocks/v2ray-plugin#44]
./v2ray-plugin_linux_mips: line 1: syntax error: unexpected "("

**Comment by chenhw2** [comment]
try: https://github.com/chenhw2/openwrt-v2ray-plugin/releases/tag/trunk

**Comment by jsjhzw** [comment]
我安装 了这个包，但是用了后 透明代理无法运行，并且网都上不了了

**Comment by Mygod** [comment]
Contributions are welcome.
