### ISSUE TITLE
How to use this with shadowrocket?

### ISSUE THREAD

**Issue by garveen** [shadowsocks/v2ray-plugin#45]
I've try all settings in shadowrocket but none of them had effects.

**Comment by hybtoy** [comment]
Not supported by Shadowrocket yet.
You can use pure vmess protocol instead.

**Comment by hadifarnoud** [comment]
@hybtoy how can I use pure vmess on shadowrocket? I failed to do that

**Comment by hybtoy** [comment]
@hadifarnoud 
https://github.com/Jrohy/multi-v2ray
https://github.com/FunctionClub/V2ray.Fun
https://github.com/233boy/v2ray/tree/master
Install the server and add provided link to Shadowrocket

**Comment by hadifarnoud** [comment]
This is not an invalid request @mygod. Please re-open it

**Comment by GeonChen** [comment]
ws+tls config like this：
![配置](https://user-images.githubusercontent.com/43988989/65042277-16571c80-d98b-11e9-9815-aaafe5b1b149.png)
