### ISSUE TITLE
Can't start service via systemctl 

### ISSUE THREAD

**Issue by Eintler** [shadowsocks/v2ray-plugin#46]
json
{
    "server":"0.0.0.0",
    "server_port":111,
    "local_port":1080,
    "password":"*",
    "timeout":60,
    "method":"aes-256-gcm",
    "plugin":"/usr/bin/v2ray-plugin",
    "plugin_opts":"server",
    "fast_open":true,
    "mode": "tcp_and_udp"
}

error message via systemctl start shadowsocks-libev
failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 111 > v2ray.com/core/transport/internet

I am sure the port 111 is not occupied via netstat

However it starts well via 
ss-server -c /etc/shadowsocks-libev/config.json -p 111 --plugin /usr/bin/v2ray-plugin --plugin-opts "server"

Anything wrong?

Thanks in advance ;)

**Comment by bigbighill** [comment]
setcap cap_net_bind_service+ep /usr/bin/v2ray-plugin 

 setcap cap_net_bind_service+ep /usr/bin/ss-server

**Comment by Eintler** [comment]
@bigbighill Thank you so much :)

**Comment by Eintler** [comment]
Feb 16 10:48:00 ubuntu ss-server[2828]: 2019/02/16 10:48:00 A unified platform for anti-censorship.
Feb 16 10:48:00 ubuntu ss-server[2828]: 2019/02/16 10:48:00 No TLS cert specified, trying /nonexistent/.acme.sh/domain/fullchain.cer
Feb 16 10:48:00 ubuntu ss-server[2828]: 2019/02/16 10:48:00 main: failed to parse config > main: failed to read cert > open /nonexistent/.acme.sh/domain/fullchain.cer: no such file or directory
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 ERROR: plugin service exit unexpectedly
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 INFO: using tcp fast open
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 INFO: plugin "/usr/bin/v2ray-plugin" enabled
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 INFO: UDP relay enabled
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 INFO: initializing ciphers... aes-256-gcm
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 INFO: tcp server listening at 127.0.0.1:32817
Feb 16 10:48:00 ubuntu ss-server[2828]:  2019-02-16 10:48:00 INFO: udp server listening at 0.0.0.0:111

@bigbighill  
Another issue ,error happens via systemctl start shadowsocks-libev,however it is ok via ss-server -c /etc/shadowsocks-libev/config.json -p 111 --plugin /usr/bin/v2ray-plugin --plugin-opts "server;tls;host=domain"
Thanks

**Comment by bigbighill** [comment]
1、
curl  https://get.acme.sh | sh
sudo apt-get -y install socat
sudo ~/.acme.sh/acme.sh --issue -d mydomain.me --standalone -k 4096

https://github.com/Neilpang/acme.sh/blob/master/README.md

2、 

{
    "server":"0.0.0.0",
    "server_port":111,
    "password":"PASSWORD",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "nameserver": "8.8.8.8",
    "fast_open":true,
    "reuse_port":true,
    "no_delay":true,
    "mode":"tcp_only"
    "plugin":"v2ray-plugin", 
    "plugin_opts":"server;tls;host=xxxx .com;cert=/etc/shadowsocks-libev/xxxx.com/fullchain.cer;key=/etc/shadowsocks-libev/xxxx.com/xxxx.com.key"
 }

**Comment by Eintler** [comment]
systemctl start shadowsocks-libev
systemctl status shadowsocks-libev

shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2019-02-18 03:54:21 EST; 6min ago
     Docs: man:shadowsocks-libev(8)
  Process: 424 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 424 (code=exited, status=0/SUCCESS)

Feb 18 03:54:21 ubuntu systemd[1]: Started Shadowsocks-libev Default Server Service.

cat /var/log/syslog |grep ss-server

Feb 18 03:41:11 ubuntu ss-server[704]: sh: 1: exec: /root/v2ray-plugin/v2ray-plugin: Permission denied
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 ERROR: plugin service exit unexpectedly
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: using tcp fast open
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: plugin "/root/v2ray-plugin/v2ray-plugin" enabled
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: UDP relay enabled
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: enable TCP no-delay
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: initializing ciphers... aes-256-gcm
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: tcp server listening at 127.0.0.1:54489
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: tcp port reuse enabled
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: udp server listening at 0.0.0.0:111
Feb 18 03:41:11 ubuntu ss-server[704]:  2019-02-18 03:41:11 INFO: udp port reuse enabled


-rwxr-xr-x 1 root root 12506671 Feb 18 03:39 v2ray-plugin
the first and second solution have been utilized
@bigbighill 
Thanks

**Comment by bigbighill** [comment]
{
"server":"0.0.0.0",
"server_port":111,
"password":"PASSWORD",
"timeout":300,
### "user":"nobody", (del)
"method":"aes-256-gcm",
"nameserver": "8.8.8.8",
"fast_open":true,
"reuse_port":true,
"no_delay":true,
"mode":"tcp_only"
"plugin":"v2ray-plugin",
"plugin_opts":"server;tls;host=xxxx .com;cert=/etc/shadowsocks-libev/xxxx.com/fullchain.cer;key=/etc/shadowsocks-libev/xxxx.com/xxxx.com.key"
}

**Comment by Eintler** [comment]
{
      "server":"0.0.0.0",
       "server_port":111,
       "nameserver": "8.8.8.8",
       "password":"password",
       "timeout":60,
       "method":"aes-256-gcm",
       "plugin":"v2ray-plugin",
       "plugin_opts":"server;tls;host=*.com;cert=/etc/shadowsocks-libev/*.com/fullchain.cer;key=/etc/shadowsocks-libev/*.com/*.com.key",
      "mode": "tcp_only",
      "reuse_port":true,
      "no_delay":true
  }

cat /var/log/syslog |grep ss-server

root@ubuntu:~# cat /var/log/syslog |grep ss-server
Feb 19 08:52:06 ubuntu ss-server[2311]: 2019/02/19 08:52:06 V2Ray 4.16 (Po) Custom
Feb 19 08:52:06 ubuntu ss-server[2311]: 2019/02/19 08:52:06 A unified platform for anti-censorship.
Feb 19 08:52:06 ubuntu ss-server[2311]: 2019/02/19 08:52:06 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 111 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:111 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:111 > listen tcp 0.0.0.0:111: bind: permission denied
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 ERROR: plugin service exit unexpectedly
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: plugin "v2ray-plugin" enabled
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: UDP relay enabled
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: enable TCP no-delay
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: initializing ciphers... aes-256-gcm
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: using nameserver: 8.8.8.8
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: tcp server listening at 127.0.0.1:36369
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: tcp port reuse enabled
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: udp server listening at 0.0.0.0:521
Feb 19 08:52:06 ubuntu ss-server[2311]:  2019-02-19 08:52:06 INFO: udp port reuse enabled

@bigbighill 
Thanks as always :)

**Comment by bigbighill** [comment]
setcap cap_net_bind_service+ep /usr/bin/v2ray-plugin

**Comment by Eintler** [comment]
Finally works.Thank you so much @bigbighill
