### ISSUE TITLE
Can't build with go build.

### ISSUE THREAD

**Issue by gscfwid** [shadowsocks/v2ray-plugin#47]
On my centos 6, after installing go, with go build, I got following message:
go: finding github.com/miekg/dns v1.1.4
go: finding github.com/golang/protobuf v1.2.1-0.20190205222052-c823c79ea157
go: github.com/miekg/dns@v1.1.4: unknown revision v1.1.4
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
go: finding golang.org/x/crypto v0.0.0-20190211182817-74369b46fc67
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding v2ray.com/core v4.16.0+incompatible
go: finding google.golang.org/genproto v0.0.0-20190215211957-bd968387e4aa
go: v2ray.com/core@v4.16.0+incompatible: unknown revision v4.16.0
go: github.com/golang/protobuf@v1.2.1-0.20190205222052-c823c79ea157: unknown revision c823c79ea15                  7
go: google.golang.org/genproto@v0.0.0-20190215211957-bd968387e4aa: unknown revision bd968387e4aa
go: golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4: unknown revision 37e7f081c4d4
go: golang.org/x/text@v0.3.1-0.20180807135948-17ff2d5776d2: unknown revision 17ff2d5776d2
go: golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a: unknown revision d0b11bdaac8a
go: golang.org/x/crypto@v0.0.0-20190211182817-74369b46fc67: unknown revision 74369b46fc67
go: golang.org/x/net@v0.0.0-20190213061140-3a22650c66bd: unknown revision 3a22650c66bd
go: error loading module requirements
[root@v55one v2ray-plugin]# go get github.com/golang/protobuf
go: finding github.com/miekg/dns v1.1.4
go: finding github.com/golang/protobuf v1.2.1-0.20190205222052-c823c79ea157
go: github.com/miekg/dns@v1.1.4: unknown revision v1.1.4
go: finding v2ray.com/core v4.16.0+incompatible
go: v2ray.com/core@v4.16.0+incompatible: unknown revision v4.16.0
go: finding golang.org/x/crypto v0.0.0-20190211182817-74369b46fc67
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding google.golang.org/genproto v0.0.0-20190215211957-bd968387e4aa
go: github.com/golang/protobuf@v1.2.1-0.20190205222052-c823c79ea157: unknown revision c823c79ea157
go: google.golang.org/genproto@v0.0.0-20190215211957-bd968387e4aa: unknown revision bd968387e4aa
go: golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4: unknown revision 37e7f081c4d4
go: golang.org/x/text@v0.3.1-0.20180807135948-17ff2d5776d2: unknown revision 17ff2d5776d2
go: golang.org/x/crypto@v0.0.0-20190211182817-74369b46fc67: unknown revision 74369b46fc67
go: golang.org/x/net@v0.0.0-20190213061140-3a22650c66bd: unknown revision 3a22650c66bd
go: golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a: unknown revision d0b11bdaac8a
go: error loading module requirements

What is the problem?

**Comment by jibon57** [comment]
Run `go get` first then `go build`

**Comment by lcjzfx** [comment]
./build-release.sh
I use this after "cd v2ray-plugin-1.1.0",but it show something wrong ,
fatal: Not a git repository (or any of the parent directories): .git
mkdir: cannot create directory ‘bin’: File exists
env: ‘go’: No such file or directory
tar: v2ray-plugin_linux_amd64: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-linux-amd64-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_linux_386: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-linux-386-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_darwin_amd64: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-darwin-amd64-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_darwin_386: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-darwin-386-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_windows_amd64.exe: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-windows-amd64-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_windows_386.exe: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-windows-386-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_freebsd_amd64: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-freebsd-amd64-.tar.gz
env: ‘go’: No such file or directory
tar: v2ray-plugin_freebsd_386: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cc5f1c3a37a15bc170a103aee667a7ff1fd2dba7  bin/v2ray-plugin-freebsd-386-.tar.gz
env: ‘go’: No such file or directory
env: ‘go’: No such file or directory
Have you fix it ?can you help me ?thanks.

**Comment by Youngmanhai** [comment]
I met a similar problem after I run "go build" in commndline. I got this:
  ~/VPS/v2ray-plugin$ go build

main.go:15:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.6/src/github.com/golang/protobuf/proto (from $GOROOT)
	($GOPATH not set)
main.go:17:2: cannot find package "v2ray.com/core" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core (from $GOROOT)
	($GOPATH not set)
main.go:19:2: cannot find package "v2ray.com/core/app/dispatcher" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/dispatcher (from $GOROOT)
	($GOPATH not set)
main.go:36:2: cannot find package "v2ray.com/core/app/log" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/log (from $GOROOT)
	($GOPATH not set)
main.go:20:2: cannot find package "v2ray.com/core/app/proxyman" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman (from $GOROOT)
	($GOPATH not set)
main.go:21:2: cannot find package "v2ray.com/core/app/proxyman/inbound" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman/inbound (from $GOROOT)
	($GOPATH not set)
main.go:22:2: cannot find package "v2ray.com/core/app/proxyman/outbound" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman/outbound (from $GOROOT)
	($GOPATH not set)
errors.generated.go:3:8: cannot find package "v2ray.com/core/common/errors" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/errors (from $GOROOT)
	($GOPATH not set)
main.go:37:2: cannot find package "v2ray.com/core/common/log" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/log (from $GOROOT)
	($GOPATH not set)
main.go:24:2: cannot find package "v2ray.com/core/common/net" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/net (from $GOROOT)
	($GOPATH not set)
main.go:39:2: cannot find package "v2ray.com/core/common/platform/filesystem" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/platform/filesystem (from $GOROOT)
	($GOPATH not set)
main.go:25:2: cannot find package "v2ray.com/core/common/protocol" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/protocol (from $GOROOT)
	($GOPATH not set)
main.go:26:2: cannot find package "v2ray.com/core/common/serial" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/serial (from $GOROOT)
	($GOPATH not set)
main.go:28:2: cannot find package "v2ray.com/core/proxy/dokodemo" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/proxy/dokodemo (from $GOROOT)
	($GOPATH not set)
main.go:29:2: cannot find package "v2ray.com/core/proxy/freedom" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/proxy/freedom (from $GOROOT)
	($GOPATH not set)
main.go:31:2: cannot find package "v2ray.com/core/transport/internet" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet (from $GOROOT)
	($GOPATH not set)
main.go:32:2: cannot find package "v2ray.com/core/transport/internet/quic" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/quic (from $GOROOT)
	($GOPATH not set)
main.go:33:2: cannot find package "v2ray.com/core/transport/internet/tls" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/tls (from $GOROOT)
	($GOPATH not set)
main.go:34:2: cannot find package "v2ray.com/core/transport/internet/websocket" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/websocket (from $GOROOT)
	($GOPATH not set)
younghai@younghai-GL553VD:~/VPS/v2ray-plugin$ ./build-release.sh 
main.go:15:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.6/src/github.com/golang/protobuf/proto (from $GOROOT)
	($GOPATH not set)
main.go:17:2: cannot find package "v2ray.com/core" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core (from $GOROOT)
	($GOPATH not set)
main.go:19:2: cannot find package "v2ray.com/core/app/dispatcher" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/dispatcher (from $GOROOT)
	($GOPATH not set)
main.go:36:2: cannot find package "v2ray.com/core/app/log" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/log (from $GOROOT)
	($GOPATH not set)
main.go:20:2: cannot find package "v2ray.com/core/app/proxyman" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman (from $GOROOT)
	($GOPATH not set)
main.go:21:2: cannot find package "v2ray.com/core/app/proxyman/inbound" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman/inbound (from $GOROOT)
	($GOPATH not set)
main.go:22:2: cannot find package "v2ray.com/core/app/proxyman/outbound" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman/outbound (from $GOROOT)
	($GOPATH not set)
errors.generated.go:3:8: cannot find package "v2ray.com/core/common/errors" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/errors (from $GOROOT)
	($GOPATH not set)
main.go:37:2: cannot find package "v2ray.com/core/common/log" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/log (from $GOROOT)
	($GOPATH not set)
main.go:24:2: cannot find package "v2ray.com/core/common/net" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/net (from $GOROOT)
	($GOPATH not set)
main.go:39:2: cannot find package "v2ray.com/core/common/platform/filesystem" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/platform/filesystem (from $GOROOT)
	($GOPATH not set)
main.go:25:2: cannot find package "v2ray.com/core/common/protocol" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/protocol (from $GOROOT)
	($GOPATH not set)
main.go:26:2: cannot find package "v2ray.com/core/common/serial" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/serial (from $GOROOT)
	($GOPATH not set)
main.go:28:2: cannot find package "v2ray.com/core/proxy/dokodemo" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/proxy/dokodemo (from $GOROOT)
	($GOPATH not set)
main.go:29:2: cannot find package "v2ray.com/core/proxy/freedom" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/proxy/freedom (from $GOROOT)
	($GOPATH not set)
main.go:31:2: cannot find package "v2ray.com/core/transport/internet" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet (from $GOROOT)
	($GOPATH not set)
main.go:32:2: cannot find package "v2ray.com/core/transport/internet/quic" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/quic (from $GOROOT)
	($GOPATH not set)
main.go:33:2: cannot find package "v2ray.com/core/transport/internet/tls" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/tls (from $GOROOT)
	($GOPATH not set)
main.go:34:2: cannot find package "v2ray.com/core/transport/internet/websocket" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/websocket (from $GOROOT)
	($GOPATH not set)
tar: v2ray-plugin_linux_amd64：无法 stat: 没有那个文件或目录
tar: 由于前次错误，将以上次的错误状态退出
c3cf8e0351096a2dd334c6cd22323a9e6c04d96a  bin/v2ray-plugin-linux-amd64-v1.1.0-5-ga3b8add.tar.gz
main.go:15:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.6/src/github.com/golang/protobuf/proto (from $GOROOT)
	($GOPATH not set)
main.go:17:2: cannot find package "v2ray.com/core" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core (from $GOROOT)
	($GOPATH not set)
main.go:19:2: cannot find package "v2ray.com/core/app/dispatcher" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/dispatcher (from $GOROOT)
	($GOPATH not set)
main.go:36:2: cannot find package "v2ray.com/core/app/log" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/log (from $GOROOT)
	($GOPATH not set)
main.go:20:2: cannot find package "v2ray.com/core/app/proxyman" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman (from $GOROOT)
	($GOPATH not set)
main.go:21:2: cannot find package "v2ray.com/core/app/proxyman/inbound" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman/inbound (from $GOROOT)
	($GOPATH not set)
main.go:22:2: cannot find package "v2ray.com/core/app/proxyman/outbound" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/app/proxyman/outbound (from $GOROOT)
	($GOPATH not set)
errors.generated.go:3:8: cannot find package "v2ray.com/core/common/errors" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/errors (from $GOROOT)
	($GOPATH not set)
main.go:37:2: cannot find package "v2ray.com/core/common/log" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/log (from $GOROOT)
	($GOPATH not set)
main.go:24:2: cannot find package "v2ray.com/core/common/net" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/net (from $GOROOT)
	($GOPATH not set)
main.go:39:2: cannot find package "v2ray.com/core/common/platform/filesystem" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/platform/filesystem (from $GOROOT)
	($GOPATH not set)
main.go:25:2: cannot find package "v2ray.com/core/common/protocol" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/protocol (from $GOROOT)
	($GOPATH not set)
main.go:26:2: cannot find package "v2ray.com/core/common/serial" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/common/serial (from $GOROOT)
	($GOPATH not set)
main.go:28:2: cannot find package "v2ray.com/core/proxy/dokodemo" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/proxy/dokodemo (from $GOROOT)
	($GOPATH not set)
main.go:29:2: cannot find package "v2ray.com/core/proxy/freedom" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/proxy/freedom (from $GOROOT)
	($GOPATH not set)
main.go:31:2: cannot find package "v2ray.com/core/transport/internet" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet (from $GOROOT)
	($GOPATH not set)
main.go:32:2: cannot find package "v2ray.com/core/transport/internet/quic" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/quic (from $GOROOT)
	($GOPATH not set)
main.go:33:2: cannot find package "v2ray.com/core/transport/internet/tls" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/tls (from $GOROOT)
	($GOPATH not set)
main.go:34:2: cannot find package "v2ray.com/core/transport/internet/websocket" in any of:
	/usr/lib/go-1.6/src/v2ray.com/core/transport/internet/websocket (from $GOROOT)
	($GOPATH not set)
tar: v2ray-plugin_linux_386：cannot stat: No such file or directory

Any ideas about "$GOPATH not set" ? thanks

**Comment by ugist** [comment]
searched on copr and found this, try it
https://copr.fedorainfracloud.org/coprs/registe/others/
