### ISSUE TITLE
How to use with v2ray-core client?

### ISSUE THREAD

**Issue by skiyer** [shadowsocks/v2ray-plugin#49]
I've set up a v2ray-plugin server and it worked well when using ss-local with plugin-opts `"path=/path;host=somehost;tls"`.

Now I want to use v2ray-core as the client, but it comes up with following errors:
```
v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > v2ray.com/core/common/mux: invalid metalen 53052
```

This is my outbound setting:
```
{
  "protocol": "shadowsocks",
  "settings": {
    "servers": [
      {
        "address": "somehost",
        "port": 443,
        "method": "chacha20-ietf-poly1305",
        "password": "password"
      }
    ]
  },
  "streamSettings": {
    "network": "ws",
    "security": "tls",
    "wsSettings": {
      "path": "/path"
    }
  },
  "mux": {
    "enabled": true,
    "concurrency": 1
  }
}
```

**Comment by bigbighill** [comment]
https://gist.github.com/eycorsican/4ac150fd0d91c2ae4de0b2959ceb4c52

**Comment by bigbighill** [comment]
{
    "log": {
			"access": "",
			"error": "",
			"loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 1080,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": false
            }
        }
    ],
    "outbounds": [
        {
            "tag": "protocol_layer",
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "method": "chacha20-ietf-poly1305",
                        "port": 443, 
                        "password": "password",
                        "address": "domain.com"
                    }
                ]
            },
            "proxySettings": {
                "tag": "transport_layer"
            }
        },
        {
            "tag": "transport_layer",
            "protocol": "freedom",
            "settings": {
                "redirect": "domain:443"
            },
            "streamSettings": {
                "wsSettings": {
                    "path": "/path",
					"headers": {
					"Host": "domain.com"
					}
                },
                "network": "ws",
                "security": "tls"
            },
            "mux": {
                "enabled": true
            }
        }
    ],
     "dns": {
		"servers": [
			"208.67.222.222",
			"1.1.1.1"
		]
	},

 "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rule": [
            {
				"type": "field",
				"network": "tcp,udp",
				"outboundTag": "protocol_layer"
			},
			{
				"type": "field",
				"port": null,
				"outboundTag": "direct",
				"ip": [
					"geoip:private"
				],
				"domain": null
			},
			{
				"type": "field",
				"port": null,
				"outboundTag": "direct",
				"ip": [
					"geoip:cn"
				],
				"domain": null
			},
			{
				"type": "field",
				"port": null,
				"outboundTag": "direct",
				"ip": null,
				"domain": [
					"geosite:cn"
				]
			}
        ]
    }
}

**Comment by skiyer** [comment]
> https://gist.github.com/eycorsican/4ac150fd0d91c2ae4de0b2959ceb4c52

It works after I adapt it to `tls` version.

**Comment by hadifarnoud** [comment]
it didn't work for me
```
[v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://****:8530/):  > tls: first record does not look like a TLS handshake] > v2ray.com/core/common/retry: all retry attempts failed
```

my config:
```
{
  "log": {
    "error": "",
    "loglevel": "warning",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "ip": "",
        "userLevel": 0,
        "timeout": 0,
        "udp": true,
        "auth": "noauth"
      },
      "port": "1080"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "protocol": "shadowsocks",
      "streamSettings": {
        "wsSettings": {
          "path": "/",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "protocol_layer",
      "settings": {
        "servers": [
          {
            "port": 8530,
            "method": "chacha20-ietf-poly1305",
            "password": "****",
            "address": "*****",
            "level": 0,
            "email": "",
            "ota": false
          }
        ]
      }
    },
    {
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "protocol": "freedom",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/",
          "headers": {
            "host": ""
          }
        },
        "security": "tls"
      },
      "tag": "transport_layer",
      "settings": {
        "domainStrategy": "",
        "redirect": "****:8530",
        "userLevel": 0
      }
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": []
    }
  },
  "transport": {}
}
```

**Comment by hadifarnoud** [comment]
my shadowsocks installation says this is the config:
```
Server: ****
    Port: 8530
    Password: ****
    Encryption Method: chacha20-ietf-poly1305
    Plugin: v2ray-plugin
    Plugin_Options: host=github.com
```

**Comment by skiyer** [comment]
@hadifarnoud 
> ```
>     Plugin_Options: host=github.com
> ```
My options are `server;path=/ss;host=myhost.com`.

You should only use your own host. Obviously you can't sign the certificates of `github.com`, because you don't have the right key.
