### ISSUE TITLE
mipsle not work properly at padavan Router

### ISSUE THREAD

**Issue by xianren78** [shadowsocks/v2ray-plugin#53]
{
"server":"mydomain.com",
"server_port":443,
"local_address": "0.0.0.0",
"local_port":9950,
"password":"pass",
"timeout":600,
"method":"aes-128-gcm",
"plugin":"/opt/bin/v2ray-plugin",
"plugin_opts":"host=mydomain.com;tls;loglevel=debug"
}

with error on Padavan Router as below, seems to related with ssl cert, but all work on my android and windows. Both Heroku deployment and Self-managed Domain signed by Let's Encrypt has this problem.

2019/02/27 02:26:38 [Info] failed to handler mux client connection > v2ray.com/core/proxy/freedom: failed to open connection to tcp:mydomain.com:443 > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mydomain.com.com/):  > x509: certificate signed by unknown authority] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by qgtxqj** [comment]
finally after export root certs from chrome in Base64, and use cert parameter to show the path in config file. and it works well on my Padavan Router.
"plugin_opts":"host=mydomain.com;tls;loglevel=debug;cert=/opt/leroot.cer"

**Comment by qgtxqj** [comment]
I think this problem might be solved through https://github.com/shadowsocks/v2ray-plugin/pull/50

**Comment by rampageX** [comment]
I think it's golang SSL certificate file seach path on Padawan problem, solved:

1. install Entware;
2. install ca-files;
```
opkg update
opkg upgrade
opkg install ca-bundle
opkg install ca-certificates
```
3. export ca-path(These are default installed parh, you need find where pandawan install these file by youself then replace path...  )
```
export SSL_CERT_FILE=/opt/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/opt/etc/ssl/certs
```

Or easy-way: 

1. Download https://curl.haxx.se/ca/cacert.pem to your router, like /opt/etc/cacert.pem;
2. `export SSL_CERT_FILE=/opt/etc/cacert.pem`.

These will work too.

And these will solve all `x509: certificate signed by unknown authority` problem on your Padawan when using any golang&TLS program.

**Comment by qgtxqj** [comment]
tks, it is OK now
