### ISSUE TITLE
Split v2ray-plugin-linux-arm-v1.1.0.tar.gz to three file.

### ISSUE THREAD

**Issue by zw963** [shadowsocks/v2ray-plugin#58]
Because github redirect assert url to AWS, which cause download file is slow.

And, this file size is 8.54 MB, which bigger and need quite long time when
network is not good, for performance, if we can split this file to three file 
(arm5, arm6, arm7), will got more ideal download time.

Thanks

**Comment by LiveChief** [comment]
No

**Comment by colibris79** [comment]
@LiveChief , definitely you don't live in China. 
@zw963 , good suggestion for people who are behind the GFW

**Comment by LiveChief** [comment]
@colibris79 NYC, United States

**Comment by Mygod** [comment]
yr
