### ISSUE TITLE
Asus AC68U with Merlin 384.9 fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by wangxin6** [shadowsocks/v2ray-plugin#59]
admin@RT-AC68U:/tmp/mnt/sda1/entware/etc/init.d# ss-redir -c /opt/etc/shadowsocks.json --plugin /opt/etc/v2ray-plugin_linux_arm5 -vvv
 2019-03-02 18:10:42 INFO: plugin "/opt/etc/v2ray-plugin_linux_arm5" enabled
 2019-03-02 18:10:42 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-02 18:10:42 INFO: listening at 192.168.1.1:1080
 2019-03-02 18:10:42 INFO: running from root user
2019/03/02 18:10:42 V2Ray 4.13 (Po) Custom
2019/03/02 18:10:42 A unified platform for anti-censorship.
2019/03/02 18:10:42 [Warning] v2ray.com/core: V2Ray 4.13 started
 2019-03-02 18:10:44 INFO: redir to 172.217.27.142:443, len=530, recv=530
 2019-03-02 18:10:45 INFO: redir to 172.217.27.142:443, len=530, recv=530
 2019-03-02 18:10:45 INFO: redir to 172.217.27.142:443, len=51, recv=51
 2019-03-02 18:10:45 INFO: redir to 172.217.27.142:443, len=93, recv=93
.........
 2019-03-02 18:14:24 INFO: redir to 74.125.102.123:443, len=913, recv=913
 2019-03-02 18:14:24 INFO: redir to 216.58.206.238:443, len=1241, recv=1241
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x43b84b, 0x16)
	/home/max/Workspace/go/src/runtime/panic.go:608 +0x5c
runtime.sysMap(0xc00000, 0x400000, 0x797af8)
	/home/max/Workspace/go/src/runtime/mem_linux.go:156 +0xac
runtime.(*linearAlloc).alloc(0x78b8e4, 0x400000, 0x400000, 0x797af8, 0x0)
	/home/max/Workspace/go/src/runtime/malloc.go:1230 +0x94
runtime.(*mheap).sysAlloc(0x78ae20, 0x400000, 0x0, 0x33a0c)
	/home/max/Workspace/go/src/runtime/malloc.go:525 +0x54
runtime.(*mheap).grow(0x78ae20, 0x1, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:920 +0x2c
runtime.(*mheap).allocSpanLocked(0x78ae20, 0x1, 0x797b08, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:848 +0x320
runtime.(*mheap).alloc_m(0x78ae20, 0x1, 0x6, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:692 +0x118
runtime.(*mheap).alloc.func1()
	/home/max/Workspace/go/src/runtime/mheap.go:759 +0x3c
runtime.(*mheap).alloc(0x78ae20, 0x1, 0x10006, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:758 +0x60
runtime.(*mcentral).grow(0x78ba70, 0x0)
	/home/max/Workspace/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x78ba70, 0x0)
	/home/max/Workspace/go/src/runtime/mcentral.go:106 +0x34c
runtime.(*mcache).refill(0x40016000, 0xa24d06)
	/home/max/Workspace/go/src/runtime/mcache.go:122 +0x7c
runtime.(*mcache).nextFree.func1()
	/home/max/Workspace/go/src/runtime/malloc.go:749 +0x24
runtime.systemstack(0x8e03c0)
	/home/max/Workspace/go/src/runtime/asm_arm.s:354 +0x84
runtime.mstart()
	/home/max/Workspace/go/src/runtime/proc.go:1229

goroutine 345 [running]:
runtime.systemstack_switch()
	/home/max/Workspace/go/src/runtime/asm_arm.s:298 +0x4 fp=0xa25698 sp=0xa25694 pc=0x67724
runtime.(*mcache).nextFree(0x40016000, 0xbf7d06, 0xa05e48, 0x704b4, 0xa05e40)
	/home/max/Workspace/go/src/runtime/malloc.go:748 +0xa4 fp=0xa256c4 sp=0xa25698 pc=0x1a254
runtime.mallocgc(0x20, 0x3fa528, 0x942001, 0x2)
	/home/max/Workspace/go/src/runtime/malloc.go:903 +0x768 fp=0xa2572c sp=0xa256c4 pc=0x1ab74
runtime.newobject(0x3fa528, 0x3b3688)
	/home/max/Workspace/go/src/runtime/malloc.go:1032 +0x2c fp=0xa25740 sp=0xa2572c pc=0x1af40
v2ray.com/core/common/buf.New(0x4b23b8)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/buf/buffer.go:202 +0x58 fp=0xa2575c sp=0xa25740 pc=0x175314
v2ray.com/core/common/mux.(*FrameMetadata).Unmarshal(0xa257d0, 0x4b23b8, 0xa05e40, 0x0, 0x0)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/mux/frame.go:101 +0x184 fp=0xa25794 sp=0xa2575c pc=0x2c9c64
v2ray.com/core/common/mux.(*ClientWorker).fetchOutput(0xa05d80)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/mux/client.go:373 +0x9c fp=0xa257e4 sp=0xa25794 pc=0x2c8ea8
runtime.goexit()
	/home/max/Workspace/go/src/runtime/asm_arm.s:867 +0x4 fp=0xa257e4 sp=0xa257e4 pc=0x6946c
created by v2ray.com/core/common/mux.NewClientWorker
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/mux/client.go:189 +0x134

goroutine 1 [chan receive]:
main.main()
	/home/max/Workspace/v2ray-plugin/main.go:356 +0x120

goroutine 4 [syscall]:
os/signal.signal_recv(0x0)
	/home/max/Workspace/go/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/home/max/Workspace/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
	/home/max/Workspace/go/src/os/signal/signal_unix.go:29 +0x30

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x400aefc0, 0x72, 0x0)
	/home/max/Workspace/go/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x890c44, 0x72, 0x85c000, 0x0, 0x0)
	/home/max/Workspace/go/src/internal/poll/fd_poll_runtime.go:85 +0x7c
internal/poll.(*pollDesc).waitRead(0x890c44, 0xffffff00, 0x0, 0x0)
	/home/max/Workspace/go/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Accept(0x890c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/max/Workspace/go/src/internal/poll/fd_unix.go:384 +0x17c
net.(*netFD).accept(0x890c30, 0x82c7a0, 0xc, 0x8010a0)
	/home/max/Worksp42-57877d644e06+incompatible/common/task/task.go:27 +0xa0

goroutine 208 [select]:
v2ray.com/core/transport/pipe.(*pipe).ReadMultiBuffer(0x993b90, 0x2, 0x0, 0x1, 0x9a0780, 0x0)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/transport/pipe/impl.go:89 +0xb8
v2ray.com/core/transport/pipe.(*Reader).ReadMultiBuffer(0x85bd00, 0x9a0780, 0x0, 0x1, 0x0, 0x0)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/transport/pipe/reader.go:16 +0x20
v2ray.com/core/common/buf.copyInternal(0x4b2688, 0x85bd00, 0x4b24f0, 0x9b2000, 0x99a9f0, 0x4b24f0, 0x9b2000)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/buf/copy.go:79 +0x24
v2ray.com/core/common/buf.Copy(0x4b2688, 0x85bd00, 0x4b24f0, 0x9b2000, 0x0, 0x0, 0x0, 0x1, 0x1)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/buf/copy.go:102 +0x84
v2ray.com/core/common/mux.fetchInput(0x4b4c48, 0x9ae4a0, 0x97ffe0, 0x4b26a0, 0x9a0388)
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/mux/client.go:260 +0x454
created by v2ray.com/core/common/mux.(*ClientWorker).Dispatch
	/home/max/go/pkg/mod/v2ray.com/core@v4.12.1-0.20190117145842-57877d644e06+incompatible/common/mux/client.go:300 +0xe8

 2019-03-02 18:14:24 ERROR: plugin service exit unexpectedly

**Comment by wangxin6** [comment]
完整信息可移步gist https://gist.github.com/wangxin6/2d86c9482c8c45d214d0f6cfcf8bf9ac

**Comment by Acris** [comment]
内存不够。尝试启用swap看看？

**Comment by wangxin6** [comment]
请教如何启用swap？

**Comment by Acris** [comment]
@wangxin6 如果是KoolShare的改版梅林，直接在软件中心搜索虚拟内存即可。
如果是原版梅林，可以参考这篇文章：https://mydevtutorials.wordpress.com/2014/01/10/how-to-activate-swap-on-asus-rt-ac68u-router/

**Comment by wangxin6** [comment]
我是用原版的。抽空我试一下。多谢@Acris

**Comment by wangxin6** [comment]
已经设置好swap但是不能解决fatal error: runtime: out of memory的问题。

通过free命令可以看到mem使用量不断在增加，但是swap使用仍然为0.

例如：
admin@RT-AC68U:/tmp/home/root# free
             total       used       free     shared    buffers     cached
Mem:        255700     201880      53820          0        908     118412
-/+ buffers/cache:      82560     173140
Swap:       262140          0     262140
admin@RT-AC68U:/tmp/home/root# free
             total       used       free     shared    buffers     cached
Mem:        255700     201896      53804          0        908     118412
-/+ buffers/cache:      82576     173124
Swap:       262140          0     262140

**Comment by Acris** [comment]
不太清楚内存耗尽后不使用swap的原因。
使用`cat /proc/sys/vm/swappiness`命令查看下是不是默认值60，另外确保下创建并启用swapfile的过程没有问题。

**Comment by qgtxqj** [comment]
更新一下v2ray-plugin试试

**Comment by wangxin6** [comment]
已经更新到v1.1.0。问题依旧。@qgtxqj 

创建和启用swapfile过程没问题。 free命令可以看到swap。@Acris 

> admin@RT-AC68U:/tmp/home/root# free
total        used       free      shared    buffers cached
Mem:   255700 201896   53804    0 908    118412
-/+ buffers/cache: 82576 173124
Swap:   262140  0           262140

**Comment by qgtxqj** [comment]
试试v2ray-plugin_linux_arm7呢？ac68u应该是armv7

**Comment by wangxin6** [comment]
v2ray-plugin_linux_arm7不能正常工作。只有arm5才行。

**Comment by wangxin6** [comment]
确认默认值是60

admin@RT-AC68U:/tmp/home/root# cat /proc/sys/vm/swappiness
60

**Comment by Acris** [comment]
我目前看不出是什么问题了，抱歉😂

**Comment by qgtxqj** [comment]
看看有参考价值没？
https://github.com/shadowsocks/v2ray-plugin/issues/55#issuecomment-468920980

**Comment by Acris** [comment]
@qgtxqj 应该不是，你说的这个问题shadowsocks-libev 3.2.4已经解决了，如果楼主用的是3.2.4就不会存在这个问题，当然还是可以试一下。

**Comment by wangxin6** [comment]
当前entware支持的最新版本如下：
shadowsocks-libev-config (3.2.3-1) 
shadowsocks-libev-ss-redir (3.2.3-1)

**Comment by wangxin6** [comment]
添加参数以后，问题未解决

admin@RT-AC68U:/tmp/mnt/sda1/entware/etc/init.d# ss-redir -c /opt/etc/shadowsocks.json --plugin /opt/etc/v2ray-plugin_linux_arm5 --plugin-opts "loglevel=none" -vvv
 2019-03-05 15:11:31 INFO: plugin "/opt/etc/v2ray-plugin_linux_arm5" enabled
 2019-03-05 15:11:31 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-05 15:11:31 INFO: listening at 192.168.1.1:1080
 2019-03-05 15:11:31 INFO: running from root user
2019/03/05 15:11:32 V2Ray 4.13 (Po) Custom
2019/03/05 15:11:32 A unified platform for anti-censorship.
 2019-03-05 15:11:43 INFO: redir to 216.58.198.196:443, len=517, recv=517
....

 2019-03-05 15:13:32 INFO: redir to 172.217.19.238:443, len=46, recv=46
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x43b84b, 0x16)
	/home/max/Workspace/go/src/runtime/panic.go:608 +0x5c
runtime.sysMap(0xc00000, 0x400000, 0x797af8)
	/home/max/Workspace/go/src/runtime/mem_linux.go:156 +0xac
runtime.(*linearAlloc).alloc(0x78b8e4, 0x400000, 0x400000, 0x797af8, 0x0)
	/home/max/Workspace/go/src/runtime/malloc.go:1230 +0x94
runtime.(*mheap).sysAlloc(0x78ae20, 0x400000, 0x0, 0x33a0c)
	/home/max/Workspace/go/src/runtime/malloc.go:525 +0x54
runtime.(*mheap).grow(0x78ae20, 0x1, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:920 +0x2c
runtime.(*mheap).allocSpanLocked(0x78ae20, 0x1, 0x797b08, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:848 +0x320
runtime.(*mheap).alloc_m(0x78ae20, 0x1, 0x8, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:692 +0x118
runtime.(*mheap).alloc.func1()
	/home/max/Workspace/go/src/runtime/mheap.go:759 +0x3c
runtime.(*mheap).alloc(0x78ae20, 0x1, 0x10008, 0x0)
	/home/max/Workspace/go/src/runtime/mheap.go:758 +0x60
runtime.(*mcentral).grow(0x78baf0, 0x0)
	/home/max/Workspace/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x78baf0, 0x0)
	/home/max/Workspace/go/src/runtime/mcentral.go:106 +0x34c
runtime.(*mcache).refill(0x40096360, 0x8)
	/home/max/Workspace/go/src/runtime/mcache.go:122 +0x7c
runtime.(*mcache).nextFree.func1()
	/home/max/Workspace/go/src/runtime/malloc.go:749 +0x24
runtime.systemstack(0x8fa5a0)
	/home/max/Workspace/go/src/runtime/asm_arm.s:354 +0x84
runtime.mstart()
	/home/max/Workspace/go/src/runtime/proc.go:1229

**Comment by lovemyliwu** [comment]
我是报这错，getpeername: Transport endpoint is not connected

**Comment by wangxin6** [comment]
估计是geoip文件造成的内存溢出。

**Comment by billysingo** [comment]
> 估计是geoip文件造成的内存溢出。

请问后来问题解决了吗？我也有同样的问题现在

**Comment by wangxin6** [comment]
> > 估计是geoip文件造成的内存溢出。
> 
> 请问后来问题解决了吗？我也有同样的问题现在

给你几个解决思路：
1. 使用upx压缩geoip
2. 在U盘创建swap
3. 改用clash https://github.com/KOP-XIAO/Clash-Merlin/wiki
