### ISSUE TITLE
Doesn't support ss-manager

### ISSUE THREAD

**Issue by love1st** [shadowsocks/v2ray-plugin#6]
It seems that this plugin doesn't support ss-manager.

When using ss-server, I can see
_2019/01/15 11:22:59 V2Ray 4.13 (Po) Custom
2019/01/15 11:22:59 A unified platform for anti-censorship.
2019/01/15 11:22:59 [Warning] v2ray.com/core: V2Ray 4.13 started_
in the console.

While if I use ss-manager, there isn't any log info about this plugin presented in the console.

**Comment by mklnz** [comment]
Same here, I'm not sure what other information I can see, this is from syslog:

`Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: plugin "v2ray-plugin" enabled
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: UDP relay enabled
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: initializing ciphers... chacha20-ietf-poly1305
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: tcp port reuse enabled
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: tcp server listening at 127.0.0.1:44159
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: udp port reuse enabled
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: udp server listening at 0.0.0.0:10177
Feb 25 00:34:02 hongkong-test-1 ss-server[20247]: plugin service exit unexpectedly`

**Comment by yujincheng08** [comment]
same here
