### ISSUE TITLE
work on v2ray client,but shadowsocks windows client failed, how can i do?

### ISSUE THREAD

**Issue by c21xdx** [shadowsocks/v2ray-plugin#60]
Hi, i followed  this  https://gist.github.com/eycorsican/4ac150fd0d91c2ae4de0b2959ceb4c52,
server side is shadowsocks-libev + v2ray-plugin, and it was work on v2ray  client, but it is was failed on shadowsocks windows client.
server side
command: 
> ss-server -c /path/server_config.json --plugin /path/v2ray-plugin_linux_amd64 --plugin-opts "server;mode=websocket;path=/;loglevel=info"

server_config.json:
```
{
    "server_port":8080,
    "password":"passwd123",
    "timeout":600,
    "method":"aes-128-gcm"
}
```
windows client:
![ssws2](https://user-images.githubusercontent.com/5766149/53697257-b04de200-3e0a-11e9-93d5-e02648f76141.png)

![ssws](https://user-images.githubusercontent.com/5766149/53697142-3d903700-3e09-11e9-8d43-cc55726c51c7.png)

what is wrong?
 and the v2ray client's json file, it is work for shadowsocks-libev + v2ray-plugin which is the server side.

> {
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
        {
            "port": 8081,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "tag": "protocol_layer",
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "method": "aes-128-gcm",
                        "port": 10000,
                        "password": "passwd123",
                        "address": "baidu.com"
                    }
                ]
            },
            "proxySettings": {
                "tag": "transport_layer"
            }
        },
        {
            "tag": "transport_layer",
            "protocol": "freedom",
            "settings": {
                "redirect": "serveraddress.com:8080"
            },
            "streamSettings": {
                "wsSettings": {
                    "path": "/"
                },
                "network": "ws",
                "security": "none"
            },
            "mux": {
                "enabled": true
            }
        }
    ],
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rule": [
            {
                "type": "field",
                "network": "tcp,udp",
                "outboundTag": "protocol_layer"
            }
        ]
    }
}

**Comment by qgtxqj** [comment]
日志呢？

**Comment by c21xdx** [comment]
> 日志呢？

server side log, it seem nothoing is coming
![sss](https://user-images.githubusercontent.com/5766149/53705216-bd47f100-3e5d-11e9-9bff-8dad4d2f0913.png)
my window pc side log,
![ssc](https://user-images.githubusercontent.com/5766149/53705228-cdf86700-3e5d-11e9-8231-f23bafb0f613.png)

**Comment by qgtxqj** [comment]
server端loglevel=debug试试

**Comment by c21xdx** [comment]
> server端loglevel=debug试试

一样的，没什么消息进来。
![sss2](https://user-images.githubusercontent.com/5766149/53706528-c63cc080-3e65-11e9-9bcb-8c565164cb4c.png)

**Comment by qgtxqj** [comment]
你确认网络没问题吗？ 8080端口是开放的？你直接用浏览器访问一下试试

**Comment by c21xdx** [comment]
> 你确认网络没问题吗？ 8080端口是开放的？你直接用浏览器访问一下试试

网络没问题。我用v2ray的图形客户端v2rayN去连接这个相同的服务端，都能正常上网。
直接浏览器访问 domainurl:8080， 页面能打开，显示 Bad Request.

**Comment by lcdtyph** [comment]
Didn't reproduce

**Comment by triaqu** [comment]
客户端选项把host=域名;path=/ 加上试试呢

**Comment by c21xdx** [comment]
> 客户端选项把host=域名;path=/ 加上试试呢

谢谢大佬，我把host=域名 在选项加上就连上了。不过很奇怪的是，没被墙的网站能打开，比如ipip.net，这个打开后显示的也是我的美国服务器的IP。但是被墙的如谷歌就打不开，服务端日志信息如下:
```
 2019-03-06 02:30:40 INFO: initializing ciphers... aes-128-gcm
 2019-03-06 02:30:40 INFO: tcp server listening at 127.0.0.1:
 2019-03-06 02:30:40 INFO: running from root user
2019/03/06 02:30:40 V2Ray 4.16 (Po) Custom
2019/03/06 02:30:40 A unified platform for anti-censorship.
2019/03/06 02:30:40 [Debug] v2ray.com/core/app/log: Logger started
2019/03/06 02:30:40 [Warning] v2ray.com/core: V2Ray 4.16 started
2019/03/06 02:30:47 [Debug] [3617658480] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:45644
2019/03/06 02:30:47 [Debug] [2497388905] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:51006
2019/03/06 02:30:47 tcp:127.0.0.1:45644 accepted tcp:127.0.0.1:0 
2019/03/06 02:30:47 [Info] [3617658480] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/03/06 02:30:47 [Info] [3617658480] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/03/06 02:30:47 [Info] [3617658480] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:43035
2019/03/06 02:30:47 [Info] [3617658480] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:43035
2019/03/06 02:30:47 tcp:127.0.0.1:51006 accepted tcp:127.0.0.1:0 
2019/03/06 02:30:47 [Info] [2497388905] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/03/06 02:30:47 [Info] [2497388905] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/03/06 02:30:47 [Info] [2497388905] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:43035
2019/03/06 02:30:47 [Info] [2497388905] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:43035
2019/03/06 02:30:49 [Debug] [2653848124] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:33344
2019/03/06 02:30:49 tcp:127.0.0.1:33344 accepted tcp:127.0.0.1:0 
2019/03/06 02:30:49 [Info] [2653848124] v2ray.com/core/common/mux: received request for tcp:127.0.0.1:0
2019/03/06 02:30:49 [Info] [2653848124] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/03/06 02:30:49 [Info] [2653848124] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:43035
2019/03/06 02:30:49 [Info] [2653848124] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:43035
2019/03/06 02:31:17 [Info] [3617658480] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/03/06 02:31:17 [Info] [3617658480] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/03/06 02:31:17 [Info] [3617658480] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/03/06 02:31:17 [Info] [3617658480] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/03/06 02:31:20 [Info] [2653848124] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/03/06 02:31:20 [Info] [2653848124] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/03/06 02:31:20 [Info] [2653848124] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/03/06 02:31:20 [Info] [2653848124] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/03/06 02:31:20 [Info] [2497388905] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/03/06 02:31:20 [Info] [2497388905] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/03/06 02:31:20 [Info] [2497388905] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/03/06 02:31:20 [Info] [2497388905] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
```

**Comment by c21xdx** [comment]
在安卓手机版再试了一下，手机端是完全OK的，谷歌能打开。和PC端相同的配置，就是手机里多出来的部分是 远程DNS 8.8.8.8.
