### ISSUE TITLE
Connect to v2ray server

### ISSUE THREAD

**Issue by Tualua** [shadowsocks/v2ray-plugin#62]
Hello!
Is it possible to connect to v2ray server using shadowsocks client and this plugin?

**Comment by updater1234** [comment]
No,this plugin is only a part of v2ray.So you cannot use shadowsocks client and this plugin to connect v2ray server.

**Comment by dimqua** [comment]
Can I do the opposite: connect to SS server with this plugin using V2Ray client?

**Comment by Tualua** [comment]
Thanks for info!

**Comment by qgtxqj** [comment]
https://github.com/v2ray/discussion/issues/173

实际上是可以的，参考一下那个样例配置文件即可。
