### ISSUE TITLE
how to simulate traffic to host www.youtube.com

### ISSUE THREAD

**Issue by whoizit** [shadowsocks/v2ray-plugin#63]
how can I simulate traffic to host www.youtube.com? I have problems with acme.sh and certs
while testing, I launch it as root
```
"plugin": "v2ray-plugin",
"plugin_opts":"server;tls;host=www.youtube.com;cert=/root/.acme.sh/www.youtube.com/www.youtube.com.csr;key=/root/.acme.sh/www.youtube.com/www.youtube.com.key"
```
2019/03/09 21:59:17 http: TLS handshake error from 78.37.201.7:18903: tls: no certificates configured  
2019/03/09 21:59:19 http: TLS handshake error from 78.37.201.7:19461: tls: no certificates configured

it works with simple-obfs

**Comment by malikshi** [comment]
use your own domain.

**Comment by LiveChief** [comment]
Get a domain for like books or videos that u own and do it to that , it's not possible to use other people's websites

**Comment by whoizit** [comment]
I do not have a domain, it costs money

**Comment by LiveChief** [comment]
@whoizit http://www.dot.tk/

and

https://www.cloudflare.com

**Comment by Mygod** [comment]
Impossible and should not be possible for obvious security reasons.

**Comment by lotus-x** [comment]
If my ISP/Company firewall block traffic to all other domains, but only allow access to few domains, then can I use v2ray to fake my packets act like they are routing to one of those allowed domain?

**Comment by Prajwal-Koirala** [comment]
Create your own domain and use that.
@lotus-x

Try outline.
