### ISSUE TITLE
[Bug] port already in use

### ISSUE THREAD

**Issue by linhua55** [shadowsocks/v2ray-plugin#64]
When use `plugin`  and `plugin-opts` in  `config.json`   like this:

    "plugin": "v2ray-plugin",
    "plugin-opts": "server; path=/xxxxx/"

The v2ray would crash with error "port already in use".  The v2ray and shadowsocks would use same port which is random instead of `server_port`.

v2ray-plugin Version: v1.1.0

**Comment by TomFrank** [comment]
~~"plugin-opts"~~: "server; path=/xxxxx/"
**"plugin_opts"**: "server; path=/xxxxx/"

that's underline
