### ISSUE TITLE
可否增加failover功能

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/v2ray-plugin#66]
在VPS有真实网站下，simple-obfs将ss流量直接转发到ss而一般流量则failover到web服务。这个插件的ss流量则需要先通过web服务分流到v2ray插件再到ss, 也就是websocket+tls+web方式，效率上没有第一种方式高，而且web服务也会占用较大的资源。
所以v2ray-plugin可否增加failover功能，即ss流量通过插件直接调用ss服务，而一般流量则转发到web服务。

**Comment by debiansid** [comment]
性能有什么区别

**Comment by triaqu** [comment]
我用的CADDY转发，在流量较大时会占用较多资源，用TOP就能看到。而且简单比较两种方式的带宽也有区别。

**Comment by Mygod** [comment]
simple-obfs is expected to perform better because it is simple. It's an inherent trade-off.
