### ISSUE TITLE
How to reduce the compiled file size

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/v2ray-plugin#68]
In the release page, file size for linux-arm and linux-mips is too big.
Is there any method to reduce the size?
eg. I'm using a router with armv7 CPU, how to build to make the file size smaller?

**Comment by rampageX** [comment]
`upx `

**Comment by Love4Taylor** [comment]
https://upx.github.io

```
upx --best /path/to/v2ray-plugin
```

**Comment by oglops** [comment]
@cokebar Did you managed to get file size smaller ? I saw there is commit 1d239bc already, but latest release `1.2.0` binaries are still around 3.4 MB
