### ISSUE TITLE
[Question]UDP Forwarding using v2ray plugin

### ISSUE THREAD

**Issue by shadowmigue** [shadowsocks/v2ray-plugin#70]
Hello to anyone!

I just want to know if there is a way to do the udp forwarding using v2ray plugin on the serverside so i can use it to make voip calls and play online games!

Regards, 
ShadowMigue

**Comment by LiveChief** [comment]
idk why its not working for u but its working for me buddy

**Comment by Mygod** [comment]
Use UDP fallback.

**Comment by aeroweb340** [comment]
Hello!

I'm using SS + v2ray plugin (Websocket TLS + CloudFlare CDN). I can't get Skype VOIP calls go through. I connect from the UAE.

Here is the conf:
{
    "server":"0.0.0.0",
    "server_port":443,
    "password":"",
    "timeout":300,
    "method":"aes-256-gcm",
    "fast_open":false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"v2ray-plugin",
    "plugin_opts":"server;tls;cert=/etc/letsencrypt/live/mywebsite.com/f$
}
Thank you for anything you can do to help.
