### ISSUE TITLE
not working with google voice wifi-calling

### ISSUE THREAD

**Issue by baraja** [shadowsocks/v2ray-plugin#72]
shadowsocks-android 4.7.4 has fixed this problem, https://github.com/shadowsocks/shadowsocks-android/issues/2168

however, shadowsocks-andorid 4.7.4 with v2ray plugin enabled cannot work with GV wifi-calling.

the situation is:
v2ray plugin is setup correctly on my system (both android and windows)
I can use GV wifi-calling perfectly with v2ray plugin disabled on android
I can use GV wifi-calling perfectly with v2ray plugin enabled on windows
plugin's options: path=/mypath;host=mydomainl;tls
(websocket + tls)

**Comment by Mygod** [comment]
Use UDP fallback.
