### ISSUE TITLE
behind CDN

### ISSUE THREAD

**Issue by whoizit** [shadowsocks/v2ray-plugin#75]
Is it possible using shadowsocks-libev proxy with v2ray-plugin on VPS behind CDN? 

On server and client I have used same updated Linux OS with same software versions
```
shadowsocks-libev 3.2.5
shadowsocks-v2ray-plugin 1.1.0
```

How I do this:
### Create free domain 
https://freenom.com

### Reg. on cloudflare.com and add your domain
`https://dash.cloudflare.com>{DOMAIN.TLD}`
* `DNS page>A, Name=@, ipv4_address={VPS V4IP}, Automatic TTL>Add Record`

### Set cloudflare nameservers 
* on `https://my.freenom.com>My Domains>Manage Domains>Management Tools>Nameservers`
* from `https://dash.cloudflare.com>{DOMAIN.TLD}>DNS page`

### Generating certs
`https://dash.cloudflare.com>{DOMAIN.TLD}>Get your API key>Origin CA Key>View`
```
$ sudo cat /root/.secrets/certbot/cloudflare.ini
dns_cloudflare_email = mail@example.tld
dns_cloudflare_api_key = api_key

$ sudo chmod 700 /root/.secrets/certbot/cloudflare.ini

$ sudo certbot certonly \
  --dns-cloudflare \
  --dns-cloudflare-credentials /root/.secrets/certbot/cloudflare.ini \
  --dns-cloudflare-propagation-seconds 120 \
  -d domain.tld
```

### shadowsocks-libev server settings
```
{
  "server": "0.0.0.0", 
  "server_port": 443,
  "password": "{PASSWORD}",
  "method": "xchacha20-ietf-poly1305",
  "plugin": "v2ray-plugin",
  "plugin_opts": "server;tls;host={DOMAIN.TLD};cert=/home/user/.acme.sh/{DOMAIN.TLD}/fullchain.cer;key=/home/user/.acme.sh/{DOMAIN.TLD}/{DOMAIN.TLD}.key;loglevel=debug"
}
```
`sudo ss-server -c /etc/shadowsocks/config.json`

### shadowsocks-libev client settings
```
{
  "server": "{DOMAIN.TLD}", 
  "server_port": 443,
  "local_address": "127.0.0.1", 
  "local_port": 1080,
  "password": "{PASSWORD}",
  "method": "xchacha20-ietf-poly1305",
  "plugin": "v2ray-plugin", 
  "plugin_opts": "tls;host={DOMAIN.TLD};loglevel=debug"
}
```
`sudo ss-local -c /etc/shadowsocks/config.json`

### Setting browser proxy settings to 
type=SOCKS5 IP=127.0.0.1 port=1080

### On client I getting:
_(I hid the domain name from log)_
```
...
 2019-04-18 06:07:25 INFO: connect to riot.im:443
2019/04/18 06:07:25 [Debug] [1844585956] v2ray.com/core/proxy/dokodemo: processing connection from: [::1]:42008
2019/04/18 06:07:25 [Info] [1844585956] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/04/18 06:07:25 [Info] [1844585956] v2ray.com/core/common/mux: dispatching request to tcp:127.0.0.1:0
2019/04/18 06:07:25 [Info] v2ray.com/core/proxy/freedom: opening connection to tcp:{DOMAIN.TLD}:443
2019/04/18 06:07:25 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:{DOMAIN.TLD}:443
2019/04/18 06:07:25 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:{DOMAIN.TLD}:443
2019/04/18 06:07:25 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:{DOMAIN.TLD}:443
2019/04/18 06:07:26 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:{DOMAIN.TLD}:443
2019/04/18 06:07:26 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:{DOMAIN.TLD}:443
2019/04/18 06:07:27 [Info] failed to handler mux client connection > v2ray.com/core/proxy/freedom: failed to open connection to tcp:{DOMAIN.TLD}:443 > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://{DOMAIN.TLD}/):  > remote error: tls: handshake failure] > v2ray.com/core/common/retry: all retry attempts failed
2019/04/18 06:07:27 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/04/18 06:07:28 [Info] [1844585956] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > context canceled
2019/04/18 06:07:28 [Info] [1844585956] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
...
```
### On server I getting:
_(different timezones)_
`2019/04/18 03:53:22 http: TLS handshake error from 198.108.66.192:20334: tls: no cipher suite supported by both client and server`

**Comment by madeye** [comment]
Double check if you have enabled `websocket` in CloudFlare.

**Comment by whoizit** [comment]
`websocket` enabled by default on cloudflare `Network` page

**Comment by madeye** [comment]
Can you confirm that the plugin works without CDN?

**Comment by whoizit** [comment]
on server
I disable `cloudflare` service and switch domain settings to `freenom` DNS
Now I getting on server
```
2019/04/18 04:56:52 http: TLS handshake error from 91.122.20.124:45216: remote error: tls:
bad certificate
2019/04/18 04:56:52 http: TLS handshake error from 91.122.20.124:45220: remote error: tls: bad certificate
2019/04/18 04:56:54 http: TLS handshake error from 91.122.20.124:45238: remote error: tls: bad certificate
```
Oh, wow, seems like I typo in one char in domain name. it was `.gg` instead `.gq`
`"plugin_opts": "tls;host={DOMAIN.gg};loglevel=debug"`

`2019/04/18 07:57:17 [Info] failed to handler mux client connection > v2ray.com/core/proxy/freedom: failed to open connection to tcp:meshnet.gq:443 > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://{DOMAIN.gq/):  > **x509: certificate is valid for {DOMAIN.gq}, not {DOMAIN.gg}**] > v2ray.com/core/common/retry: all retry attempts failed`

**Comment by whoizit** [comment]
now I getting on client
`x509: certificate signed by unknown authority`

**Comment by whoizit** [comment]
now `521 Origin Down > websocket: bad handshake`

**Comment by whoizit** [comment]
on server:
```
2019/04/18 08:57:16 [Info] [1883109256] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed
to transport request > websocket: close 1006 (abnormal closure): unexpected EOF           
2019/04/18 08:57:16 [Info] [1883109256] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled  
2019/04/18 08:57:16 [Info] [4272083748] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed
to transport request > websocket: close 1006 (abnormal closure): unexpected EOF           
2019/04/18 08:57:16 [Info] [4272083748] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled  
2019/04/18 08:57:16 [Info] [1217812956] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe               
2019/04/18 08:57:16 [Info] [1217812956] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
```

**Comment by whoizit** [comment]
It works directly, but not over CDN

**Comment by whoizit** [comment]
also works over CDN in websocket (HTTP) mode. I change port to 80 and remove TLS from config, and it works. But I need TLS

**Comment by devarped** [comment]
How about trying stunnel for TLS termination on your client computer? It works for me, I aslo use it to balance load between various Cloudflare IPs.
The sample config is:
```
[socks]
client = yes
accept = 127.0.0.1:1337
connect = 104.20.23.61:443
connect = 104.16.58.5:443
connect = 104.16.168.99:443
protocolHost = <your domain>:443
verifyChain = yes
checkHost = <your domain>
CApath = /etc/ssl/certs
```
Then just set server and server_port to 127.0.0.1 and 1337 respectively in shadowsocks config.

**Comment by whoizit** [comment]
@devarped do you mean ss-libev>v2ray-plugin (websocket - http server)<->v2ray-plugin (websocket - http client)<ss-libev<stunnel (TLS)?

**Comment by devarped** [comment]
> @devarped do you mean ss-libev>v2ray-plugin (websocket - http server)<->v2ray-plugin (websocket - http client)<ss-libev<stunnel (TLS)?

Not exactly. I meant that stunnel should be on client, so it's something like this: `(server: ss-libev <- v2ray-plugin (in TLS mode)) <-> (client: stunnel -> v2ray-plugin (in regular non-TLS mode) -> ss-libev)`.

**Comment by whoizit** [comment]
Finally it works
**minimal configs with shadowsocks-libev + v2ray-plugin with certs from certbot in TLS mode behind cloudflare CDN:**
```
$ sudo cat /root/.secrets/certbot/cloudflare.ini
dns_cloudflare_email = mail@example.tld
dns_cloudflare_api_key = api_key

$ sudo l /root/.secrets/certbot/cloudflare.ini
-rwx------ 1 root root 106 Apr 19 01:58 /root/.secrets/certbot/cloudflare.ini

sudo certbot certonly \
  --dns-cloudflare \
  --dns-cloudflare-credentials ~/.secrets/certbot/cloudflare.ini \
  --dns-cloudflare-propagation-seconds 120 \
  -d domain.tld
```

server:
```
{
  "server": "0.0.0.0",
  "server_port": 443,
  "password": "password",
  "method": "aes-256-gcm",
  "timeout": 300,
  "plugin": "v2ray-plugin",
  "plugin_opts": "server;tls;host=domain.tld;cert=/etc/letsencrypt/live/domain.tld/fullchain.pem;key=/etc/letsencrypt/live/domain.tld/privkey.pem;loglevel=debug"
}
```
`sudo ss-server -c server.config`

client:
```
{ 
  "server": "domain.tld",
  "server_port": 443,
  "local_port": 1080,
  "password": "password",
  "method": "aes-256-gcm",
  "timeout": 300,
  "plugin": "v2ray-plugin",
  "plugin_opts": "tls;host=domain.tld;loglevel=debug"
}
```
`pkill v2ray; ss-local -c client.config`

**Comment by whoizit** [comment]
**minimal client configs with stunnel**
`cat /etc/stunnel/stunnel.conf`
```
foreground = yes

[socks]
client = yes
accept = 127.0.0.1:1337
connect = cloudflare_ip:443
connect = cloudflare_ip:443
protocolHost = domain.tld:443
verifyChain = yes
checkHost = domain.tld
CApath = /etc/ssl/certs
```
`stunnel  /etc/stunnel/stunnel.conf`
```
{ 
  "server": "127.0.0.1",
  "server_port": 1337,
  "local_port": 1080,
  "password": "password",
  "method": "aes-256-gcm",
  "timeout": 300,
  "plugin": "v2ray-plugin",
  "plugin_opts": "host=domain.tld",
}
```

**Comment by whoizit** [comment]
@devarped I don't know what the problem was, but now it seems to work. Thank you anyway.

What are the advantages of using stunnel for load balancing on Сloudflare CDN?

**Comment by malikshi** [comment]
Server side for stunnel?

**Comment by devarped** [comment]
@whoizit 
>I don't know what the problem was

I guess the problem was in v2ray cipher support, as it does not implement all the ciphers supported by Cloudflare and major browsers, for example, it does not support TLS 1.3 yet (if I'm wrong, then this is an issue with Android plugin). So, I have to use stunnel to decrypt TLS 1.3 for v2ray instead of handling it within v2ray itself.
>What are the advantages of using stunnel for load balancing on Сloudflare CDN?

I guess it will make the traffic look more legitimate, since the packaets are being sent to different addreses instead of only one.

@malikshi 
I didn't try to use stunnel on server side, but I think it shouldn't be too hard, [stunnel example config](https://www.stunnel.org/config_unix.html) shows an example of TLS front-end for a webserver, which should also work with v2ray.

**Comment by omidraha** [comment]
> Finally it works
> **minimal configs with shadowsocks-libev + v2ray-plugin with certs from certbot in TLS mode behind cloudflare CDN:**
> 
> ```
> $ sudo cat /root/.secrets/certbot/cloudflare.ini
> dns_cloudflare_email = mail@example.tld
> dns_cloudflare_api_key = api_key
> 
> $ sudo l /root/.secrets/certbot/cloudflare.ini
> -rwx------ 1 root root 106 Apr 19 01:58 /root/.secrets/certbot/cloudflare.ini
> 
> sudo certbot certonly \
>   --dns-cloudflare \
>   --dns-cloudflare-credentials /root/.secrets/certbot/cloudflare.ini \
>   --dns-cloudflare-propagation-seconds 120 \
>   -d domain.tld
> ```
> 
> server:
> 
> ```
> {
>   "server": "0.0.0.0",
>   "server_port": 443,
>   "password": "password",
>   "method": "aes-256-gcm",
>   "timeout": 300,
>   "plugin": "v2ray-plugin",
>   "plugin_opts": "server;tls;host=domain.tld;cert=/etc/letsencrypt/live/domain.tld/fullchain.pem;key=/etc/letsencrypt/live/domain.tld/privkey.pem;loglevel=debug"
> }
> ```
> 
> `sudo ss-server -c server.config`
> 
> client:
> 
> ```
> { 
>   "server": "domain.tld",
>   "server_port": 443,
>   "local_port": 1080,
>   "password": "password",
>   "method": "aes-256-gcm",
>   "timeout": 300,
>   "plugin": "v2ray-plugin",
>   "plugin_opts": "tls;host=domain.tld;loglevel=debug"
> }
> ```
> 
> `pkill v2ray; ss-local -c client.config`

With the same configs as above, Now I get this error on client:

`521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed`

Do you have any idea?

**Comment by whoizit** [comment]
Double check you config. If u set correct domain.tld, i believe you need just await 24h before cert will work. Try to test it, please.

**Comment by omidraha** [comment]
I double checked, config is the same as yours.
I will wait for time,

Here is current client full log:
```
2019-04-20 21:13:07 INFO: connect to www.instagram.com:443
2019/04/20 21:13:07 [Debug] [3858380295] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:42006
2019/04/20 21:13:07 [Info] [3858380295] v2ray.com/core/app/dispatcher: default route for tcp:127.0.0.1:0
2019/04/20 21:13:07 [Info] [3858380295] v2ray.com/core/common/mux: dispatching request to tcp:127.0.0.1:0
2019/04/20 21:13:07 [Info] v2ray.com/core/proxy/freedom: opening connection to tcp:example.com:443
2019/04/20 21:13:07 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:example.com:443
2019/04/20 21:13:09 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:example.com:443
2019/04/20 21:13:09 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:example.com:443
2019/04/20 21:13:10 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:example.com:443
2019/04/20 21:13:12 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:example.com:443
2019/04/20 21:13:13 [Info] failed to handler mux client connection > v2ray.com/core/proxy/freedom: failed to open connection to tcp:example.com:443 > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://example.com/): 521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2019/04/20 21:13:13 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/04/20 21:13:14 [Info] [3858380295] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > context canceled
2019/04/20 21:13:14 [Info] [3858380295] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
```

>  I replace my domain with example.com in the above log.

I don't know this is important or not, but when I directly go to my domain on browser,
Cloud flare show me [Error 522 page](https://support.cloudflare.com/hc/en-us/article_attachments/201814387/error522.png).

**Comment by whoizit** [comment]
`521 Origin Down > websocket: bad handshake`
I getting same issue long time, and I don't know how was it resolved, Just a wait. I have no answer. I post best minimal config, it's absolutelly correct.

**Comment by whoizit** [comment]
check yours ports on client and server
```
$ sudo ss -nlp | egrep 'ss-server|ss-local|v2ray'
udp                UNCONN              0                    0                                                                                         127.0.0.1:1080                0.0.0.0:*       users:(("ss-local",pid=29127,fd=7))         
tcp                LISTEN              0                    128                                                                                       127.0.0.1:1080                0.0.0.0:*       users:(("ss-local",pid=29127,fd=6))         
tcp                LISTEN              0                    128                                                                                           [::1]:55547                  [::]:*       users:(("v2ray-plugin",pid=29128,fd=4)) 
```

**Comment by whoizit** [comment]
i getting 521 if I open my domain from browser

**Comment by omidraha** [comment]
> i getting 521 if I open my domain from browser

Thanks, same as me, because there is no web server running on server.

**Comment by omidraha** [comment]
> check yours ports on client and server
> 
> ```
> $ sudo ss -nlp | egrep 'ss-server|ss-local|v2ray'                      
> [sudo] password for user:
> udp   UNCONN 0      0                                       0.0.0.0:443                   
>                          0.0.0.0:*                                    users:(("ss-server",pid=16495,fd=7))                                                                           
> tcp   LISTEN 0      1024                                  127.0.0.1:37109                 
>                          0.0.0.0:*                                    users:(("ss-server",pid=16495,fd=5))                                                                           
> tcp   LISTEN 0      4096                                          *:443                   
>                                *:*                                    users:(("v2ray-plugin",pid=16496,fd=3))
> ```
> 
> ```
> $ sudo ss -nlp | egrep 'ss-server|ss-local|v2ray'
> udp                UNCONN              0                    0                                                                                         127.0.0.1:1080                0.0.0.0:*       users:(("ss-local",pid=29127,fd=7))         
> tcp                LISTEN              0                    128                                                                                       127.0.0.1:1080                0.0.0.0:*       users:(("ss-local",pid=29127,fd=6))         
> tcp                LISTEN              0                    128                                                                                           [::1]:55547                  [::]:*       users:(("v2ray-plugin",pid=29128,fd=4)) 
> ```

Server:
```
server $ sudo ss -nlp | egrep 'ss-server|ss-local|v2ray'  
tcp  LISTEN 0       1024     127.0.0.1:32383              0.0.0.0:*       users:(("ss-server",pid=16852,fd=5))              
tcp  LISTEN 0       4096             *:443                      *:*       users:(("v2ray-plugin_li",pid=16853,fd=3))        
```
Client:
```
client $ sudo ss -nlp | egrep 'ss-server|ss-local|v2ray'
tcp     LISTEN              0          128     127.0.0.1:9090                0.0.0.0:*            users:(("ss-local",pid=9289,fd=6))               
tcp     LISTEN              0          128     127.0.0.1:50483               0.0.0.0:*            users:(("v2ray-plugin_li",pid=9290,fd=4))                  
```

**Comment by omidraha** [comment]
While I'm waiting 24h for cert, Do `ss-server` and `v2ray` have to run on the server with HTTPS mode?
Or I can temporarily switch to HTTP mode?

**Comment by whoizit** [comment]
Test if it works without a CDN. Set your VPS ip to "server" in client

**Comment by whoizit** [comment]
do you change TLS version on cloudflare _Crypto_ page? v2ray-plugin still not support TLS v1.3

**Comment by omidraha** [comment]
> do you change TLS version on cloudflare _Crypto_ page? v2ray-plugin still not support TLS v1.3

It was Enbaled, I disable it now. but I still get the same handshake error.

**Comment by whoizit** [comment]
Does it work without a CDN?

**Comment by omidraha** [comment]
> Test if it works without a CDN. Set your VPS ip to "server" in client

It works  directly with TLS.
It also works over CDN without TLS. 

But I need TLS over CDN.

**Comment by whoizit** [comment]
https://community.cloudflare.com/t/cloudflare-serving-wrong-ssl-certificate/1021
https://community.cloudflare.com/t/certificate-ssl-does-not-work/34962

**Comment by omidraha** [comment]
In TLS without CDN mode, I receive connections log on server.
In HTTP with CDN mode, I also receive connections log on server.
But In TLS with CDN mode, I don't receive any connection log on server, why requests from client is not received by server?

**Comment by whoizit** [comment]
I think the problem is in the cloudflare and/or certificate. I had the same problem, but idk how I solve it.

**Comment by omidraha** [comment]
On DNS page of cloudflare , for domain you added, The status icon is [orange](https://support.cloudflare.com/hc/en-us/article_attachments/205133448/Screen_Shot_2016-01-31_at_4.17.04_PM.png) or is [gray](https://support.cloudflare.com/hc/en-us/article_attachments/205133458/Screen_Shot_2016-01-31_at_4.17.12_PM.png)?

**Comment by whoizit** [comment]
orange
all by default, I just put minimal TLS version 1.2 and SSL Full (strict) on Crypto page

**Comment by omidraha** [comment]
> orange
> all by default, I just put minimal TLS version 1.2 and SSL Full (strict) on Crypto page

Thank, Fixed with change to your these configs.

When you go this address: https://www.google.com/search?q=ip

The IP displayed to you, is IP of cloud-flare or is IP of your server?

**Comment by whoizit** [comment]
on this page I see link to wiki page about IP. 
On another sites I see my VPS IP. And it's correct, cause Cloudflare CDN only proxying traffic to my VPS.

You should set `socks5 127.0.0.1:1080` to your web browser proxy setting

**Comment by omidraha** [comment]
I did before,
So Same as me, I just think because this is behind CND, The IP should be the IP of Cloudflare.
So every thing works.
Thank you so much for your great help. @whoizit ,
_I will remove all posts in this thread, for some considerations._

**Comment by whoizit** [comment]
it turns out the certificate cloudflare is not required. You can use letsencrypt cert, so it even simpler:

`sudo certbot certonly --standalone -d $MY_DOMAIN -m $EMAIL --agree-tos --non-interactive `

**Comment by Jay54520** [comment]
@whoizit 
What kind of CDN can v2ray use? Must the CDN support websocket?
Can v2ray use CDN that support HTTP2 or HTTPS ?

**Comment by whoizit** [comment]
@Jay54520 You can read in README.md which types are supported by the v2ray-plugin. Yes, CDN should support websocket or quic proxying. Cloudflare, for example support free websocket proxying from 2015.
