### ISSUE TITLE
不能用mode=quic

### ISSUE THREAD

**Issue by wupeng1211** [shadowsocks/v2ray-plugin#78]
把mode=quic去掉可以，Android段也可以连接，加上后，android改成quic-tls连接不成功，请问我配置文件哪里出错了吗？
{
    "server": "0.0.0.0",
    "server_port": 54321,
    "nameserver": "8.8.8.8",
    "timeout": 60,
    "method": "xchacha20-ietf-poly1305",
    "password": "987654321",
    "plugin": "/usr/bin/v2ray-plugin",
    "plugin_opts": "server;mode=quic;tls;fast-open;host=xxx.com;cert=/home/ka/.acme.sh/xxx.com/fullchain.cer$
    "mode": "tcp_only",
    "fast_open": true,
    "no_delay": true
}

**Comment by wupeng1211** [comment]
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-05-06 15:47:00 CST; 2s ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 948 (ss-server)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/shadowsocks-libev.service
           ├─948 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json
           └─954 /usr/bin/v2ray-plugin --fast-open

May 06 15:47:00 Bestone_Vultr systemd[1]: Started Shadowsocks-libev Default Server Service.
May 06 15:47:00 Bestone_Vultr ss-server[948]:  2019-05-06 15:47:00 INFO: using tcp fast open
May 06 15:47:00 Bestone_Vultr ss-server[948]:  2019-05-06 15:47:00 INFO: plugin "/usr/bin/v2ray-plugin" enabled
May 06 15:47:00 Bestone_Vultr ss-server[948]:  2019-05-06 15:47:00 INFO: enable TCP no-delay
May 06 15:47:00 Bestone_Vultr ss-server[948]:  2019-05-06 15:47:00 INFO: initializing ciphers... xchacha20-ietf-poly1305
May 06 15:47:00 Bestone_Vultr ss-server[948]:  2019-05-06 15:47:00 INFO: tcp server listening at 127.0.0.1:40443
May 06 15:47:01 Bestone_Vultr ss-server[948]: 2019/05/06 15:47:01 V2Ray 4.16 (Po) Custom
May 06 15:47:01 Bestone_Vultr ss-server[948]: 2019/05/06 15:47:01 A unified platform for anti-censorship.
May 06 15:47:01 Bestone_Vultr ss-server[948]: 2019/05/06 15:47:01 [Warning] v2ray.com/core: V2Ray 4.16 started

**Comment by wupeng1211** [comment]
服务器端运行感觉没什么问题

**Comment by mchlwang** [comment]
去掉tls;

**Comment by wupeng1211** [comment]
> 去掉tls;

@ @mchlwang 去掉也不行

**Comment by z5n0w** [comment]
少了个key参数？

**Comment by wupeng1211** [comment]
> 少了个关键参数？

少了什么？

**Comment by z5n0w** [comment]
"plugin_opts"="server;tls;key=xxx;cert=xxx"
这个key
