### ISSUE TITLE
Add a gitlab mirrors for better download speed.

### ISSUE THREAD

**Issue by zw963** [shadowsocks/v2ray-plugin#80]
Hello, Gitlab can be [set](https://gitlab.com/help/workflow/repository_mirroring#pulling-from-a-remote-repository-starter) to auto mirroring an upstream repo(e.g, current github repo) every minutes, and give us a better download speeds.

Following is my own deploy script for download this plugin to my router. (i always disable transparency proxy, and after deploy is finished, enable it again, because i am updating proxy), so, when disable proxy, download speed is very slow like this.

![image](https://user-images.githubusercontent.com/549126/57581342-bafeb480-74e8-11e9-93a1-2be3b270a9dc.png)

Because github assets use amazon S3,  it is very very slow when not enable proxy.

For  the same reason, i create another issue #58, so, but i got a very strange answer.

![image](https://user-images.githubusercontent.com/549126/57581391-732c5d00-74e9-11e9-84e9-8beac963fbe9.png)

I thought that guy never know the internet situation live on china, please consider resolve this.

Thank you.

**Comment by Mygod** [comment]
I believe one does not need any authorization to create mirrors.
