### ISSUE TITLE
是否有 iOS 客户端可以支持该插件并支持设置路径(path)

### ISSUE THREAD

**Issue by bzdk** [shadowsocks/v2ray-plugin#81]
PC/Mac/Android 平台都有客户端可以支持 websocket (HTTPS) 模式下设置路径。不知是否有iOS客户端也能支持以上特性？

**Comment by zhangyz1997** [comment]
Shadowrocket的TestFlight版本

**Comment by bzdk** [comment]
@zhangyz1997 感谢告知，好消息。

**Comment by GainSury** [comment]
> @zhangyz1997 感谢告知，好消息。

今天已经更新支持了
