### ISSUE TITLE
How to specify id and alterid in plugin_opts?

### ISSUE THREAD

**Issue by kfstorm** [shadowsocks/v2ray-plugin#83]
My VPS provider requires `id` and `alterid`. But I can't find any instruction to specify them in `plugin_opts`.

**Comment by madeye** [comment]
`id` and `alterid` are part of `vmess` protocol.

Given `v2ray-plugin` works as a SIP003 plugin of shadowsocks for transport obfuscating only, you don't need to specify any of them in the `plugin_opts`.

**Comment by kfstorm** [comment]
I misunderstood the target scenario of this plugin. This plugin is used to enable v2ray transport between shadowsocks client and server. It can't be used to connect to a v2ray server with v2ray plugin enabled shadowsocks client.
