### ISSUE TITLE
Can anyone to recommend a client on IOS?

### ISSUE THREAD

**Issue by mkuymkuy** [shadowsocks/v2ray-plugin#84]
Hi, 
I built this on my linux server. But I don't find any iOS app supporting this feature. Any suggestions?

**Comment by zhangyz1997** [comment]
Shadowrocket

**Comment by GainSury** [comment]
shadowrocket 最新版本已经支持了

**Comment by kopstill** [comment]
@GainSury 
我在win上使用shadowsocks-windows(4.1.6)连接没有问题
但是在iOS上使用shadowrocket和macOS上使用shadowsocks-ng都无法连接
不清楚是什么原因 求帮助 多谢

**Comment by GainSury** [comment]
macOS上看hadowsocks-ng的issue，最新releases没有支持这个插件，但是最新的commit版本支持了，我编译了一份放在一个issue，应该能找到。
shadowrocket再注意下是不是参数没设置对，我测试通过。
可以把你的参数贴上来参考一下。

> @GainSury
> 我在win上使用shadowsocks-windows(4.1.6)连接没有问题
> 但是在iOS上使用shadowrocket和macOS上使用shadowsocks-ng都无法连接
> 不清楚是什么原因 求帮助 多谢

**Comment by kopstill** [comment]
非常感谢 macOS的找到了您放的版本[https://github.com/shadowsocks/ShadowsocksX-NG/issues/1054](#issue-1054)

shadowrocket(2.1.25(727))的配置如下
类型: Shadowsocks
混淆: none
插件: 选择v2ray-plugin 其余项全部默认或为空

服务端的配置如下
{
    "server":"0.0.0.0",
    "server_port":5xxxx,
    "local_port":1080,
    "mode":"tcp_and_udp",
    "password":"xxxxxx",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "plugin":"v2ray-plugin",
    "plugin_opts":"server"
}

**Comment by GainSury** [comment]
插件页面提供服务器和端口填上，确定更新到小火箭的最新版本2.1.25
![IMG_0045](https://user-images.githubusercontent.com/12730371/59357599-b898b000-8d5d-11e9-80fa-ae9e978001c8.jpeg)


> 非常感谢
> 
> macOS的找到了您放的版本[#issue-1054](https://github.com/shadowsocks/ShadowsocksX-NG/issues/1054)
> 
> shadowrocket(2.1.25(727))的配置如下
> 类型: Shadowsocks
> 混淆: none
> 插件: 选择v2ray-plugin 其余项全部默认或为空
> 
> 服务端的配置如下
> ss-server: 3.2.5
> v2ray-plugin: 1.1.0
> 
> ```json
> {
>     "server":"0.0.0.0",
>     "server_port":5xxxx,
>     "local_port":1080,
>     "mode":"tcp_and_udp",
>     "password":"xxxxxx",
>     "timeout":300,
>     "method":"chacha20-ietf-poly1305",
>     "plugin":"v2ray-plugin",
>     "plugin_opts":"server"
> }
> ```

**Comment by kopstill** [comment]
@GainSury 搞定了 是服务器权限的问题 因为我不是root启动的 但是只有手机端访问有问题 很奇怪
不过 非常感谢您的耐心解答 谢谢
