### ISSUE TITLE
how to use this plugin in macos

### ISSUE THREAD

**Issue by mikechen89** [shadowsocks/v2ray-plugin#85]

**Comment by mikechen89** [comment]
when I try to connect use ShadowsocksX-NG on mac, I put this plugin on the same directory with ShadowsocksX-NG, but can not connect to server.

**Comment by kopstill** [comment]
Yes, I have the same problem.

**Comment by GainSury** [comment]
try the newest commit version, not the release version

**Comment by kopstill** [comment]
@mikechen89 [Here](https://github.com/shadowsocks/ShadowsocksX-NG/issues/1054)
