### ISSUE TITLE
Custom HTTP headers

### ISSUE THREAD

**Issue by trochdewei** [shadowsocks/v2ray-plugin#86]
Can you please add support for custom HTTP headers, as in AnonyTun android app? It may help to circumvent more restrictions.
![photo_2019-06-10_19-46-28](https://user-images.githubusercontent.com/37622670/59207674-07e0b400-8b97-11e9-9ad2-251478e80277.jpg)
![photo_2019-06-10_19-46-32](https://user-images.githubusercontent.com/37622670/59207675-08794a80-8b97-11e9-87b6-4a83c82c3100.jpg)

**Comment by trochdewei** [comment]
Looks like v2ray supports it by itself, if iunderstand https://www.v2ray.com/en/configuration/transport/websocket.html

**Comment by Mygod** [comment]
"may" does not justify the cost.

**Comment by 1608637229** [comment]
> "may" does not justify the cost.

我试了下。v2ray插件是支持直接转发http的host的，只需要在手机上填写hostname，然后path只填/
就能正常联网了。证明此插件是完全符合上面所说的v2ray的特性。
