### ISSUE TITLE
How to kill certain v2ray-plugin process which run as a plugin of an ss-xxx

### ISSUE THREAD

**Issue by freakinyy** [shadowsocks/v2ray-plugin#89]
how I start ss-server:
ss-server -c /etc/shadowsocks-libev_server/$json_file -f /var/run/shadowsocks-libev_server/$somename.pid
how I stop ss-server:
kill -9 $(cat /var/run/shadowsocks-libev_server/$somename.pid)

This works fine with obfs-server.
The json file:
{
	"server":"xxx",
	"server_port":xxx,
	"password":"xxx",
	"method":"xxx",
	"timeout":xxx,
	"user":"nobody",
	"plugin":"/usr/bin/obfs-server",
	"plugin_opts":"obfs=http",
	"fast_open":true,
	"mode":"tcp_and_udp"
}
After kill ss-server, the pidof obfs-server is empty.

But doesn't work with v2ray-plugin. 
The json file:
{
	"server":"xxx",
	"server_port":xxx,
	"password":"xxx",
	"method":"xxx",
	"timeout":xxx,
	"user":"nobody",
	"plugin":"/usr/bin/v2ray-plugin",
	"plugin_opts":"server",
	"fast_open":true,
	"mode":"tcp_and_udp"
}
After kill ss-server, the pidof v2ray-plugin is not empty. I have to kill it by "kill $(pidof v2ray-plugin)". But processes that named "v2ray-plugin" will all be killed unexpectedly.

So is there a better way to kill certain v2ray-plugin process which run as a plugin of a ss-xxx?

**Comment by Aster-the-Med-Stu** [comment]
I think it might be a good idea to implment **systemd** to handle the hassle:

```
[Unit]
Description=Shadowsocks QUIC Server
After=network.target

[Service]
ExecStart=/usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config-quic.json -f /var/run/shadowsocks-libev-quic.pid -a www
Restart=always
PIDFile=/var/run/shadowsocks-libev-quic.pid
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target

```

Please notice that I used user **www** to run instead of root, so modify it for your needs, or just simply delete ```-a www```.

Then you could find out that v2ray-plugin is also managed by systemd, so ```service shadowsocks-libev-quic stop``` would kill v2ray-plugin too in my case:

```

● shadowsocks-libev-quic.service - Shadowsocks QUIC Server
   Loaded: loaded (/etc/systemd/system/shadowsocks-libev-quic.service; enabled;
   Active: active (running) since Mon 2019-06-17 21:33:22 CST; 2 days ago
 Main PID: 765 (ss-server)
    Tasks: 10 (limit: 504)
   CGroup: /system.slice/shadowsocks-libev-quic.service
           ├─765 /usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config-qu
           └─773 v2ray-plugin --fast-open
```

**Comment by freakinyy** [comment]
> I think it might be a good idea to implment **systemd** to handle the hassle:
> 
> ```
> [Unit]
> Description=Shadowsocks QUIC Server
> After=network.target
> 
> [Service]
> ExecStart=/usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config-quic.json -f /var/run/shadowsocks-libev-quic.pid -a www
> Restart=always
> PIDFile=/var/run/shadowsocks-libev-quic.pid
> StandardOutput=syslog
> StandardError=syslog
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Please notice that I used user **www** to run instead of root, so modify it for your needs, or just simply delete `-a www`.
> 
> Then you could find out that v2ray-plugin is also managed by systemd, so `service shadowsocks-libev-quic stop` would kill v2ray-plugin too in my case:
> 
> ```
> 
> ● shadowsocks-libev-quic.service - Shadowsocks QUIC Server
>    Loaded: loaded (/etc/systemd/system/shadowsocks-libev-quic.service; enabled;
>    Active: active (running) since Mon 2019-06-17 21:33:22 CST; 2 days ago
>  Main PID: 765 (ss-server)
>     Tasks: 10 (limit: 504)
>    CGroup: /system.slice/shadowsocks-libev-quic.service
>            ├─765 /usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config-qu
>            └─773 v2ray-plugin --fast-open
> ```

Thanks a lot. I found that ""user":"nobody"" causes ss-xxx can only be "kill -9" by another user.  And ss-xxx that be "kill -9" may not clean its plugin.
 ss-xxx can be "kill" by service and both simple-obfs and v2ray-plugin run as plugin exit expectlly.
