### ISSUE TITLE
A TCP Connection Would Be Cut Off If Idle for Too Long

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [shadowsocks/v2ray-plugin#90]
# Version

Server: shadowsocks-libev 3.2.5, with v2ray-plugin 1.1.0
Client: shadowsocks-windows 4.1.6

# Steps to reproduce

- SSH to a server through SOCKS5 proxy created by shadowsocks-windows
- Away from keyboard to take snacks

After get back to screen you would see this:
![PuTTY Err](https://user-images.githubusercontent.com/32929636/59815066-0eff8300-934a-11e9-8f0f-27a53191f7f0.png)

Pretty annoying, isn't it?

**Comment by Mygod** [comment]
Can you confirm that this does not occur without v2ray-plugin?

**Comment by Aster-the-Med-Stu** [comment]
@Mygod Yup I could confirm. I tested with ssh on WSL with ```time ssh root@someserver```. 

# With v2ray-plugin
```
root@comic:~#Connection to marchhappy.tech closed by remote host.
Connection to marchhappy.tech closed.

real    1m2.845s
user    0m0.109s
sys     0m0.297s
```

# Without v2ray-plugin

```
root@comic:~# exit
logout
Connection to marchhappy.tech closed.

real    4m17.206s
user    0m0.031s
sys     0m0.109s
```

**Comment by beanslel** [comment]
I experienced the same thing. Using SSH KeepAlive and setting it to a value below the SS timeout fixed it for me. Putty should have this option.

**Comment by zmz125000** [comment]
nginx 里设置一下
```
location / {
    proxy_read_timeout 600s;
```

**Comment by Aster-the-Med-Stu** [comment]
@zmz125000 谢谢~没考虑到 Nginx 反代代理超时的问题🤣
