### ISSUE TITLE
 e5ada30版本 undefined: "crypto/tls"

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/v2ray-plugin#91]
# go build
# v2ray.com/core/transport/internet/tls
../work/pkg/mod/v2ray.com/core@v4.19.1+incompatible/transport/internet/tls/config.go:191:4: undefined: "crypto/tls".TLS_AES_128_GCM_SHA256
../work/pkg/mod/v2ray.com/core@v4.19.1+incompatible/transport/internet/tls/config.go:192:4: undefined: "crypto/tls".TLS_AES_256_GCM_SHA384
../work/pkg/mod/v2ray.com/core@v4.19.1+incompatible/transport/internet/tls/config.go:193:4: undefined: "crypto/tls".TLS_CHACHA20_POLY1305_SHA256

**Comment by yanyan33333** [comment]
use go 1.12.x 
believe me

**Comment by clockzhong** [comment]
升级为 go 1.12.14解决了这个问题，但是不要升级到 go 1.13，否则会出另外的问题，太混乱了。。。。。
