### ISSUE TITLE
在 v2ray-plugin 中使用 tls 模式后, 原本的 shadowsocks 是否需要再设置加密模式?

### ISSUE THREAD

**Issue by tekksphpiq** [shadowsocks/v2ray-plugin#92]
既然使用 tls 模式后, 所有流量都已经被 tls 加密过, 那原本的 shadowsocks 的加密是不没有任何用途了?再加密一次会不会浪费计算性能?

**Comment by Dark11296** [comment]
我认为可以不加密或者直接使用rc4等弱加密

**Comment by zhfreal** [comment]
RC4应该会比AES效率高一些，理论上加tls后，速度快些，安全性也没问题。但1个月前对比测试时发现tls+AES却比tls+RC4快，而前两天再对比时发现tls+RC4快些。百思不得其解，不知GFW的规律。

**Comment by dujianchi** [comment]
会不会是CPU对AES有硬件加速？据有些资料说，2010年之后的CPU都支持AES-NI（全称是：Advanced Encryption Standard New Instructions），这是针对AES加密算法的硬件加解密CPU指令集。我觉得反正加了AES也差不了那几十毫秒，肉眼上看没差，没准两重加密更安全呢

**Comment by zhfreal** [comment]
感觉和墙及运营商Qos关系更大，当前的硬件处理能力相当于目前的网络带宽而言已经不是瓶颈。

**Comment by Sraw** [comment]
I think you still should use strong encryption. The reason is simple, even your traffic has been encrypted, everyone can connect to your server. Which means the government can also use a simple shadowsocks client to connect to your server.

**Comment by Mygod** [comment]
Cost of symmetric key crypto should be negligible.
