### ISSUE TITLE
failed to listen on address: 127.0.0.1:45345 > listen tcp 127.0.0.1:45345: bind: address already in use

### ISSUE THREAD

**Issue by binsocks** [shadowsocks/v2ray-plugin#96]
```
root@s:~/ss/configs# ss-server -a nobody  /tmp/ss_10001.pid -c /root/ss/configs/10001.json
 2019-06-30 12:37:36 INFO: using tcp fast open
 2019-06-30 12:37:36 INFO: plugin "v2ray-plugin" enabled
 2019-06-30 12:37:36 INFO: UDP relay enabled
 2019-06-30 12:37:36 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-06-30 12:37:36 INFO: tcp server listening at 127.0.0.1:45345
 2019-06-30 12:37:36 INFO: udp server listening at 0.0.0.0:10001
2019/06/30 12:37:36 V2Ray 4.13 (Po) Custom
2019/06/30 12:37:36 A unified platform for anti-censorship.
2019/06/30 12:37:36 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 45345 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:45345 > listen tcp 127.0.0.1:45345: bind: address already in use
 2019-06-30 12:37:36 ERROR: plugin service exit unexpectedly
```
Address doesn't used.

```
root@s:~/ss/configs# cat /root/ss/configs/10001.json
{
    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":10001,
    "local_port":9001,   
    "password":"***",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "fast_open": true,
    "plugin":"v2ray-plugin",
    "plugin-opts":"server;tls;host=*;cert=/etc/letsencrypt/live/*/fullchain.pem;key=/etc/letsencrypt/live/*/privkey.pem"
}
root@s:~/ss/configs# 
```
```
root@s:~/ss/configs# v2ray-plugin -server -tls -host * -cert /etc/letsencrypt/live/*/fullchain.pem -key /etc/letsencrypt/live/*/privkey.pem 
2019/06/30 12:44:09 V2Ray 4.13 (Po) Custom
2019/06/30 12:44:09 A unified platform for anti-censorship.
2019/06/30 12:44:09 [Warning] v2ray.com/core: V2Ray 4.13 started
```
All is ok. ???

iptables -L

```
root@s:~/ss/configs# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
root@s:~/ss/configs# 

```
```
root@s:~/ss/configs# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1137/nginx: master  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1110/sshd           
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1309/master         
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1137/nginx: master  
tcp6       0      0 :::80                   :::*                    LISTEN      1137/nginx: master  
tcp6       0      0 :::22                   :::*                    LISTEN      1110/sshd           
tcp6       0      0 :::25                   :::*                    LISTEN      1309/master         
tcp6       0      0 :::443                  :::*                    LISTEN      1137/nginx: master  
udp        0      0 0.0.0.0:68              0.0.0.0:*                           748/dhclient        
root@s:~/ss/configs# 
```

**Comment by maddie** [comment]
`mode` cannot be `tcp_and_udp` since shadowsocks will listen on port 9001 UDP also, then v2ray plugin will fail.

**Comment by binsocks** [comment]
> `mode` cannot be `tcp_and_udp` since shadowsocks will listen on port 9001 UDP also, then v2ray plugin will fail.

```
root@s:~/ss# cat configs/10001.json
{
    "server":"0.0.0.0",
    "server_port":10001,
    "mode":"tcp_only",
    "local_port":9001,
    "password":"hwA3UzfA",
    "timeout":60,
    "method":"xchacha20-ietf-poly1305",
    "fast_open": true,
    "plugin":"v2ray-plugin",
    "plugin-opts":"server;tls;host=*;cert=/etc/letsencrypt/live/*/fullchain.pem;key=/etc/letsencrypt/live/*/privkey.pem"
}
root@s:~/ss# 
```
```
root@s:~/ss# ss-server -a nobody -d 1.1.1.1,1.0.0.1 -c /root/ss/configs/10001.json
 2019-07-04 19:29:20 INFO: using tcp fast open
 2019-07-04 19:29:20 INFO: plugin "v2ray-plugin" enabled
 2019-07-04 19:29:20 INFO: initializing ciphers... xchacha20-ietf-poly1305
 2019-07-04 19:29:20 INFO: using nameserver: 1.1.1.1,1.0.0.1
 2019-07-04 19:29:20 INFO: tcp server listening at 127.0.0.1:22343
2019/07/04 19:29:20 V2Ray 4.16 (Po) Custom
2019/07/04 19:29:20 A unified platform for anti-censorship.
2019/07/04 19:29:20 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 22343 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:22343 > listen tcp 127.0.0.1:22343: bind: address already in use
 2019-07-04 19:29:20 ERROR: plugin service exit unexpectedly
root@s:~/ss# 
```

**Comment by maddie** [comment]
Try removing `mode` option entirely.

**Comment by binsocks** [comment]
Same.5 июл. 2019 г. 6:21 пользователь maddie <notifications@github.com> написал:Try removing mode option entirely.

**Comment by lcdtyph** [comment]
@binsocks 
In the json config file it should be `plugin_opts` instead of `plugin-opts`.

**Comment by binsocks** [comment]
@lcdtyph

Thank you! But same error.

**Comment by lcdtyph** [comment]
@binsocks 
Emm.. That seems impossible, please post your latest config file and log of `ss-server -c <path to your config>` here.

**Comment by binsocks** [comment]
@lcdtyph 
Thank you, I'm stupid. All works.

**Comment by http600** [comment]
> 

Hi, how did you fix the problem...

**Comment by combrs** [comment]
I'm stupid too and I have similar problem
```
 "server":"aaaa",
 "server_port":443,
 "local_address": "127.0.0.1",
 "local_port":16800,
 "password":"xxxxx",
 "plugin": "ss-v2ray-plugin",
 "plugin_opts":"path=/2acab;host=aaaa;tls",
 "method":"chacha20-ietf-poly1305"

```
$ ss-server -c config.json 
 2022-06-08 21:12:14 INFO: binding to outbound IPv4 addr: 127.0.0.1
 2022-06-08 21:12:14 INFO: plugin "ss-v2ray-plugin" enabled
 2022-06-08 21:12:14 INFO: initializing ciphers... chacha20-ietf-poly1305
 2022-06-08 21:12:14 INFO: tcp server listening at 127.0.0.1:54831
2022/06/08 21:12:14 V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
2022/06/08 21:12:14 A unified platform for anti-censorship.
2022/06/08 21:12:14 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 54831 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.01:54831 > listen tcp 127.0.0.1:54831: bind: address already in use
 2022-06-08 21:12:14 ERROR: plugin service exit unexpectedly

54831 is a random port, new at every run,  an it is not listened
```
sudo ss -anlutp  | grep 54831  
<empty>
```

**Comment by icpz** [comment]
I think you have to append `;server` to `plugin_opts` for ss-server to operate.

**Comment by combrs** [comment]
> I think you have to append `;server` to `plugin_opts` for ss-server to operate.

Yes, if I add server opt then error with port is gone. But it start to complain on 
```
2022/06/09 11:35:02 No TLS cert specified, trying  ..... /fullchain.cer
2022/06/09 11:35:02 main: failed to parse config > main: failed to read cert > open ..../fullchain.cer: no such file or directory
```
I try to use shadowsocks-libev with v2ray plugin as client on local computer for connect to remote server (my own heroku applet)
And I cannot guess what is server and what is client in that case.
server connect url is 
`ss://<key>@<server>.com:443?plugin=v2ray%3Bpath%3D%2F2<path>%3D<server>.com%3Btls`

**Comment by Behrouz-m** [comment]
I have the same error. how did you guys fix it?
**bind: address already in use**

**Comment by z0mb1e-kgd** [comment]
> > I think you have to append `;server` to `plugin_opts` for ss-server to operate.
> 
> Yes, if I add server opt then error with port is gone. But it start to complain on
> 
> ```
> 2022/06/09 11:35:02 No TLS cert specified, trying  ..... /fullchain.cer
> 2022/06/09 11:35:02 main: failed to parse config > main: failed to read cert > open ..../fullchain.cer: no such file or directory
> ```
> 
> I try to use shadowsocks-libev with v2ray plugin as client on local computer for connect to remote server (my own heroku applet) And I cannot guess what is server and what is client in that case. server connect url is `ss://<key>@<server>.com:443?plugin=v2ray%3Bpath%3D%2F2<path>%3D<server>.com%3Btls`
> 
> Android client did not require tls keys setup.. (and work with that ss url)

Разпарсь урл ss:// утилитой ssurl (или ss-url, зависит от реализации клиента) с перенаправлением вывода в произвольный файл с расширением json, например: ss-url ss://... > ~/.v2ray.json. Укажи в нем дополнительно графу "local_port = <любой номер порта>," после графы, например, "server_port". Там же отредактируй строку "plugin" из "v2ray" в "v2ray-plugin". После этого запусти не ss-server, а "ss-local -c <файл.json>". Запустится локальный сервер 127.0.0.1:<номер порта>, который будет перенаправлять пущеный на него трафик на <имя.herokuapp.com:443>. Чтобы работало в фоне, рекомендую оформить в сервис systemd. Но нужно будет либо прописывать переменные окружения ..._proxy, которые читают полторы программы, либо искать настройки прокси в DE (например, в XFCE этого нет), либо редиректить через iptables/nftables - без этого трафик туда не пойдет. Либо, если нужно только для браузера, можно установить расширения, через настройки лазить неудобно. Сам промудохался какое-то время со всем этим хозяйством, проги и документация кривые до жопы, как и всё китайское.

--------------------------------------------

Parse the ss://-url with the ssurl program (or ss-url, depending on the client implementation) redirecting its output to any .json file, i.e. ss-url ss://... > ~/.v2ray.json. Add the "local_port = <any port>," section there. Edit the "plugin" section from "v2ray" to "v2ray-plugin". Run the ss-local program instead of ss-server as follows: ss-local -c <your file>.json. It will spawn the local 127.0.0.1:<port> server, and the traffic should be redirected there for the proxy to actually work.
