### ISSUE TITLE
certRaw option does not work

### ISSUE THREAD

**Issue by zypA13510** [shadowsocks/v2ray-plugin#98]
## Description
When using a self-signed certificate, `certRaw` option does not work as intended, while `cert` option works (on Linux x86_64). On Android, only `certRaw` is supported, and it cannot connect (I have yet to check logcat to confirm, but it didn't work on Linux so probably the same reason).
All tests are done in LAN to eliminate other factors.

#### Generate self-signed certificate
```console
$ sudo openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out /etc/ssl/private/test.key
$ sudo openssl req -x509 -key /etc/ssl/private/test.key -out /etc/ssl/certs/test.pem -days 365 -subj "/CN=example.com" -addext "keyUsage=critical,keyCertSign,cRLSign,digitalSignature,keyEncipherment" -addext "extendedKeyUsage=serverAuth,clientAuth,codeSigning,emailProtection,timeStamping"
```
#### Server-side configuration
```JSON
{
  "...": "...",
  "plugin": "v2ray-plugin",
  "plugin_opts": "server;tls;host=example.com;path=/test;cert=/etc/ssl/certs/test.pem;key=/etc/ssl/private/test.key"
}
```
#### Client-side configuration
```JSON
{
  "...": "...",
  "plugin": "v2ray-plugin",
  "plugin_opts": "tls;host=example.com;path=/test;certRaw=-----BEGIN CERTIFICATE-----MII ... ==-----END CERTIFICATE-----"
}
```
### Expected
Client can proxy through the server.
### Actual result
Client cannot connect. The following log is printed:
> [Info] failed to handler mux client connection > v2ray.com/core/proxy/freedom: failed to open connection to tcp:172.16.1.1:443 > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://172.16.1.1/test):  > x509: certificate signed by unknown authority] > v2ray.com/core/common/retry: all retry attempts failed

## Other information
Usually, PEM(base64)-encoded certificates contain `=` at the end as padding. I'm not sure if it is a parsing issue, and how to escape it (`\=`?), or if quoting the entire string works (`certRaw="-----BEGIN ... END CERTIFICATE-----"`).
Another potential cause could be the missing line breaks (AFAIK it is required by some libraries). I'm not sure how to address this either.

**Comment by lcdtyph** [comment]
It seems that server's certificate is not trusted by your operating system. The certRaw option works fine.

**Comment by zypA13510** [comment]
The `certRaw` option is intended to explicitly trust an untrusted (maybe self-signed) certificate, isn't it?
Also, using the same certificate file in `cert` option will work.

**Comment by lcdtyph** [comment]
Oh, sorry I didn't notice that it's in client side.

I'll track the code later.

**Comment by madeye** [comment]
Please follow the spec here: https://github.com/shadowsocks/shadowsocks-org/wiki/Plugin#passing-arguments-to-a-plugin

```
where semicolons, equal signs and backslashes MUST be escaped with a backslash
```

Also see: https://github.com/shadowsocks/v2ray-plugin/blob/2e56b2b70d12233e336afbaa6788bf5f5c12e2ee/args.go#L45

**Comment by lcdtyph** [comment]
@zypA13510 

While it seems that the missing line break cause your problem on linux/macOS. It works fine when the certRaw contains line breaks from the original cert file.

I don't have an android environment so I can't address this issue on android.

It's fine to not escape '=' in value part according to the code, though it would be better to escape them.

**Comment by zypA13510** [comment]
Ok, will test again and let you know if this is the cause. Thanks for the help.

**Comment by JDalready** [comment]
> 好的，将再次测试，并让您知道是否是原因。谢谢您的帮助。

请问你的证书是哪里申请的

**Comment by br0metheus** [comment]
I am also having this issue. I've spent a few hours tinkering, thinking maybe it wasn't parsing the certificate because of formatting. I am using a self-signed certificate too, which works flawlessly on my two linux machines. In this case however, no matter how I formatted the certificate, with which editor, or how I gave it to the plugin in the android app, it fails to connect. What I see on the server is 

"TLS handshake error from MY_IP:PORT: remote error: tls: bad certificate" 

What is the correct way to format and load the certificate? Would you consider adding an option to import it from a file? I tried using the browse button, but it didn't recognize .pem .crt or .cert files
