### ISSUE TITLE
How to use v2ray-plugin in windows and android Client

### ISSUE THREAD

**Issue by sefira** [shadowsocks/v2ray-plugin#99]
The README.md in the main page only contains the usage for command line, so the question is how to use v2ray-plugin in windows and android client?

Best

**Comment by prajwalkoirala23** [comment]
```
Server Address: [SERVER_IP_ADDRESS]
Server Port: [SERVER_PORT]
Password: [SERVER_PASSWORD]
Encryption: [SERVER_ENCRYPTION_METHOD] 
Plugin Program:[V2RAY_PROGRAM]
Plugin Options:[DOMAIN_NAME]
Remarks:[NICKNAME_FOR_SHADOWSOCKS]
Timeout(sec):[SECONDS]
```

```
Server Address: 104.16.0.0
Server Port: 80
Password: pqmTkSZ5c6ZTtgFpdS
Encryption: chacha20-ietf-poly1305
Plugin Program: v2ray-plugin_windows_amd64
Plugin Options: host=example.com
Remarks: Example
Timeout(sec): 5
```

**Comment by duxiaofeng-github** [comment]
actually, @Prajwal-Koirala is right.

download the release tar.gz. unconpress it and rename the exe file to v2ray.exe.

put it into your shadowsocks folder and open shadowsocks, input "v2ray" to "plugin program" field and input option "host=whatever you want.com".

then it will search the plugin named v2ray in the same folder.

that's it.

**Comment by skykingit** [comment]
> actually, @Prajwal-Koirala is right.
> 
> download the release tar.gz. unconpress it and rename the exe file to v2ray.exe.
> 
> put it into your shadowsocks folder and open shadowsocks, input "v2ray" to "plugin program" field and input option "host=whatever you want.com".
> 
> then it will search the plugin named v2ray in the same folder.
> 
> that's it.



> actually, @Prajwal-Koirala is right.
> 
> download the release tar.gz. unconpress it and rename the exe file to v2ray.exe.
> 
> put it into your shadowsocks folder and open shadowsocks, input "v2ray" to "plugin program" field and input option "host=whatever you want.com".
> 
> then it will search the plugin named v2ray in the same folder.
> 
> that's it.

how to use in android?

**Comment by duxiaofeng-github** [comment]
search v2ray plugin on google play store, install and select it in shadowsocks setting page.
